Config = Config or {}

Config.Houses = {}

Config.OutsideVehicles = {}

Config.Locations = {
    [1] = {
        ['Name'] = "apartment6",
        ['Label'] = "Phillbox Hill",
        ['Coords'] = vector3(-271.00, -957.80, 31.22),
    },
}


Config.GarageSpots = {
    [1] = {
        ['Garage'] = 'Alta Parking',
        ['Coords'] = vector3(-318.08, -974.92, 31.08),
        ['Spots'] = {
            [1] = vector4(-297.72, -989.88, 31.08, 164.21),
            [2] = vector4(-301.15, -988.49, 31.08, 160.00),
            [3] = vector4(-304.83, -987.61, 31.08, 160.00),
            [4] = vector4(-307.95, -986.33, 31.08, 160.00),
            [5] = vector4(-311.62, -985.12, 31.08, 161.26),
        }
    },
    [2] = {
        ['Garage'] = 'Phillbox Parking',
        ['Coords'] = vector3(283.02, -333.69, 45.04),
        ['Spots'] = {
            [1] = vector4(283.31, -342.38, 44.91, 248.92),
            [2] = vector4(284.74, -339.17, 44.91, 248.92),
            [3] = vector4(285.69, -335.89, 44.91, 248.92),
            [4] = vector4(277.12, -340.11, 44.91, 66.10),
            [5] = vector4(278.30, -336.83, 44.91, 66.10),
            [6] = vector4(279.43, -333.59, 44.91, 66.10),
        }
    },
    [3] = {
        ['Garage'] = 'Blokken Parking',
        ['Coords'] = vector3(219.86, -800.81, 30.72),
        ['Spots'] = {
            [1] = vector4(220.49, -806.56, 30.69, 240.71),
            [2] = vector4(221.60, -804.05, 30.69, 240.71),
            [3] = vector4(222.80, -801.57, 30.69, 240.71),
            [4] = vector4(215.76, -804.36, 30.69, 68.45),
            [5] = vector4(216.48, -801.75, 30.69, 68.45),
            [6] = vector4(217.00, -799.08, 30.69, 68.45),
        }
    },
    [4] = {
        ['Garage'] = 'Rode Parking',
        ['Coords'] = vector3(-341.85, -759.61, 33.96),
        ['Spots'] = {
            [1] = vector4(-341.05, -767.32, 33.96, 87.69),
            [2] = vector4(-341.82, -763.98, 33.96, 87.69),
            [3] = vector4(-341.98, -760.19, 33.96, 268.24),
            [4] = vector4(-341.78, -756.87, 33.96, 87.69),
            [5] = vector4(-341.78, -753.21, 33.96, 87.69),
        }
    },
    [5] = {
        ['Garage'] = 'Haan Parking',
        ['Coords'] = vector3(69.64, 6395.37, 31.23),
        ['Spots'] = {
            [1] = vector4(62.28, 6403.58, 31.22, 32.89),
            [2] = vector4(59.37, 6400.46, 31.22, 32.89),
            [3] = vector4(65.02, 6405.86, 31.22, 32.89),
            [4] = vector4(72.11, 6403.87, 31.22, 310.32),
            [5] = vector4(75.05, 6401.27, 31.22, 310.32),
        }
    },
}

Config.DepotSpots = {
    [1] = vector4(-194.48, -1173.57, 23.04, 192.74),
    [2] = vector4(-191.24, -1173.26, 23.04, 194.86),
    [3] = vector4(-187.66, -1173.72, 23.04, 195.35),
    [4] = vector4(-184.01, -1173.63, 23.04, 198.56),
}

Config.Furniture = {
	["sofas"] = {
		label = "Banken",
		items = {
			[1] = { ["object"] = "miss_rub_couch_01", ["price"] = 300, ["label"] = "Oude bank" },
			[2] = { ["object"] = "prop_fib_3b_bench", ["price"] = 700, ["label"] = "Driezits bankje" },
			[3] = { ["object"] = "prop_ld_farm_chair01", ["price"] = 250, ["label"] = "Oude stoel" },
			[4] = { ["object"] = "prop_ld_farm_couch01", ["price"] = 300, ["label"] = "Oude driezits bank" },
			[5] = { ["object"] = "prop_ld_farm_couch02", ["price"] = 300, ["label"] = "Oude gestreepte bank" },
			[6] = { ["object"] = "v_res_d_armchair", ["price"] = 300, ["label"] = "Old 1 Seat Couch Yellow" },
			[7] = { ["object"] = "v_res_fh_sofa", ["price"] = 3700, ["label"] = "Hoekbank" },
			[8] = { ["object"] = "v_res_mp_sofa", ["price"] = 3700, ["label"] = "Hoekbank 2" },
			[9] = { ["object"] = "v_res_d_sofa", ["price"] = 700, ["label"] = "Bank 1" },
			[10] = { ["object"] = "v_res_j_sofa", ["price"] = 700, ["label"] = "Bank 2" },
			[11] = { ["object"] = "v_res_mp_stripchair", ["price"] = 700, ["label"] = "Bank 3" },
			[12] = { ["object"] = "v_res_m_h_sofa_sml", ["price"] = 700, ["label"] = "Bank 4" },
			[13] = { ["object"] = "v_res_r_sofa", ["price"] = 700, ["label"] = "Bank 5" },
			[14] = { ["object"] = "v_res_tre_sofa", ["price"] = 700, ["label"] = "Bank 6" },
			[15] = { ["object"] = "v_res_tre_sofa_mess_a", ["price"] = 700, ["label"] = "Bank 7" },
			[16] = { ["object"] = "v_res_tre_sofa_mess_b", ["price"] = 700, ["label"] = "Bank 8" },
			[17] = { ["object"] = "v_res_tre_sofa_mess_c", ["price"] = 700, ["label"] = "Bank 9" },
			[18] = { ["object"] = "v_res_tt_sofa", ["price"] = 700, ["label"] = "Bank 10" },
			[19] = { ["object"] = "prop_rub_couch02", ["price"] = 700, ["label"] = "Bank 11" },
			[20] = { ["object"] = "v_ilev_m_sofa", ["price"] = 2000, ["label"] = "witte bank" },
			[21] = { ["object"] = "v_med_p_sofa", ["price"] = 1000, ["label"] = "leren bank bruin" },
			[22] = { ["object"] = "v_club_officesofa", ["price"] = 500, ["label"] = "pauper bank rood" },
			[23] = { ["object"] = "bkr_prop_clubhouse_sofa_01a", ["price"] = 1000, ["label"] = "zwarte bank" },
			[24] = { ["object"] = "apa_mp_h_stn_sofacorn_01", ["price"] = 5000, ["label"] = "hoekbank 3" },
			[25] = { ["object"] = "prop_couch_lg_02", ["price"] = 1000, ["label"] = "bank hout" },
			[26] = { ["object"] = "apa_mp_h_stn_sofacorn_10", ["price"] = 5000, ["label"] = "hoekbank 4" },
			[27] = { ["object"] = "apa_mp_h_yacht_sofa_02", ["price"] = 1000, ["label"] = "bruine bank" },
			[28] = { ["object"] = "apa_mp_h_yacht_sofa_01", ["price"] = 5000, ["label"] = "witte lange bank" }
		},
	},
	["chairs"] = {
		label = "Stoelen",
		items = {
			[1] = { ["object"] = "v_res_d_highchair", ["price"] = 700, ["label"] = "Hoge stoel" },
			[2] = { ["object"] = "apa_mp_h_stn_chairstrip_03", ["price"] = 500, ["label"] = "zitstoel 4" },
			[3] = { ["object"] = "v_res_fa_chair01", ["price"] = 700, ["label"] = "Stoel" },
			[4] = { ["object"] = "v_res_fa_chair02", ["price"] = 700, ["label"] = "Stoel 2" },
			[5] = { ["object"] = "v_res_fh_barcchair", ["price"] = 700, ["label"] = "Hoge stoel 2" },
			[6] = { ["object"] = "v_res_fh_dineeamesa", ["price"] = 700, ["label"] = "Keukenstoel 1" },
			[7] = { ["object"] = "v_res_fh_dineeamesb", ["price"] = 700, ["label"] = "Keukenstoel 2" },
			[8] = { ["object"] = "v_res_fh_dineeamesc", ["price"] = 700, ["label"] = "Keukenstoel 3" },
			[9] = { ["object"] = "v_res_fh_easychair", ["price"] = 700, ["label"] = "Stoel 3" },
			[10] = { ["object"] = "v_res_fh_kitnstool", ["price"] = 700, ["label"] = "Stoel 4" },
			[11] = { ["object"] = "v_res_fh_singleseat", ["price"] = 700, ["label"] = "Hoge stoel 3" },
			[12] = { ["object"] = "v_res_jarmchair", ["price"] = 700, ["label"] = "Arm stoel" },
			[13] = { ["object"] = "v_res_j_dinechair", ["price"] = 700, ["label"] = "Keukenstoel 4" },
			[14] = { ["object"] = "v_res_j_stool", ["price"] = 700, ["label"] = "Stoel 5" },
			[15] = { ["object"] = "v_res_mbchair", ["price"] = 700, ["label"] = "MB Stoel" },
			[16] = { ["object"] = "v_res_m_armchair", ["price"] = 700, ["label"] = "Arm stoel 2" },
			[17] = { ["object"] = "v_res_m_dinechair", ["price"] = 700, ["label"] = "Keukenstoel 5" },
			[18] = { ["object"] = "v_res_study_chair", ["price"] = 700, ["label"] = "Studeer stoel" },
			[19] = { ["object"] = "v_res_trev_framechair", ["price"] = 700, ["label"] = "Stoel frame" },
			[20] = { ["object"] = "v_res_tre_chair", ["price"] = 700, ["label"] = "Stoel 5" },
			[21] = { ["object"] = "v_res_tre_officechair", ["price"] = 700, ["label"] = "Kantoorstoel" },
			[22] = { ["object"] = "v_res_tre_stool", ["price"] = 700, ["label"] = "Stoel 6" },
			[23] = { ["object"] = "v_res_tre_stool_leather", ["price"] = 700, ["label"] = "Leren stoel" },
			[24] = { ["object"] = "v_res_tre_stool_scuz", ["price"] = 700, ["label"] = "Stoel Scuz" },
			[25] = { ["object"] = "v_med_p_deskchair", ["price"] = 700, ["label"] = "Bureaustoel" },
			[26] = { ["object"] = "v_med_p_easychair", ["price"] = 700, ["label"] = "Gemakkelijke stoel" },
			[27] = { ["object"] = "v_med_whickerchair1", ["price"] = 700, ["label"] = "Whicker Stoel" },
			[28] = { ["object"] = "prop_direct_chair_01", ["price"] = 700, ["label"] = "Regiseur Stoel" },
			[29] = { ["object"] = "prop_direct_chair_02", ["price"] = 700, ["label"] = "Regiseur Stoel 2" },
			[30] = { ["object"] = "prop_yacht_lounger", ["price"] = 700, ["label"] = "Yacht Stoel 1" },
			[31] = { ["object"] = "prop_yacht_seat_01", ["price"] = 700, ["label"] = "Yacht Stoel 2" },
			[32] = { ["object"] = "prop_yacht_seat_02", ["price"] = 700, ["label"] = "Yacht Stoel 3" },
			[33] = { ["object"] = "prop_yacht_seat_03", ["price"] = 700, ["label"] = "Yacht Stoel 4" },
			[34] = { ["object"] = "v_ret_chair_white", ["price"] = 100, ["label"] = "Witte stoel" },
			[35] = { ["object"] = "v_ret_chair", ["price"] = 100, ["label"] = "Stoel 7" },
			[36] = { ["object"] = "v_ret_ta_stool", ["price"] = 100, ["label"] = "TA Stoel" },
			[37] = { ["object"] = "prop_cs_office_chair", ["price"] = 100, ["label"] = "Kantoorstoel 2" },
			[38] = { ["object"] = "apa_mp_h_yacht_armchair_01", ["price"] = 1000, ["label"] = "Witte fauteuil" },
			[39] = { ["object"] = "v_club_barchair", ["price"] = 300, ["label"] = "Stoel 8" },
			[40] = { ["object"] = "prop_off_chair_04", ["price"] = 300, ["label"] = "Bureaustoel 2" },
			[41] = { ["object"] = "v_club_stagechair", ["price"] = 500, ["label"] = "Fauteuil roze" },
			[42] = { ["object"] = "v_club_officechair", ["price"] = 500, ["label"] = "Bureaustoel 3" },
			[43] = { ["object"] = "prop_armchair_01", ["price"] = 500, ["label"] = "Zitstoel" },
			[44] = { ["object"] = "prop_bar_stool_01", ["price"] = 300, ["label"] = "Barkruk" },
			[45] = { ["object"] = "apa_mp_h_yacht_stool_01", ["price"] = 300, ["label"] = "Witte pouffe" },
			[46] = { ["object"] = "apa_mp_h_stn_chairarm_12", ["price"] = 500, ["label"] = "Zitstoel 3" },
			[47] = { ["object"] = "apa_mp_h_stn_chairstool_12", ["price"] = 300, ["label"] = "Voetensteun" },
			[48] = { ["object"] = "v_ret_gc_chair01", ["price"] = 100, ["label"] = "GC Chair 01" },
			[49] = { ["object"] = "v_ret_gc_chair02", ["price"] = 100, ["label"] = "GC Chair 02" },
			[50] = { ["object"] = "prop_chair_03", ["price"] = 100, ["label"] = "Houten stoel" }
		},
	},
	["beds"] = {
		label = "Bedden",
		items = {
			[1] = { ["object"] = "v_res_d_bed", ["price"] = 700, ["label"] = "Oranje bed" },	
			[2] = { ["object"] = "v_res_lestersbed", ["price"] = 700, ["label"] = "Houten bed klein" },	
			[3] = { ["object"] = "v_res_mbbed", ["price"] = 700, ["label"] = "Klasiek bed bruin" },	
			[4] = { ["object"] = "v_res_mdbed", ["price"] = 700, ["label"] = "Klasiek bed wit" },	
			[5] = { ["object"] = "v_res_msonbed", ["price"] = 700, ["label"] = "Leren bed" },	
			[6] = { ["object"] = "v_res_tre_bed1", ["price"] = 700, ["label"] = "Houten bed groen" },	
			[7] = { ["object"] = "v_res_tre_bed2", ["price"] = 700, ["label"] = "Houten bed blauw" },	
			[8] = { ["object"] = "v_res_tt_bed", ["price"] = 700, ["label"] = "Vuil bed" },
			[9] = { ["object"] = "apa_mp_h_bed_with_table_02", ["price"] = 5000, ["label"] = "Modern bed" },
			[10] = { ["object"] = "apa_mp_h_bed_wide_05", ["price"] = 5000, ["label"] = "Rood bed" },
			[11] = { ["object"] = "bkr_prop_biker_campbed_01", ["price"] = 100, ["label"] = "Veldbed" },
			[12] = { ["object"] = "v_res_tt_bedpillow", ["price"] = 300, ["label"] = "Hoodkussen 1" },
			[13] = { ["object"] = "v_res_tre_cushiona", ["price"] = 300, ["label"] = "Hoodkussen 2" },
			[14] = { ["object"] = "v_res_tre_cushionb", ["price"] = 300, ["label"] = "Hoodkussen 3" },
			[15] = { ["object"] = "v_res_tre_cushionc", ["price"] = 300, ["label"] = "Hoodkussen 4" },
			[16] = { ["object"] = "v_res_tre_cushiond", ["price"] = 300, ["label"] = "Hoodkussen 5" },
			[17] = { ["object"] = "v_res_tre_cushnscuzb", ["price"] = 300, ["label"] = "Hoodkussen 6" },
			[18] = { ["object"] = "v_res_tre_cushnscuzd", ["price"] = 300, ["label"] = "Hoodkussen 7" }
		},	
	},
	["general"] = {
		label = "Algemeen",
		items = {
			[1] = { ["object"] = "v_corp_facebeanbag", ["price"] = 100, ["label"] = "Bean Bag 1" },
			[2] = { ["object"] = "v_res_cherubvase", ["price"] = 2500, ["label"] = "White Vase" },
			[3] = { ["object"] = "v_res_d_paddedwall", ["price"] = 300, ["label"] = "Padded Wall" },
			[4] = { ["object"] = "v_res_d_ramskull", ["price"] = 300, ["label"] = "Ram schedel" },
			[5] = { ["object"] = "v_res_d_whips", ["price"] = 300, ["label"] = "Zweepjes" },
			[6] = { ["object"] = "v_res_fashmag1", ["price"] = 300, ["label"] = "Tijdschrift" },
			[7] = { ["object"] = "v_res_fashmagopen", ["price"] = 300, ["label"] = "Tijdschrift Open" },
			[8] = { ["object"] = "v_res_fa_magtidy", ["price"] = 300, ["label"] = "Tijdschrift mandje 2" },
			[9] = { ["object"] = "v_res_fa_yogamat002", ["price"] = 300, ["label"] = "Yoga Mat 1" },
			[10] = { ["object"] = "v_res_fa_yogamat1", ["price"] = 300, ["label"] = "Yoga Mat 2" },
			[11] = { ["object"] = "prop_yoga_mat_01", ["price"] = 100, ["label"] = "Yoga Mat 1" },
			[12] = { ["object"] = "prop_yoga_mat_02", ["price"] = 100, ["label"] = "Yoga Mat 2" },
			[13] = { ["object"] = "prop_yoga_mat_03", ["price"] = 100, ["label"] = "Yoga Mat 3" },
			[14] = { ["object"] = "v_res_fh_aftershavebox", ["price"] = 300, ["label"] = "Aftershave" },
			[15] = { ["object"] = "v_res_fh_fruitbowl", ["price"] = 300, ["label"] = "Fruitmandje" },
			[16] = { ["object"] = "v_res_fh_laundrybasket", ["price"] = 300, ["label"] = "Wasmand" },
			[17] = { ["object"] = "v_res_fh_pouf", ["price"] = 300, ["label"] = "Pouf" },
			[18] = { ["object"] = "v_res_fh_sculptmod", ["price"] = 300, ["label"] = "Groot beeld" },
			[19] = { ["object"] = "v_res_j_magrack", ["price"] = 300, ["label"] = "Tijdschrift mandje 2" },
			[20] = { ["object"] = "v_res_jewelbox", ["price"] = 300, ["label"] = "Juwelen doosje" },
			[21] = { ["object"] = "v_res_mbbin", ["price"] = 300, ["label"] = "Vuilbakje" },
			[22] = { ["object"] = "v_res_mbowlornate", ["price"] = 300, ["label"] = "fruitmandje" },
			[23] = { ["object"] = "v_res_mbronzvase", ["price"] = 300, ["label"] = "Bronze vaas" },
			[24] = { ["object"] = "v_res_mchalkbrd", ["price"] = 300, ["label"] = "Krijtbord" },
			[25] = { ["object"] = "v_res_mp_ashtrayb", ["price"] = 300, ["label"] = "Asbak blauw" },
			[26] = { ["object"] = "prop_ashtray_01", ["price"] = 100, ["label"] = "asbak zwart" },
			[27] = { ["object"] = "v_ret_fh_ashtray", ["price"] = 100, ["label"] = "asbak steen" },
			[28] = { ["object"] = "v_res_m_kscales", ["price"] = 300, ["label"] = "Weegschaal" },
			[29] = { ["object"] = "v_med_cor_whiteboard", ["price"] = 300, ["label"] = "whiteboard" },
			[30] = { ["object"] = "apa_mp_h_acc_rugwooll_04", ["price"] = 500, ["label"] = "kleed 1" },
			[31] = { ["object"] = "ex_mp_h_acc_rugwoolm_04", ["price"] = 500, ["label"] = "kleed 2" },
			[32] = { ["object"] = "apa_mp_h_acc_rugwoolm_03", ["price"] = 500, ["label"] = "kleed 3" },
			[33] = { ["object"] = "apa_mp_h_acc_rugwooll_03", ["price"] = 500, ["label"] = "kleed 4" },
			[34] = { ["object"] = "apa_mp_h_acc_rugwoolm_04", ["price"] = 500, ["label"] = "kleed 5" },
			[35] = { ["object"] = "hei_mpheist_yacht_ab_03", ["price"] = 500, ["label"] = "Piano" },
			[36] = { ["object"] = "apa_mp_h_acc_rugwoolm_04", ["price"] = 500, ["label"] = "kleed 6" },
			[37] = { ["object"] = "apa_mp_h_acc_rugwoolm_01", ["price"] = 500, ["label"] = "kleed 7" },
			[38] = { ["object"] = "apa_mp_h_acc_rugwoolm_02", ["price"] = 500, ["label"] = "kleed 8" },
			[39] = { ["object"] = "hei_heist_acc_rughidel_01", ["price"] = 500, ["label"] = "kleed 9" },
			[40] = { ["object"] = "hei_heist_acc_rugwooll_01", ["price"] = 500, ["label"] = "kleed 10" },
			[41] = { ["object"] = "apa_mp_h_acc_rugwools_03", ["price"] = 500, ["label"] = "kleed 11" },
			[42] = { ["object"] = "ex_office_swag_ivory4", ["price"] = 500, ["label"] = "Diervel voor op de bank" },
			[43] = { ["object"] = "v_club_rack", ["price"] = 500, ["label"] = "kledingrek" },
			[44] = { ["object"] = "prop_surf_board_04", ["price"] = 250, ["label"] = "Surfbord" },
			[45] = { ["object"] = "v_ilev_ra_doorsafe", ["price"] = 250, ["label"] = "Napoleon" },
			[46] = { ["object"] = "v_ilev_mchalkbrd_3", ["price"] = 250, ["label"] = "Vol krijtbord" },
			[47] = { ["object"] = "prop_crate_03a", ["price"] = 250, ["label"] = "Krat fruit" },
			[48] = { ["object"] = "prop_crate_04a", ["price"] = 250, ["label"] = "Krat decoratie" },
			[49] = { ["object"] = "prop_crate_05a", ["price"] = 250, ["label"] = "Krat opslag" },
			[50] = { ["object"] = "prop_crate_06a", ["price"] = 250, ["label"] = "Krat bier leeg" },
			[51] = { ["object"] = "prop_crate_09a", ["price"] = 250, ["label"] = "Krat pallet" },
			[52] = { ["object"] = "prop_wateringcan", ["price"] = 250, ["label"] = "Gieter" },
			[53] = { ["object"] = "prop_golf_bag_01c", ["price"] = 100, ["label"] = "golftas" },
			[54] = { ["object"] = "hei_heist_kit_bin_01", ["price"] = 100, ["label"] = "prullenbak" },
			[55] = { ["object"] = "apa_mp_h_acc_scent_sticks_01", ["price"] = 100, ["label"] = "Geur stokjes" },
			[56] = { ["object"] = "ex_prop_exec_award_plastic", ["price"] = 100, ["label"] = "Award Zwart" },
			[57] = { ["object"] = "prop_strip_pole_01", ["price"] = 250, ["label"] = "Strip paal" }
		},
	},
	["general2"] = {
		label = "Objecten",
		items = {
			[1] = { ["object"] = "prop_a4_pile_01", ["price"] = 100, ["label"] = "A4 hoopje 1" },
			[2] = { ["object"] = "prop_barry_table_detail", ["price"] = 100, ["label"] = "A4 hoopje 2" },
			[3] = { ["object"] = "prop_cs_binder_01", ["price"] = 100, ["label"] = "Map met papier" },
			[4] = { ["object"] = "v_med_p_notebook", ["price"] = 100, ["label"] = "Aantekeningen" },
			[5] = { ["object"] = "prop_cs_lester_crate", ["price"] = 100, ["label"] = "Doos met papieren" },
			[6] = { ["object"] = "prop_amb_40oz_03", ["price"] = 100, ["label"] = "Alcohol fles" },
			[7] = { ["object"] = "ba_prop_club_champset", ["price"] = 300, ["label"] = "Champagneset" },
			[8] = { ["object"] = "prop_champ_cool", ["price"] = 100, ["label"] = "Champagnekoeler" },
			[9] = { ["object"] = "prop_champ_01b", ["price"] = 100, ["label"] = "Champagnefles" },
			[10] = { ["object"] = "prop_champ_flute", ["price"] = 100, ["label"] = "Champagneglas 1" },
			[11] = { ["object"] = "prop_cs_champ_flute", ["price"] = 100, ["label"] = "Champagneglas 2" },
			[12] = { ["object"] = "prop_cs_whiskey_bottle", ["price"] = 100, ["label"] = "Whiskey Fles" },
			[13] = { ["object"] = "prop_tumbler_01", ["price"] = 100, ["label"] = "Whiskey Glas" },
			[14] = { ["object"] = "prop_amb_beer_bottle", ["price"] = 100, ["label"] = "Bier fles" },
			[15] = { ["object"] = "prop_beer_box_01", ["price"] = 100, ["label"] = "Bier doos 1" },
			[16] = { ["object"] = "prop_cs_beer_box", ["price"] = 100, ["label"] = "Bier doos 2" },
			[17] = { ["object"] = "prop_binoc_01", ["price"] = 100, ["label"] = "Verrekijker" },
			[18] = { ["object"] = "prop_blox_spray", ["price"] = 100, ["label"] = "Blox spuit" },
			[19] = { ["object"] = "prop_bongos_01", ["price"] = 100, ["label"] = "Bongos" },
			[20] = { ["object"] = "prop_bong_01", ["price"] = 100, ["label"] = "Bong" },
			[21] = { ["object"] = "prop_boombox_01", ["price"] = 100, ["label"] = "Boombox" },
			[22] = { ["object"] = "prop_bowl_crisps", ["price"] = 100, ["label"] = "Bakje ships" },
			[23] = { ["object"] = "prop_candy_pqs", ["price"] = 100, ["label"] = "Snoepjes" },
			[24] = { ["object"] = "prop_carrier_bag_01", ["price"] = 100, ["label"] = "Zakje 247" },
			[25] = { ["object"] = "p_ld_bs_bag_01", ["price"] = 100, ["label"] = "Papieren zakje" },
			[26] = { ["object"] = "prop_cs_sack_01", ["price"] = 100, ["label"] = "Stoffen zakje" },
			[27] = { ["object"] = "prop_cs_street_binbag_01", ["price"] = 100, ["label"] = "vuilniszak" },
			[28] = { ["object"] = "prop_ceramic_jug_01", ["price"] = 100, ["label"] = "Ceramic Jug" },
			[29] = { ["object"] = "prop_cigar_pack_01", ["price"] = 100, ["label"] = "Sigaretten pakje 1" },
			[30] = { ["object"] = "prop_cigar_pack_02", ["price"] = 100, ["label"] = "Sigaretten pakje 2" },
			[31] = { ["object"] = "prop_cs_bs_cup", ["price"] = 100, ["label"] = "Drinkbeker" },
			[32] = { ["object"] = "prop_cs_cashenvelope", ["price"] = 100, ["label"] = "Envelop" },
			[33] = { ["object"] = "prop_cs_duffel_01", ["price"] = 100, ["label"] = "Duffel Bag" },
			[34] = { ["object"] = "prop_cs_dvd", ["price"] = 50, ["label"] = "DVD" },
			[35] = { ["object"] = "prop_cs_dvd_case", ["price"] = 50, ["label"] = "DVD doosje" },
			[36] = { ["object"] = "prop_cs_film_reel_01", ["price"] = 100, ["label"] = "Film doosje" },
			[37] = { ["object"] = "prop_cs_ironing_board", ["price"] = 100, ["label"] = "strijkplank" },
			[38] = { ["object"] = "prop_cs_katana_01", ["price"] = 100, ["label"] = "Katana" },
			[39] = { ["object"] = "prop_cs_petrol_can", ["price"] = 100, ["label"] = "Diesel doos" },
			[40] = { ["object"] = "prop_cs_script_bottle_01", ["price"] = 100, ["label"] = "Medicatie flesje 1" },
			[41] = { ["object"] = "prop_cs_script_bottle", ["price"] = 100, ["label"] = "Medicatie flesje 2" },
			[42] = { ["object"] = "prop_sh_bong_01", ["price"] = 100, ["label"] = "Bong" },
			[43] = { ["object"] = "prop_peanut_bowl_01", ["price"] = 100, ["label"] = "Pindanootjes" },
			[44] = { ["object"] = "p_cs_lighter_01", ["price"] = 100, ["label"] = "aansteker" },
			[45] = { ["object"] = "p_cs_papers_01", ["price"] = 100, ["label"] = "vloeitjes" },
			[46] = { ["object"] = "v_res_m_candle", ["price"] = 300, ["label"] = "Kaars" },
			[47] = { ["object"] = "v_res_m_candlelrg", ["price"] = 300, ["label"] = "Grote kaars" },
			[48] = { ["object"] = "v_res_fa_candle01", ["price"] = 100, ["label"] = "kaars blauw" },
			[49] = { ["object"] = "v_res_fa_candle02", ["price"] = 100, ["label"] = "kaars rood" },
			[50] = { ["object"] = "v_res_fa_candle03", ["price"] = 100, ["label"] = "kaars groen" },
			[51] = { ["object"] = "v_res_fa_candle04", ["price"] = 100, ["label"] = "kaars klein" },
			[52] = { ["object"] = "v_med_bottles2", ["price"] = 100, ["label"] = "chemicalien" },
			[53] = { ["object"] = "v_res_desktidy", ["price"] = 100, ["label"] = "kantoorspullen" },
			[54] = { ["object"] = "bkr_prop_weed_dry_01a", ["price"] = 100, ["label"] = "bergje wiet" },
			[55] = { ["object"] = "ba_prop_battle_trophy_battler", ["price"] = 100, ["label"] = "fist trofee" },
			[56] = { ["object"] = "ba_prop_battle_trophy_no1", ["price"] = 100, ["label"] = "ster trofee" },
			[57] = { ["object"] = "prop_golf_bag_01c", ["price"] = 100, ["label"] = "golftas" },
			[58] = { ["object"] = "hei_heist_kit_bin_01", ["price"] = 100, ["label"] = "prullenbak" },
			[59] = { ["object"] = "prop_wooden_barrel", ["price"] = 100, ["label"] = "houten vat" },
			[60] = { ["object"] = "prop_mb_sandblock_01", ["price"] = 100, ["label"] = "Zandblok x1" },
			[61] = { ["object"] = "prop_mb_sandblock_02", ["price"] = 100, ["label"] = "Zandblok x3" },
			[62] = { ["object"] = "p_pallet_02a_s", ["price"] = 100, ["label"] = "Pallet" },
			[63] = { ["object"] = "ch_chint03_pallet_pile_01", ["price"] = 100, ["label"] = "Pallet gestapeld" },
			[64] = { ["object"] = "ex_prop_crate_money_bc", ["price"] = 100, ["label"] = "Pallet met geld" },
			[65] = { ["object"] = "hei_prop_heist_weed_pallet", ["price"] = 100, ["label"] = "Pallet met wiet" },
			[66] = { ["object"] = "sm_prop_smug_crate_m_narc", ["price"] = 100, ["label"] = "Pallet met wiet 2" },	
			[67] = { ["object"] = "prop_paints_pallete01", ["price"] = 100, ["label"] = "Pallet met verf" },
			[68] = { ["object"] = "ex_prop_crate_art_02_sc", ["price"] = 100, ["label"] = "Pallet met kunstwerken" },
			[69] = { ["object"] = "sm_prop_smug_crate_m_medical", ["price"] = 100, ["label"] = "Pallet met medische spullen" },
			[70] = { ["object"] = "sm_prop_smug_crate_m_tobacco", ["price"] = 100, ["label"] = "Pallet met tabacco" },
			[71] = { ["object"] = "sm_prop_smug_crate_s_jewellery", ["price"] = 100, ["label"] = "Pallet met juwelen" },
			[72] = { ["object"] = "p_secret_weapon_02", ["price"] = 100, ["label"] = "Pallet met milcrates" },
			[73] = { ["object"] = "bkr_prop_bkr_cashpile_01", ["price"] = 100, ["label"] = "Stapeltje geld 1" },
			[74] = { ["object"] = "bkr_prop_bkr_cashpile_05", ["price"] = 100, ["label"] = "Stapeltje geld 2" },
			[75] = { ["object"] = "prop_flattruck_01d", ["price"] = 100, ["label"] = "Karretje met dozen" },
			[76] = { ["object"] = "bkr_int_w03_pallettruck", ["price"] = 100, ["label"] = "Transpalet" },
			[77] = { ["object"] = "v_55_tor_mesh_forklift", ["price"] = 100, ["label"] = "Vorklift" },
			[78] = { ["object"] = "prop_rub_pile_03", ["price"] = 100, ["label"] = "Autobanden" },
			[79] = { ["object"] = "prop_fleeca_atm", ["price"] = 100, ["label"] = "Bank ATM" },
			[80] = { ["object"] = "sm_prop_smug_crate_s_jewellery", ["price"] = 100, ["label"] = "Zwarte doos juwelen" },
			[81] = { ["object"] = "ex_office_swag_guns02", ["price"] = 100, ["label"] = "Ammo boxes" },
			[82] = { ["object"] = "v_ilev_fib_door3", ["price"] = 100, ["label"] = "Deur" },
			[83] = { ["object"] = "prop_golf_bag_01c", ["price"] = 100, ["label"] = "golftas" },
			[84] = { ["object"] = "hei_heist_kit_bin_01", ["price"] = 100, ["label"] = "prullenbak" },
			[85] = { ["object"] = "apa_mp_h_acc_scent_sticks_01", ["price"] = 100, ["label"] = "Geur stokjes" },
			[86] = { ["object"] = "ex_prop_exec_award_plastic", ["price"] = 100, ["label"] = "Award Zwart" },
			[87] = { ["object"] = "prop_strip_pole_01", ["price"] = 250, ["label"] = "Strip paal" }

		},
	},
	["general3"] = {
		label = "Random",
		items = {
			[1] = { ["object"] = "v_ret_csr_bin", ["price"] = 100, ["label"] = "Vuilnisbak 1" },
			[2] = { ["object"] = "v_ret_gc_bin", ["price"] = 100, ["label"] = "Vuilnisbak 2" },
			[3] = { ["object"] = "v_ret_fh_wickbskt", ["price"] = 100, ["label"] = "Wasmandje" },
			[4] = { ["object"] = "v_ret_gc_bag01", ["price"] = 100, ["label"] = "Duffle bag 1" },
			[5] = { ["object"] = "v_ret_gc_bag02", ["price"] = 100, ["label"] = "Duffle bag 2" },
			[6] = { ["object"] = "prop_big_bag_01", ["price"] = 100, ["label"] = "Duffle bag 3" },
			[7] = { ["object"] = "v_ret_gc_cashreg", ["price"] = 100, ["label"] = "Kassa" },
			[8] = { ["object"] = "v_ret_gc_clock", ["price"] = 100, ["label"] = "Clock" },
			[9] = { ["object"] = "v_ret_ps_bag_01", ["price"] = 100, ["label"] = "Leren tas 1" },
			[10] = { ["object"] = "v_ret_ps_bag_02", ["price"] = 100, ["label"] = "Leren Tas 2" },
			[11] = { ["object"] = "prop_amb_handbag_01", ["price"] = 100, ["label"] = "Leren tas open" },
			[12] = { ["object"] = "v_ret_ta_book1", ["price"] = 100, ["label"] = "Boek 1" },
			[13] = { ["object"] = "v_ret_ta_book2", ["price"] = 100, ["label"] = "Boek 2" },
			[14] = { ["object"] = "v_ret_ta_book3", ["price"] = 100, ["label"] = "Boek 3" },
			[15] = { ["object"] = "v_ret_ta_book4", ["price"] = 100, ["label"] = "Boek 4" },
			[16] = { ["object"] = "v_res_fa_book03", ["price"] = 100, ["label"] = "Boek 5" },
			[17] = { ["object"] = "v_ret_ta_camera", ["price"] = 100, ["label"] = "Camera" },
			[18] = { ["object"] = "v_ret_ta_hero", ["price"] = 100, ["label"] = "Beeldje held" },
			[19] = { ["object"] = "v_ret_ta_mag1", ["price"] = 100, ["label"] = "Tijdschriften 1" },
			[20] = { ["object"] = "v_ret_ta_mag2", ["price"] = 100, ["label"] = "Tijdschriften 2" },
			[21] = { ["object"] = "v_ret_ta_skull", ["price"] = 100, ["label"] = "Schedel roze" },
			[22] = { ["object"] = "prop_acc_guitar_01", ["price"] = 100, ["label"] = "Gitaar 1" },
			[23] = { ["object"] = "prop_el_guitar_01", ["price"] = 100, ["label"] = "Gitaar 2" },
			[24] = { ["object"] = "prop_el_guitar_02", ["price"] = 100, ["label"] = "Gitaar 3" },
			[25] = { ["object"] = "prop_el_guitar_03", ["price"] = 100, ["label"] = "Gitaar 3" },
			[26] = { ["object"] = "prop_attache_case_01", ["price"] = 100, ["label"] = "Case" },
			[27] = { ["object"] = "prop_cs_shopping_bag", ["price"] = 100, ["label"] = "Shopping Bag" },
			[28] = { ["object"] = "prop_cs_vial_01", ["price"] = 100, ["label"] = "Flesje" },
			[29] = { ["object"] = "prop_defilied_ragdoll_01", ["price"] = 100, ["label"] = "Voodoo" }, 
			[30] = { ["object"] = "prop_weight_rack_02", ["price"] = 500, ["label"] = "Dumbbellrek" },
			[31] = { ["object"] = "prop_weight_bench_02", ["price"] = 500, ["label"] = "Bankdrukset" },
			[32] = { ["object"] = "prop_tool_broom", ["price"] = 100, ["label"] = "Bezem" },
			[33] = { ["object"] = "prop_fire_exting_2a", ["price"] = 100, ["label"] = "Brandblusser" },
			[34] = { ["object"] = "v_res_vacuum", ["price"] = 100, ["label"] = "Stofzuiger" },
			[35] = { ["object"] = "v_ret_gc_fan", ["price"] = 100, ["label"] = "Ventilator" },
			[36] = { ["object"] = "prop_paint_stepl01b", ["price"] = 100, ["label"] = "Ladder" },
			[37] = { ["object"] = "bkr_prop_weed_bucket_01b", ["price"] = 100, ["label"] = "Kunstmest 1" },
			[38] = { ["object"] = "prop_cs_fertilizer", ["price"] = 100, ["label"] = "Kunstmest 2" },
			[39] = { ["object"] = "v_club_vusnaketank", ["price"] = 500, ["label"] = "Terrarium" },
			[40] = { ["object"] = "prop_pooltable_02", ["price"] = 1500, ["label"] = "Pooltafel" },
			[41] = { ["object"] = "prop_pool_rack_02", ["price"] = 100, ["label"] = "Poolcues" },
			[42] = { ["object"] = "v_club_vu_deckcase", ["price"] = 1000, ["label"] = "DJ set" },
			[43] = { ["object"] = "v_corp_servercln", ["price"] = 1000, ["label"] = "Serverrack" },
			[44] = { ["object"] = "prop_gold_trolly_full", ["price"] = 1000, ["label"] = "Trolly met goldbars" },
			[45] = { ["object"] = "bkr_prop_bkr_cash_scatter_01", ["price"] = 100, ["label"] = "Los geld" },
			[46] = { ["object"] = "bkr_prop_bkr_cashpile_01", ["price"] = 100, ["label"] = "Stapels geld" },
			[47] = { ["object"] = "bkr_prop_bkr_cash_roll_01", ["price"] = 100, ["label"] = "Rolletjes geld" },
			[48] = { ["object"] = "bkr_prop_money_counter", ["price"] = 1000, ["label"] = "Geldtelmachine" },
			[49] = { ["object"] = "ng_proc_paper_news_globe", ["price"] = 1000, ["label"] = "Krant 1" },
			[50] = { ["object"] = "ng_proc_paper_news_rag", ["price"] = 100, ["label"] = "Krant 2" },
			[51] = { ["object"] = "gr_prop_gr_target_02b", ["price"] = 500, ["label"] = "Schiettarget persoon" },
			[52] = { ["object"] = "prop_gnome1", ["price"] = 500, ["label"] = "Kabouter vissen" },
			[53] = { ["object"] = "prop_gnome2", ["price"] = 500, ["label"] = "Kabouter vuilnis" },
			[54] = { ["object"] = "prop_gnome3", ["price"] = 500, ["label"] = "Kabouter broek" }
		},
	},
	["general4"] = {
		label = "Random 2",
		items = {
			[1] = { ["object"] = "prop_dummy_01", ["price"] = 100, ["label"] = "Dummy" },
			[2] = { ["object"] = "prop_egg_clock_01", ["price"] = 100, ["label"] = "Ei Clock" },
			[3] = { ["object"] = "prop_feed_sack_01", ["price"] = 100, ["label"] = "Zak met eten" },
			[4] = { ["object"] = "prop_floor_duster_01", ["price"] = 100, ["label"] = "Bezem 1" },
			[5] = { ["object"] = "prop_f_duster_02", ["price"] = 100, ["label"] = "Bezem 2" },
			[6] = { ["object"] = "prop_fruit_basket", ["price"] = 100, ["label"] = "Fruit mandje" },
			[7] = { ["object"] = "prop_grapes_02", ["price"] = 100, ["label"] = "Fruit voor in het mandje" },
			[8] = { ["object"] = "prop_idol_case_01", ["price"] = 100, ["label"] = "Houten mandje" },
			[9] = { ["object"] = "prop_jewel_02a", ["price"] = 100, ["label"] = "Juwelen 1" },
			[10] = { ["object"] = "prop_jewel_02b", ["price"] = 100, ["label"] = "Juwelen 2" },
			[11] = { ["object"] = "prop_jewel_02c", ["price"] = 100, ["label"] = "Juwelen 3" },
			[12] = { ["object"] = "prop_jewel_03a", ["price"] = 100, ["label"] = "Juwelen 4" },
			[13] = { ["object"] = "prop_jewel_03b", ["price"] = 100, ["label"] = "Juwelen 5" },
			[14] = { ["object"] = "prop_jewel_04a", ["price"] = 100, ["label"] = "Juwelen 6" },
			[15] = { ["object"] = "prop_jewel_04b", ["price"] = 100, ["label"] = "Juwelen 7" },
			[16] = { ["object"] = "p_watch_01", ["price"] = 100, ["label"] = "Horloge 1" },
			[17] = { ["object"] = "p_watch_02", ["price"] = 100, ["label"] = "Horloge 2" },
			[18] = { ["object"] = "p_watch_03", ["price"] = 100, ["label"] = "Horloge 3" },
			[19] = { ["object"] = "p_watch_04", ["price"] = 100, ["label"] = "Horloge 4" },
			[20] = { ["object"] = "p_watch_05", ["price"] = 100, ["label"] = "Horloge 5" },
			[21] = { ["object"] = "p_watch_06", ["price"] = 100, ["label"] = "Horloge 6" },
			[22] = { ["object"] = "prop_j_disptray_01", ["price"] = 100, ["label"] = "Juwelen tray 1" },
			[23] = { ["object"] = "prop_j_disptray_01b", ["price"] = 100, ["label"] = "Juwelen tray 2" },
			[24] = { ["object"] = "prop_j_disptray_02", ["price"] = 100, ["label"] = "Juwelen tray 3" },
			[25] = { ["object"] = "prop_j_disptray_03", ["price"] = 100, ["label"] = "Juwelen tray 4" },
			[26] = { ["object"] = "prop_j_disptray_04", ["price"] = 100, ["label"] = "Juwelen tray 5" },
			[27] = { ["object"] = "prop_j_disptray_04b", ["price"] = 100, ["label"] = "Juwelen tray 6" },
			[28] = { ["object"] = "prop_j_disptray_05", ["price"] = 100, ["label"] = "Juwelen tray 7" },
			[29] = { ["object"] = "prop_j_disptray_05b", ["price"] = 100, ["label"] = "Juwelen tray 8" },
			[30] = { ["object"] = "prop_ld_greenscreen_01", ["price"] = 100, ["label"] = "Green Screen" },
			[31] = { ["object"] = "prop_ld_jerrycan_01", ["price"] = 100, ["label"] = "Jerry Can" },
			[32] = { ["object"] = "prop_ld_keypad_01", ["price"] = 100, ["label"] = "Keypad 1" },
			[33] = { ["object"] = "prop_ld_keypad_01b", ["price"] = 100, ["label"] = "Keypad 2" },
			[34] = { ["object"] = "v_corp_bk_secpanel", ["price"] = 1000, ["label"] = "Keypad 3" },
			[35] = { ["object"] = "prop_ld_suitcase_01", ["price"] = 100, ["label"] = "Koffer 1" },
			[36] = { ["object"] = "prop_ld_suitcase_02", ["price"] = 100, ["label"] = "Koffer 2" },
			[37] = { ["object"] = "hei_p_attache_case_shut", ["price"] = 100, ["label"] = "Koffer 3"},
			[38] = { ["object"] = "prop_mr_rasberryclean", ["price"] = 100, ["label"] = "Teddybeer" },
			[39] = { ["object"] = "prop_shopping_bags01", ["price"] = 100, ["label"] = "Winkel tasjes 1" },
			[40] = { ["object"] = "prop_shopping_bags02", ["price"] = 100, ["label"] = "Winkel tasjes 1" },
			[41] = { ["object"] = "p_ld_sax", ["price"] = 100, ["label"] = "Sax" },
			[42] = { ["object"] = "p_ld_soc_ball_01", ["price"] = 100, ["label"] = "Voetbal" },
			[43] = { ["object"] = "bkr_prop_fakeid_boxdriverl_01a", ["price"] = 500, ["label"] = "Doos neppe rijbewijzen" },
			[44] = { ["object"] = "bkr_prop_fakeid_boxpassport_01a", ["price"] = 500, ["label"] = "Doos neppe ID-kaarten" },
			[45] = { ["object"] = "prop_table_tennis", ["price"] = 500, ["label"] = "Tafeltennnis" },
			[46] = { ["object"] = "prop_table_ten_bat", ["price"] = 500, ["label"] = "Tafeltennis bat" }
		},
	},
	["small"] = {
		label = "Details",
		items = {
			[1] = { ["object"] = "v_res_r_figcat", ["price"] = 300, ["label"] = "Beeldje Cat" },
			[2] = { ["object"] = "v_res_r_figclown", ["price"] = 300, ["label"] = "Beeldje Clown" },
			[3] = { ["object"] = "v_res_r_figauth2", ["price"] = 300, ["label"] = "Beeldje Auth" },
			[4] = { ["object"] = "v_res_r_figfemale", ["price"] = 300, ["label"] = "Beeldje Female" },
			[5] = { ["object"] = "v_res_r_figflamenco", ["price"] = 300, ["label"] = "Beeldje Flamenco" },
			[6] = { ["object"] = "v_res_r_figgirl", ["price"] = 300, ["label"] = "Beeldje vrouw" },
			[7] = { ["object"] = "v_res_r_figgirlclown", ["price"] = 300, ["label"] = "Beeldje vrouwelijke Clown" },
			[8] = { ["object"] = "v_res_r_figoblisk", ["price"] = 300, ["label"] = "Beeldje Oblisk" },
			[9] = { ["object"] = "v_res_r_figpillar", ["price"] = 300, ["label"] = "Beeldje Pillar" },
			[10] = { ["object"] = "v_res_r_teapot", ["price"] = 300, ["label"] = "Theepot" },
			[11] = { ["object"] = "v_res_sculpt_dec", ["price"] = 300, ["label"] = "Beeldje 1" },
			[12] = { ["object"] = "v_res_sculpt_decd", ["price"] = 300, ["label"] = "Beeldje 2" },
			[13] = { ["object"] = "v_res_sculpt_dece", ["price"] = 300, ["label"] = "Beeldje 3" },
			[14] = { ["object"] = "v_res_sculpt_decf", ["price"] = 300, ["label"] = "Beeldje 4" },
			[15] = { ["object"] = "v_res_skateboard", ["price"] = 300, ["label"] = "Skateboard" },
			[16] = { ["object"] = "v_res_sketchpad", ["price"] = 300, ["label"] = "Tekenblok" },
			[17] = { ["object"] = "v_res_tissues", ["price"] = 300, ["label"] = "Tissues" },
			[18] = { ["object"] = "v_res_tre_basketmess", ["price"] = 300, ["label"] = "Mandje van tichelaar" },
			[19] = { ["object"] = "v_res_tre_bin", ["price"] = 300, ["label"] = "Vuilnisbakje" },
			[20] = { ["object"] = "v_res_tre_fruitbowl", ["price"] = 300, ["label"] = "Mandje met enveloppen" },
			[21] = { ["object"] = "prop_idol_01", ["price"] = 100, ["label"] = "Beeldje goud" },
			[22] = { ["object"] = "v_res_r_fighorsestnd", ["price"] = 300, ["label"] = "Beeldje zwart paard" },
			[23] = { ["object"] = "v_res_r_fighorse", ["price"] = 300, ["label"] = "Beeldje groot paard" },
			[24] = { ["object"] = "v_res_r_figdancer", ["price"] = 300, ["label"] = "Beeldje danseres" },
			[25] = { ["object"] = "v_res_fa_idol02", ["price"] = 300, ["label"] = "Olifanten beeldje" },
			[26] = { ["object"] = "v_res_m_statue", ["price"] = 300, ["label"] = "Beeldhouwwerk" },
			[27] = { ["object"] = "v_20_ornaeagle", ["price"] = 300, ["label"] = "Beeldje adelaar" },
			[28] = { ["object"] = "v_med_p_vaseround", ["price"] = 300, ["label"] = "Vaas rond" },
			[29] = { ["object"] = "ex_mp_h_acc_vase_05", ["price"] = 300, ["label"] = "Vaas paars" },
			[30] = { ["object"] = "apa_mp_h_acc_dec_head_01", ["price"] = 300, ["label"] = "kunstwerk" },
			[31] = { ["object"] = "apa_mp_h_acc_dec_sculpt_02", ["price"] = 300, ["label"] = "kunstwerk 2" },
			[32] = { ["object"] = "ex_mp_h_acc_dec_plate_02", ["price"] = 300, ["label"] = "kunstwerk 3" },
			[33] = { ["object"] = "apa_mp_h_acc_bowl_ceramic_01", ["price"] = 300, ["label"] = "schaal" },
			[34] = { ["object"] = "apa_mp_h_acc_bottle_01", ["price"] = 300, ["label"] = "Deco flesje" },
			[35] = { ["object"] = "apa_mp_h_acc_bottle_02", ["price"] = 300, ["label"] = "Deco flesje" },
			[36] = { ["object"] = "apa_mp_h_acc_drink_tray_02", ["price"] = 300, ["label"] = "Thee setje" },
			[37] = { ["object"] = "prop_rub_tyre_03", ["price"] = 300, ["label"] = "Autoband breed" },
			[38] = { ["object"] = "prop_rub_tyre_01", ["price"] = 300, ["label"] = "Autoband small" },
			[39] = { ["object"] = "frag_plank_a", ["price"] = 300, ["label"] = "Houten plank 1" },
			[40] = { ["object"] = "frag_plank_b", ["price"] = 300, ["label"] = "Houten plank 2" },
			[41] = { ["object"] = "frag_plank_d", ["price"] = 300, ["label"] = "Houten plank 3" },
			[42] = { ["object"] = "frag_plank_e", ["price"] = 300, ["label"] = "Houten plank 4" },
			[43] = { ["object"] = "prop_metal_plates01", ["price"] = 300, ["label"] = "Metaal plaat" },
			[44] = { ["object"] = "prop_big_clock_01", ["price"] = 500, ["label"] = "Klok groot" },
			[45] = { ["object"] = "prop_id2_20_clock", ["price"] = 500, ["label"] = "Klok zonder plaat" }
		},
	},
	["storage"] = {
		label = "Opslag",
		items = {
			[1] = { ["object"] = "v_res_cabinet", ["price"] = 2500, ["label"] = "Cabinet Large" },
			[2] = { ["object"] = "v_res_d_dressingtable", ["price"] = 2500, ["label"] = "Dressing Table" },
			[3] = { ["object"] = "v_res_d_sideunit", ["price"] = 2500, ["label"] = "Side Unit" },
			[4] = { ["object"] = "v_res_fh_sidebrddine", ["price"] = 2500, ["label"] = "Side Unit" },
			[5] = { ["object"] = "v_res_fh_sidebrdlngb", ["price"] = 2500, ["label"] = "Side Unit" },
			[6] = { ["object"] = "v_res_mbbedtable", ["price"] = 2500, ["label"] = "Bed Unit" },
			[7] = { ["object"] = "v_res_j_tvstand", ["price"] = 2500, ["label"] = "Tv Unit" },
			[8] = { ["object"] = "v_res_mbdresser", ["price"] = 2500, ["label"] = "Dresser Unit" },
			[9] = { ["object"] = "v_res_mbottoman", ["price"] = 2500, ["label"] = "Bottoman Unit" },
			[10] = { ["object"] = "v_res_mconsolemod", ["price"] = 2500, ["label"] = "Console Unit" },
			[11] = { ["object"] = "v_res_mcupboard", ["price"] = 2500, ["label"] = "Cupboard Unit" },
			[12] = { ["object"] = "v_res_mdchest", ["price"] = 2500, ["label"] = "Chest Unit" },
			[13] = { ["object"] = "v_res_msoncabinet", ["price"] = 2500, ["label"] = "Mason Unit" },
			[14] = { ["object"] = "v_res_m_armoire", ["price"] = 2500, ["label"] = "Armoire Unit" },
			[15] = { ["object"] = "v_res_m_sidetable", ["price"] = 2500, ["label"] = "Side Unit" },
			[16] = { ["object"] = "v_res_tre_bedsidetable", ["price"] = 2500, ["label"] = "Side Unit" },
			[17] = { ["object"] = "v_res_tre_bedsidetableb", ["price"] = 2500, ["label"] = "Side Unit 2" },
			[18] = { ["object"] = "v_res_tre_smallbookshelf", ["price"] = 2500, ["label"] = "Book Unit" },
			[19] = { ["object"] = "v_res_tre_storagebox", ["price"] = 2500, ["label"] = "Box Unit" },
			[20] = { ["object"] = "v_res_tre_storageunit", ["price"] = 2500, ["label"] = "Storage Unit" },
			[21] = { ["object"] = "v_res_tre_wardrobe", ["price"] = 2500, ["label"] = "Wardrobe Unit" },
			[22] = { ["object"] = "v_res_tre_wdunitscuz", ["price"] = 2500, ["label"] = "Wood Unit" },
			[23] = { ["object"] = "prop_devin_box_closed", ["price"] = 100, ["label"] = "Bean Bag 1" },
			[24] = { ["object"] = "prop_mil_crate_01", ["price"] = 100, ["label"] = "Mil Crate 1" },
			[25] = { ["object"] = "prop_mil_crate_02", ["price"] = 100, ["label"] = "Mil Crate 2" },
			[26] = { ["object"] = "prop_ld_int_safe_01", ["price"] = 1100, ["label"] = "Safe" },
			[27] = { ["object"] = "prop_toolchest_05", ["price"] = 5000, ["label"] = "Crafting Bench" },
			[28] = { ["object"] = "v_corp_filecablow", ["price"] = 500, ["label"] = "archiefkast laag" },
			[29] = { ["object"] = "v_corp_filecabtall", ["price"] = 500, ["label"] = "archiefkast hoog" },
			[30] = { ["object"] = "apa_mp_h_str_shelffloorm_02", ["price"] = 500, ["label"] = "grote moderne kast" },
			[31] = { ["object"] = "prop_coathook_01", ["price"] = 100, ["label"] = "kapstokje" },
			[32] = { ["object"] = "v_corp_lowcabdark01", ["price"] = 500, ["label"] = "archiefkast laag zwart" },
			[33] = { ["object"] = "v_corp_tallcabdark01", ["price"] = 500, ["label"] = "archiefkast hoog zwart" },
			[34] = { ["object"] = "v_corp_cabshelves01", ["price"] = 1000, ["label"] = "archiefkast zwart" },
			[35] = { ["object"] = "v_corp_offshelf", ["price"] = 1000, ["label"] = "archiefkast groot" },
			[36] = { ["object"] = "apa_mp_h_str_sideboardl_06", ["price"] = 750, ["label"] = "kastje modern" },
			[37] = { ["object"] = "apa_mp_h_str_sideboardl_09", ["price"] = 750, ["label"] = "kastje modern 2" },
			[38] = { ["object"] = "apa_mp_h_str_shelfwallm_01", ["price"] = 750, ["label"] = "boekenkast 2" },
			[39] = { ["object"] = "apa_mp_h_str_sideboardl_11", ["price"] = 750, ["label"] = "kastje modern 3" },
			[40] = { ["object"] = "prop_box_wood02a_pu", ["price"] = 100, ["label"] = "Military Crate" },
			[41] = { ["object"] = "prop_mb_cargo_02a", ["price"] = 100, ["label"] = "Supply crate" },
			[42] = { ["object"] = "imp_prop_impexp_rack_01a", ["price"] = 100, ["label"] = "Rack met spullen 1" },
			[43] = { ["object"] = "imp_prop_impexp_rack_02a", ["price"] = 100, ["label"] = "Rack met spullen 2" },
			[44] = { ["object"] = "imp_prop_impexp_rack_03a", ["price"] = 100, ["label"] = "Rack met spullen 3" },
			[45] = { ["object"] = "imp_prop_impexp_rack_04a", ["price"] = 100, ["label"] = "Rack met spullen 4" },
			[46] = { ["object"] = "prop_rub_cage01b", ["price"] = 100, ["label"] = "Karretje met dozen" },
			[47] = { ["object"] = "v_res_mddresser", ["price"] = 300, ["label"] = "Dresser" },
			[48] = { ["object"] = "v_club_rack", ["price"] = 500, ["label"] = "kledingrek" },
			[49] = { ["object"] = "v_med_p_sideboard", ["price"] = 300, ["label"] = "Sideboard" },
			[50] = { ["object"] = "v_16_high_bed_mesh_unit", ["price"] = 300, ["label"] = "Kast met spullen" },
			[51] = { ["object"] = "mp_b_str_avunitl_01", ["price"] = 300, ["label"] = "Grote bruine kast" },
			[52] = { ["object"] = "ch_chint03_hacker", ["price"] = 300, ["label"] = "Bureau met beeldschermen 1" },
			[53] = { ["object"] = "xm_prop_base_staff_desk_01", ["price"] = 300, ["label"] = "Bureau met beeldschermen 2" },
			[54] = { ["object"] = "v_corp_deskseta", ["price"] = 300, ["label"] = "Bureau met beeldschermen 2" },
			[55] = { ["object"] = "bkr_prop_gunlocker_01a", ["price"] = 100, ["label"] = "Gunrack" },
			[56] = { ["object"] = "apa_mp_h_str_sideboardl_13", ["price"] = 750, ["label"] = "kastje modern 4" },
			[57] = { ["object"] = "apa_mp_h_str_sideboardl_14", ["price"] = 750, ["label"] = "kastje modern 5" },
			[58] = { ["object"] = "apa_mp_h_str_sideboardm_02", ["price"] = 750, ["label"] = "kastje modern 6" }
		},
	},
	["electronics"] = {
		label = "Elektonisch",
		items = {
			[1] = { ["object"] = "ba_prop_battle_club_computer_01", ["price"] = 300, ["label"] = "Computer met toetsenbord" },
			[2] = { ["object"] = "v_res_fh_speaker", ["price"] = 300, ["label"] = "Speaker" },
			[3] = { ["object"] = "v_res_fh_speakerdock", ["price"] = 300, ["label"] = "Speaker Dock" },
			[4] = { ["object"] = "v_res_fh_bedsideclock", ["price"] = 300, ["label"] = "Bedside Clock" },
			[5] = { ["object"] = "v_res_fa_phone", ["price"] = 300, ["label"] = "Phone" },
			[6] = { ["object"] = "v_res_fh_towerfan", ["price"] = 300, ["label"] = "Tower Fan" },
			[7] = { ["object"] = "v_res_fa_fan", ["price"] = 300, ["label"] = "Fan" },
			[8] = { ["object"] = "v_res_lest_bigscreen", ["price"] = 300, ["label"] = "Bigscreen" },
			[9] = { ["object"] = "v_res_lest_monitor", ["price"] = 300, ["label"] = "Monitor" },
			[10] = { ["object"] = "v_res_tre_mixer", ["price"] = 300, ["label"] = "Mixer" },
			[11] = { ["object"] = "prop_cs_cctv", ["price"] = 100, ["label"] = "CCTV" },
			[12] = { ["object"] = "prop_ld_lap_top", ["price"] = 100, ["label"] = "Laptop" },
			[13] = { ["object"] = "prop_ld_monitor_01", ["price"] = 100, ["label"] = "Monitor" },
			[14] = { ["object"] = "prop_speaker_05", ["price"] = 500, ["label"] = "Mounted speaker" },
			[15] = { ["object"] = "prop_tv_flat_03b", ["price"] = 1000, ["label"] = "Kleine flatscreen" },
			[16] = { ["object"] = "prop_laptop_01a", ["price"] = 750, ["label"] = "Opengeklapte laptop" },
			[17] = { ["object"] = "prop_tv_flat_michael", ["price"] = 3000, ["label"] = "Flatscreen hangend" },
			[18] = { ["object"] = "prop_dyn_pc", ["price"] = 1000, ["label"] = "PC" },
			[19] = { ["object"] = "prop_keyboard_01b", ["price"] = 100, ["label"] = "Toetsenbord" },
			[20] = { ["object"] = "prop_mouse_01b", ["price"] = 100, ["label"] = "Computermuis" },
			[21] = { ["object"] = "v_ret_gc_phone", ["price"] = 100, ["label"] = "Kantoor telefoon" },
			[22] = { ["object"] = "prop_tv_flat_01", ["price"] = 5000, ["label"] = "Grote flatscreen" },
			[23] = { ["object"] = "prop_arcade_01", ["price"] = 5000, ["label"] = "Arcade" },
			[24] = { ["object"] = "prop_console_01", ["price"] = 250, ["label"] = "Gameconsole" },
			[25] = { ["object"] = "v_res_tre_dvdplayer", ["price"] = 250, ["label"] = "Dvd speler" },
			[26] = { ["object"] = "prop_speaker_08", ["price"] = 500, ["label"] = "Houten speaker" },
			[27] = { ["object"] = "prop_cctv_mon_02", ["price"] = 300, ["label"] = "Cctv monitor" },
			[28] = { ["object"] = "prop_tv_flat_02", ["price"] = 2500, ["label"] = "Flatscreen staand" },
			[29] = { ["object"] = "prop_cctv_cam_01a", ["price"] = 300, ["label"] = "Cctv 2" },
			[30] = { ["object"] = "prop_dest_cctv_02", ["price"] = 300, ["label"] = "Cctv monitor 2" },
			[31] = { ["object"] = "prop_cctv_cam_07a", ["price"] = 300, ["label"] = "Cctv 3" },
			[32] = { ["object"] = "v_club_vu_deckcase", ["price"] = 1000, ["label"] = "DJ set" },
			[33] = { ["object"] = "v_corp_servercln", ["price"] = 1000, ["label"] = "serverrack" },
			[34] = { ["object"] = "prop_elecbox_18", ["price"] = 100, ["label"] = "Elektriciteitskast" },
			[35] = { ["object"] = "ba_prop_battle_club_speaker_small", ["price"] = 500, ["label"] = "kleine box" },
			[36] = { ["object"] = "ba_prop_battle_club_speaker_med", ["price"] = 750, ["label"] = "box" },
			[37] = { ["object"] = "ba_prop_battle_club_speaker_large", ["price"] = 1000, ["label"] = "grote box" },
			[38] = { ["object"] = "v_res_pcspeaker", ["price"] = 300, ["label"] = "PC speaker" },
			[39] = { ["object"] = "v_res_pcwoofer", ["price"] = 300, ["label"] = "PC subwoofer" },
			[40] = { ["object"] = "bkr_prop_clubhouse_jukebox_02a", ["price"] = 1000, ["label"] = "Jukebox" },
			[41] = { ["object"] = "bkr_prop_clubhouse_jukebox_01b", ["price"] = 1000, ["label"] = "Jukebox 2" },
			[42] = { ["object"] = "ex_office_swag_electronic2", ["price"] = 1000, ["label"] = "Dozen electronica" },
			[43] = { ["object"] = "prop_rub_monitor", ["price"] = 1000, ["label"] = "Gebroken monitor" }
		},
	},
	["lighting"] = {
		label = "Lichten",
		items = {
			[1] = { ["object"] = "v_corp_cd_desklamp", ["price"] = 100, ["label"] = "Desk Corp Lamp" },
			[2] = { ["object"] = "v_res_desklamp", ["price"] = 100, ["label"] = "Desk Lamp" },
			[3] = { ["object"] = "v_res_d_lampa", ["price"] = 100, ["label"] = "Lamp AA" },
			[4] = { ["object"] = "v_res_fa_lamp1on", ["price"] = 100, ["label"] = "Lamp 1" },
			[5] = { ["object"] = "v_res_fh_floorlamp", ["price"] = 100, ["label"] = "Floor Lamp" },
			[6] = { ["object"] = "v_res_fh_lampa_on", ["price"] = 100, ["label"] = "Lamp 2" },
			[7] = { ["object"] = "v_res_j_tablelamp1", ["price"] = 100, ["label"] = "Table Lamp" },
			[8] = { ["object"] = "v_res_j_tablelamp2", ["price"] = 100, ["label"] = "Table Lamp 2" },
			[9] = { ["object"] = "v_res_mdbedlamp", ["price"] = 100, ["label"] = "Bed Lamp" },
			[10] = { ["object"] = "v_res_mplanttongue", ["price"] = 100, ["label"] = "Plant Tongue Lamp" },
			[11] = { ["object"] = "v_res_mtblelampmod", ["price"] = 100, ["label"] = "Table Lamp 3" },
			[12] = { ["object"] = "v_res_m_lampstand", ["price"] = 100, ["label"] = "Lamp Stand" },
			[13] = { ["object"] = "v_res_m_lampstand2", ["price"] = 100, ["label"] = "Lamp Stand 2" },
			[14] = { ["object"] = "v_res_m_lamptbl", ["price"] = 100, ["label"] = "Table Lamp 4" },
			[15] = { ["object"] = "v_res_tre_lightfan", ["price"] = 100, ["label"] = "Light Fan" },
			[16] = { ["object"] = "v_res_tre_talllamp", ["price"] = 100, ["label"] = "Tall Lamp" },
			[17] = { ["object"] = "v_ret_fh_walllighton", ["price"] = 100, ["label"] = "Wall Light" },
			[18] = { ["object"] = "v_ret_gc_lamp", ["price"] = 100, ["label"] = "GC Lamp" },
			[19] = { ["object"] = "prop_dummy_light", ["price"] = 100, ["label"] = "Flickering Light" },
			[20] = { ["object"] = "prop_ld_cont_light_01", ["price"] = 100, ["label"] = "Side Wall Light" },
			[21] = { ["object"] = "prop_wall_light_07a", ["price"] = 100, ["label"] = "Lantaarn" },
			[22] = { ["object"] = "prop_wall_light_01a", ["price"] = 100, ["label"] = "Skeere lamp" },
			[23] = { ["object"] = "v_serv_tu_light2_", ["price"] = 100, ["label"] = "Industrieel licht" },
			[24] = { ["object"] = "v_serv_tu_light3_", ["price"] = 100, ["label"] = "Industrieel licht2" },
			[25] = { ["object"] = "ba_prop_battle_lights_ceiling_l_a", ["price"] = 300, ["label"] = "Hanglamp" },
			[26] = { ["object"] = "v_med_p_floorlamp", ["price"] = 300, ["label"] = "Grote lamp" },
			[27] = { ["object"] = "v_club_vu_lamp", ["price"] = 100, ["label"] = "Kleine lamp" },
			[28] = { ["object"] = "ba_prop_battle_lights_wall_l_a", ["price"] = 100, ["label"] = "Muurlamp" },
			[29] = { ["object"] = "ba_prop_battle_lights_ceiling_l_c", ["price"] = 300, ["label"] = "Hanglamp 2" },
			[30] = { ["object"] = "ba_prop_battle_lights_ceiling_l_b", ["price"] = 300, ["label"] = "Kroonluchter 2" },
			[31] = { ["object"] = "ba_prop_battle_lights_wall_l_c", ["price"] = 100, ["label"] = "Muurlamp 2" },
			[32] = { ["object"] = "ba_prop_battle_lights_wall_l_b", ["price"] = 100, ["label"] = "Muurlamp 3" },
			[33] = { ["object"] = "hei_heist_lit_lightpendant_02", ["price"] = 300, ["label"] = "Hanglamp 3" },
			[34] = { ["object"] = "prop_oldlight_01b", ["price"] = 100, ["label"] = "Muurlamp 4" },
			[35] = { ["object"] = "v_ind_cflight02", ["price"] = 100, ["label"] = "Hanglamp " },
			[36] = { ["object"] = "v_ind_cflight", ["price"] = 100, ["label"] = "Hanglamp 2" },
			[37] = { ["object"] = "xm_prop_base_wall_lampa", ["price"] = 100, ["label"] = "Grote industrie lamp 1" },
			[38] = { ["object"] = "xm_prop_base_wall_lampb", ["price"] = 100, ["label"] = "Grote industrie lamp 1" },
			[39] = { ["object"] = "apa_mp_h_lit_floorlampnight_07", ["price"] = 100, ["label"] = "Blauwe lamp" },
			[40] = { ["object"] = "apa_mp_h_floorlamp_a", ["price"] = 100, ["label"] = "vloerlamp" },
			[41] = { ["object"] = "apa_mp_h_floorlamp_b", ["price"] = 100, ["label"] = "vloerlamp 2" },
			[42] = { ["object"] = "apa_mp_h_floorlamp_c", ["price"] = 100, ["label"] = "vloerlamp 3" },
			[43] = { ["object"] = "apa_mp_h_lit_floorlamp_03", ["price"] = 100, ["label"] = "vloerlamp 7" },
			[44] = { ["object"] = "apa_mp_h_lit_floorlamp_06", ["price"] = 100, ["label"] = "vloerlamp 8" },
			[45] = { ["object"] = "apa_mp_h_lit_floorlamp_10", ["price"] = 100, ["label"] = "vloerlamp 9" },
			[46] = { ["object"] = "apa_mp_h_lit_floorlamp_13", ["price"] = 100, ["label"] = "vloerlamp 10" },
			[47] = { ["object"] = "apa_mp_h_lit_floorlamp_17", ["price"] = 100, ["label"] = "vloerlamp 11" },
			[48] = { ["object"] = "apa_mp_h_lit_lamptablenight_16", ["price"] = 100, ["label"] = "nachtlampje" },
			[49] = { ["object"] = "apa_mp_h_lit_lamptablenight_24", ["price"] = 100, ["label"] = "nachtlampje 2" },
			[50] = { ["object"] = "apa_mp_h_lit_lamptable_005", ["price"] = 100, ["label"] = "nachtlampje 3" },
			[51] = { ["object"] = "apa_mp_h_lit_lamptable_04", ["price"] = 100, ["label"] = "nachtlampje 4" },
			[52] = { ["object"] = "apa_mp_h_lit_lamptable_09", ["price"] = 100, ["label"] = "nachtlampje 5" },
			[53] = { ["object"] = "apa_mp_h_lit_lamptable_14", ["price"] = 100, ["label"] = "nachtlampje 6" },
			[54] = { ["object"] = "apa_mp_h_lit_lamptable_17", ["price"] = 100, ["label"] = "nachtlampje 7" },
			[55] = { ["object"] = "apa_mp_h_yacht_table_lamp_01", ["price"] = 100, ["label"] = "nachtlampje 8" }
		},
	},
	["tables"] = {
		label = "Tafels",
		items = {
			[1] = { ["object"] = "v_res_d_coffeetable", ["price"] = 500, ["label"] = "Coffee tafel 1" },
			[2] = { ["object"] = "v_res_d_roundtable", ["price"] = 500, ["label"] = "Round tafel" },
			[3] = { ["object"] = "v_res_d_smallsidetable", ["price"] = 500, ["label"] = "Small Side tafel" },
			[4] = { ["object"] = "v_res_fh_coftablea", ["price"] = 500, ["label"] = "Tafel A" },
			[5] = { ["object"] = "v_res_fh_coftableb", ["price"] = 500, ["label"] = "Tafel B" },
			[6] = { ["object"] = "v_res_fh_coftbldisp", ["price"] = 500, ["label"] = "Tafel C" },
			[7] = { ["object"] = "v_res_fh_diningtable", ["price"] = 500, ["label"] = "Dining tafel" },
			[8] = { ["object"] = "v_res_j_coffeetable", ["price"] = 500, ["label"] = "Coffee tafel 2" },
			[9] = { ["object"] = "v_res_j_lowtable", ["price"] = 500, ["label"] = "Low tafel" },
			[10] = { ["object"] = "v_res_mdbedtable", ["price"] = 500, ["label"] = "Bed tafel" },
			[11] = { ["object"] = "v_res_mddesk", ["price"] = 500, ["label"] = "Desk" },
			[12] = { ["object"] = "v_res_msidetblemod", ["price"] = 500, ["label"] = "Side tafel" },
			[13] = { ["object"] = "v_res_m_console", ["price"] = 500, ["label"] = "Console tafel" },
			[14] = { ["object"] = "v_res_m_dinetble_replace", ["price"] = 500, ["label"] = "Dining tafel 2" },
			[15] = { ["object"] = "v_res_m_h_console", ["price"] = 500, ["label"] = "Console H tafel" },
			[16] = { ["object"] = "v_res_m_stool", ["price"] = 500, ["label"] = "Koffietafeltje" },
			[17] = { ["object"] = "v_res_tre_sideboard", ["price"] = 500, ["label"] = "Sideboard tafel" },
			[18] = { ["object"] = "v_res_tre_table2", ["price"] = 500, ["label"] = "Tafel 2" },
			[19] = { ["object"] = "v_res_tre_tvstand", ["price"] = 500, ["label"] = "Tv tafel" },
			[20] = { ["object"] = "v_res_tre_tvstand_tall", ["price"] = 500, ["label"] = "Tv tafel Tall" },
			[21] = { ["object"] = "v_med_p_coffeetable", ["price"] = 500, ["label"] = "Med Coffee tafel" },
			[22] = { ["object"] = "v_med_p_desk", ["price"] = 500, ["label"] = "Med Desk" },
			[23] = { ["object"] = "prop_yacht_table_01", ["price"] = 100, ["label"] = "Yacht tafel 1" },
			[24] = { ["object"] = "prop_yacht_table_02", ["price"] = 100, ["label"] = "Yacht tafel 2" },
			[25] = { ["object"] = "prop_yacht_table_03", ["price"] = 100, ["label"] = "Yacht tafel 3" },
			[26] = { ["object"] = "v_ret_csr_table", ["price"] = 100, ["label"] = "CSR tafel" },
			[27] = { ["object"] = "v_res_mconsoletrad", ["price"] = 250, ["label"] = "hoge bijzettafel" },
			[28] = { ["object"] = "v_ilev_liconftable_sml", ["price"] = 500, ["label"] = "vergadertafel" },
			[29] = { ["object"] = "v_ret_tablesml", ["price"] = 350, ["label"] = "bijzettafel marillaux" },
			[30] = { ["object"] = "apa_mp_h_yacht_coffee_table_02", ["price"] = 500, ["label"] = "koffietafel bruin" },
			[31] = { ["object"] = "apa_mp_h_yacht_side_table_01", ["price"] = 300, ["label"] = "bijzettafel bruin" },
			[32] = { ["object"] = "apa_mp_h_yacht_side_table_02", ["price"] = 300, ["label"] = "ronde bijzettafel" },
			[33] = { ["object"] = "apa_mp_h_tab_sidelrg_04", ["price"] = 300, ["label"] = "ronde bijzettafel 2" },
			[34] = { ["object"] = "v_club_vu_table", ["price"] = 300, ["label"] = "gedekte tafel" },
			[35] = { ["object"] = "apa_mp_h_tab_sidelrg_07", ["price"] = 500, ["label"] = "koffietafel glas" },
			[36] = { ["object"] = "bkr_prop_weed_table_01b", ["price"] = 100, ["label"] = "klaptafel" },
			[37] = { ["object"] = "ba_prop_int_trad_table", ["price"] = 300, ["label"] = "statafel" },
			[38] = { ["object"] = "apa_mp_h_str_sideboards_02", ["price"] = 750, ["label"] = "bijzettafel glas" },
			[39] = { ["object"] = "apa_mp_h_yacht_coffee_table_01", ["price"] = 750, ["label"] = "koffietafel modern" },
			[40] = { ["object"] = "apa_mp_h_din_table_04", ["price"] = 1000, ["label"] = "eettafel glas" },
			[41] = { ["object"] = "bkr_prop_coke_table01a", ["price"] = 1000, ["label"] = "Methproductie tafel" },
			[42] = { ["object"] = "gr_prop_gr_bench_03b", ["price"] = 1500, ["label"] = "Muurtafel met wapens" },
			[43] = { ["object"] = "gr_prop_gr_bench_04b", ["price"] = 1500, ["label"] = "Muurtafel met wapens 2" },
			[44] = { ["object"] = "gr_prop_gr_bench_01b", ["price"] = 1500, ["label"] = "Muurtafel met wapens 3" }
		},
	},
	["plants"] = {
		label = "Planten",
		items = {
			[1] = { ["object"] = "prop_fib_plant_01", ["price"] = 150, ["label"] = "Plant Fib" },
			[2] = { ["object"] = "v_corp_bombplant", ["price"] = 170, ["label"] = "Plant Bomb" },		
			[3] = { ["object"] = "v_res_mflowers", ["price"] = 170, ["label"] = "Plant bloemen" },	
			[4] = { ["object"] = "v_res_mvasechinese", ["price"] = 170, ["label"] = "Plant Chinese" },	
			[5] = { ["object"] = "v_res_m_bananaplant", ["price"] = 170, ["label"] = "Plant Banana" },	
			[6] = { ["object"] = "v_res_m_palmplant1", ["price"] = 170, ["label"] = "Plant Palm" },	
			[7] = { ["object"] = "v_res_m_palmstairs", ["price"] = 170, ["label"] = "Plant Palm 2" },	
			[8] = { ["object"] = "v_res_m_urn", ["price"] = 170, ["label"] = "Plant Urn" },	
			[9] = { ["object"] = "v_res_rubberplant", ["price"] = 170, ["label"] = "Plant Rubber" },	
			[10] = { ["object"] = "v_res_tre_plant", ["price"] = 170, ["label"] = "Plant" },	
			[11] = { ["object"] = "v_res_tre_tree", ["price"] = 170, ["label"] = "Plant Tree" },	
			[12] = { ["object"] = "v_med_p_planter", ["price"] = 170, ["label"] = "Planter" },	
			[13] = { ["object"] = "v_ret_flowers", ["price"] = 100, ["label"] = "Bloemen" },
			[14] = { ["object"] = "v_ret_j_flowerdisp", ["price"] = 100, ["label"] = "Bloemen 1" },
			[15] = { ["object"] = "v_ret_j_flowerdisp_white", ["price"] = 100, ["label"] = "Bloemen 2" },	
			[16] = { ["object"] = "v_res_m_vasefresh", ["price"] = 300, ["label"] = "Bloemenvaas" },
			[17] = { ["object"] = "v_res_rosevasedead", ["price"] = 300, ["label"] = "Rozenvaas 2" },
			[18] = { ["object"] = "v_res_exoticvase", ["price"] = 300, ["label"] = "Bloemenvaas 2" },
			[19] = { ["object"] = "v_res_rosevase", ["price"] = 300, ["label"] = "Rozenvaas" },
			[20] = { ["object"] = "prop_pot_plant_6a", ["price"] = 300, ["label"] = "Hangende plant" },
			[21] = { ["object"] = "prop_pot_plant_02a", ["price"] = 300, ["label"] = "Plantenpot" },
			[22] = { ["object"] = "v_res_fh_flowersa", ["price"] = 300, ["label"] = "Bloemen" },
			[23] = { ["object"] = "prop_pot_plant_01a", ["price"] = 300, ["label"] = "plantenpot 2" },
			[24] = { ["object"] = "prop_pot_plant_01b", ["price"] = 300, ["label"] = "plantenpot 3" },
			[25] = { ["object"] = "prop_pot_plant_01c", ["price"] = 300, ["label"] = "plantenpot 4" },
			[26] = { ["object"] = "prop_pot_plant_01d", ["price"] = 300, ["label"] = "plantenpot 5" },
			[27] = { ["object"] = "prop_pot_plant_01e", ["price"] = 300, ["label"] = "plantenpot 6" },
			[28] = { ["object"] = "prop_pot_plant_03b", ["price"] = 300, ["label"] = "plantenpot 7" },
			[29] = { ["object"] = "prop_pot_plant_05a", ["price"] = 300, ["label"] = "plantenpot 8" },
			[30] = { ["object"] = "prop_pot_plant_05b", ["price"] = 300, ["label"] = "plantenpot 9" },
			[31] = { ["object"] = "p_int_jewel_plant_01", ["price"] = 300, ["label"] = "plantenpot 10" },
			[32] = { ["object"] = "p_int_jewel_plant_02", ["price"] = 300, ["label"] = "plantenpot 11" },
			[33] = { ["object"] = "apa_mp_h_acc_vase_flowers_01", ["price"] = 300, ["label"] = "plantenpot 12" },
			[34] = { ["object"] = "apa_mp_h_acc_vase_flowers_02", ["price"] = 300, ["label"] = "plantenpot 13" },
			[35] = { ["object"] = "apa_mp_h_acc_vase_flowers_03", ["price"] = 300, ["label"] = "plantenpot 14" },
			[36] = { ["object"] = "apa_mp_h_acc_vase_flowers_04", ["price"] = 300, ["label"] = "plantenpot 15" },
			[37] = { ["object"] = "prop_plant_int_01a", ["price"] = 300, ["label"] = "plant" },
			[38] = { ["object"] = "prop_plant_int_01b", ["price"] = 300, ["label"] = "plant 2" },
			[39] = { ["object"] = "prop_plant_int_02a", ["price"] = 300, ["label"] = "plant 3" },
			[40] = { ["object"] = "prop_plant_int_02b", ["price"] = 300, ["label"] = "plant 4" },
			[41] = { ["object"] = "prop_plant_int_03a", ["price"] = 300, ["label"] = "plant 5" },
			[42] = { ["object"] = "prop_plant_int_03b", ["price"] = 300, ["label"] = "plant 6" },
			[43] = { ["object"] = "prop_plant_int_03c", ["price"] = 300, ["label"] = "plant 7" },
			[44] = { ["object"] = "prop_plant_int_04a", ["price"] = 300, ["label"] = "plant 8" },
			[45] = { ["object"] = "prop_plant_int_04c", ["price"] = 300, ["label"] = "plant 9" }
		},
	},
	["kitchen"] = {
		label = "Keuken",
		items = {
			[1] = { ["object"] = "prop_washer_01", ["price"] = 150, ["label"] = "Wasmachine 1" },
			[2] = { ["object"] = "prop_washer_02", ["price"] = 150, ["label"] = "Wasmachine 2" },
			[3] = { ["object"] = "prop_washer_03", ["price"] = 150, ["label"] = "Wasmachine 3" },
			[4] = { ["object"] = "prop_washing_basket_01", ["price"] = 150, ["label"] = "Wasmandje" },
			[5] = { ["object"] = "v_res_fridgemoda", ["price"] = 150, ["label"] = "Koelkast 1" },
			[6] = { ["object"] = "v_res_fridgemodsml", ["price"] = 150, ["label"] = "Koelkast 2" },
			[7] = { ["object"] = "prop_fridge_01", ["price"] = 150, ["label"] = "Koelkast 3" },
			[8] = { ["object"] = "prop_fridge_03", ["price"] = 150, ["label"] = "Koelkast 4" },
			[9] = { ["object"] = "v_ret_ml_fridge02", ["price"] = 100, ["label"] = "Koelkast 5" },
			[10] = { ["object"] = "prop_trailr_fridge", ["price"] = 300, ["label"] = "Koelkast 6" },
			[11] = { ["object"] = "prop_cooker_03", ["price"] = 150, ["label"] = "Fornuis 1" },
			[12] = { ["object"] = "v_res_ovenhobmod", ["price"] = 1000, ["label"] = "Fornuis 2" },
			[13] = { ["object"] = "prop_micro_01", ["price"] = 150, ["label"] = "Microwave 1" },
			[14] = { ["object"] = "prop_micro_02", ["price"] = 150, ["label"] = "Microwave 2" },
			[15] = { ["object"] = "prop_wok", ["price"] = 150, ["label"] = "Wok" },
			[16] = { ["object"] = "v_res_cakedome", ["price"] = 150, ["label"] = "Cake Plate" },
			[17] = { ["object"] = "v_res_fa_chopbrd", ["price"] = 150, ["label"] = "Chopping Board" },
			[18] = { ["object"] = "v_res_mutensils", ["price"] = 150, ["label"] = "Utensils" },
			[19] = { ["object"] = "v_res_pestle", ["price"] = 150, ["label"] = "Pestle" },
			[20] = { ["object"] = "v_ret_ta_paproll", ["price"] = 150, ["label"] = "PaperRoll 1" },
			[21] = { ["object"] = "v_ret_ta_paproll2", ["price"] = 150, ["label"] = "PaperRoll 2" },
			[22] = { ["object"] = "v_ret_fh_pot01", ["price"] = 150, ["label"] = "Pot 1" },
			[23] = { ["object"] = "v_ret_fh_pot02", ["price"] = 150, ["label"] = "Pot 2" },
			[24] = { ["object"] = "v_ret_fh_pot05", ["price"] = 150, ["label"] = "Pot 3" },
			[25] = { ["object"] = "prop_pot_03", ["price"] = 150, ["label"] = "Pot 4" },
			[26] = { ["object"] = "prop_pot_04", ["price"] = 150, ["label"] = "Pot 5" },
			[27] = { ["object"] = "prop_pot_05", ["price"] = 150, ["label"] = "Pot 6" },
			[28] = { ["object"] = "prop_pot_06", ["price"] = 150, ["label"] = "Pot 7" },
			[29] = { ["object"] = "prop_pot_rack", ["price"] = 150, ["label"] = "Pot Rack" },
			[30] = { ["object"] = "prop_kitch_juicer", ["price"] = 150, ["label"] = "Juicer" },
			[31] = { ["object"] = "v_res_mkniferack", ["price"] = 100, ["label"] = "messen" },
			[32] = { ["object"] = "v_res_mchopboard", ["price"] = 100, ["label"] = "snijplank" },
			[33] = { ["object"] = "prop_cs_kettle_01", ["price"] = 100, ["label"] = "Kettle" },
			[34] = { ["object"] = "v_res_tre_fridge", ["price"] = 500, ["label"] = "koelkast" },
			[35] = { ["object"] = "apa_mp_h_acc_coffeemachine_01", ["price"] = 500, ["label"] = "koffiezetapparaat" },
			[36] = { ["object"] = "prop_bar_fridge_03", ["price"] = 500, ["label"] = "Mini koelkast" }
		},
	},
	["bathroom"] = {
		label = "Badkamer",
		items = {
			[1] = { ["object"] = "prop_ld_toilet_01", ["price"] = 100, ["label"] = "Toilet 1" },
			[2] = { ["object"] = "prop_toilet_01", ["price"] = 100, ["label"] = "Toilet 2" },
			[3] = { ["object"] = "prop_toilet_02", ["price"] = 100, ["label"] = "Toilet 3" },
			[4] = { ["object"] = "prop_sink_02", ["price"] = 100, ["label"] = "Wastafel 1" },
			[5] = { ["object"] = "prop_sink_04", ["price"] = 100, ["label"] = "Wastafel 2" },
			[6] = { ["object"] = "prop_sink_05", ["price"] = 100, ["label"] = "Wastafel 3" },
			[7] = { ["object"] = "prop_sink_06", ["price"] = 100, ["label"] = "Wastafel 4" },
			[8] = { ["object"] = "prop_soap_disp_01", ["price"] = 100, ["label"] = "Zeep Dispenser" },
			[9] = { ["object"] = "prop_shower_rack_01", ["price"] = 100, ["label"] = "Douche Rack" },
			[10] = { ["object"] = "prop_handdry_01", ["price"] = 100, ["label"] = "Hand droger 1" },
			[11] = { ["object"] = "prop_handdry_02", ["price"] = 100, ["label"] = "Hand droger 2" },
			[12] = { ["object"] = "prop_towel_rail_01", ["price"] = 100, ["label"] = "Handdoek Rail 1" },
			[13] = { ["object"] = "prop_towel_rail_02", ["price"] = 100, ["label"] = "Handdoek Rail 2" },
			[14] = { ["object"] = "prop_towel_01", ["price"] = 100, ["label"] = "Handdoek 1" },
			[15] = { ["object"] = "v_res_mbtowel", ["price"] = 100, ["label"] = "Handdoek 2" },
			[16] = { ["object"] = "v_res_mbtowelfld", ["price"] = 100, ["label"] = "Handdoek 3" },
			[17] = { ["object"] = "v_ilev_mm_faucet", ["price"] = 100, ["label"] = "kraan" },
			[18] = { ["object"] = "v_res_tre_washbasket", ["price"] = 250, ["label"] = "wasmand" },
			[19] = { ["object"] = "prop_toilet_soap_02", ["price"] = 100, ["label"] = "bakje zeep" },
			[20] = { ["object"] = "prop_bar_sink_01", ["price"] = 100, ["label"] = "gootsteen" },
			[21] = { ["object"] = "v_res_mbath", ["price"] = 100, ["label"] = "Bad 1" },
			[22] = { ["object"] = "apa_mp_h_bathtub_01", ["price"] = 1000, ["label"] = "Bad 2" },
			[23] = { ["object"] = "bkr_prop_weed_bucket_open_01a", ["price"] = 100, ["label"] = "Emmer" }
		}
	},
	["medical"] = {
		label = "Medisch",
		items = {
			[1] = { ["object"] = "v_med_barrel", ["price"] = 750, ["label"] = "Barrel" },
			[2] = { ["object"] = "v_med_apecrate", ["price"] = 750, ["label"] = "Ape Crate" },
			[3] = { ["object"] = "v_med_apecratelrg", ["price"] = 750, ["label"] = "Ape Crate Large" },
			[4] = { ["object"] = "v_med_bed1", ["price"] = 750, ["label"] = "Bed 1" },
			[5] = { ["object"] = "v_med_bed2", ["price"] = 750, ["label"] = "Bed 2" },
			[6] = { ["object"] = "v_med_bedtable", ["price"] = 750, ["label"] = "Bed Table" },
			[7] = { ["object"] = "v_med_bench1", ["price"] = 750, ["label"] = "Bureau 1" },
			[8] = { ["object"] = "v_med_bench2", ["price"] = 750, ["label"] = "Bureau 2" },
			[9] = { ["object"] = "v_med_benchcentr", ["price"] = 750, ["label"] = "Bureau Center" },
			[10] = { ["object"] = "v_med_benchset1", ["price"] = 750, ["label"] = "Bureau Set" },
			[11] = { ["object"] = "v_med_bigtable", ["price"] = 750, ["label"] = "Grote tafel" },
			[12] = { ["object"] = "v_med_bin", ["price"] = 150, ["label"] = "Vuilnisbakje" },
			[13] = { ["object"] = "v_med_centrifuge1", ["price"] = 750, ["label"] = "Centrifuge" },
			[14] = { ["object"] = "v_med_cooler", ["price"] = 750, ["label"] = "Cooler" },
			[15] = { ["object"] = "v_med_cor_ceilingmonitor", ["price"] = 750, ["label"] = "Monitor" },
			[16] = { ["object"] = "v_med_cor_autopsytbl", ["price"] = 750, ["label"] = "Autopsy Table" },
			[17] = { ["object"] = "v_med_cor_cembin", ["price"] = 750, ["label"] = "Bin" },
			[18] = { ["object"] = "v_med_cor_cemtrolly2", ["price"] = 750, ["label"] = "Trolley" },
			[19] = { ["object"] = "v_med_cor_chemical", ["price"] = 750, ["label"] = "Chem" },
			[20] = { ["object"] = "v_med_cor_emblmtable", ["price"] = 750, ["label"] = "BLM Table" },
			[21] = { ["object"] = "v_med_cor_fileboxa", ["price"] = 750, ["label"] = "File Box" },
			[22] = { ["object"] = "v_med_cor_filingcab", ["price"] = 750, ["label"] = "File Cab" },
			[23] = { ["object"] = "v_med_cor_hose", ["price"] = 750, ["label"] = "Hose" },
			[24] = { ["object"] = "v_med_cor_largecupboard", ["price"] = 750, ["label"] = "Large Cupboard" },
			[25] = { ["object"] = "v_med_cor_lightbox", ["price"] = 750, ["label"] = "Lightbox" },
			[26] = { ["object"] = "v_med_cor_medstool", ["price"] = 750, ["label"] = "Medstool" },
			[27] = { ["object"] = "v_med_cor_minifridge", ["price"] = 750, ["label"] = "Minifridge" },
			[28] = { ["object"] = "v_med_cor_papertowels", ["price"] = 750, ["label"] = "Papertowels" },
			[29] = { ["object"] = "v_med_cor_photocopy", ["price"] = 750, ["label"] = "Photocopy" },
			[30] = { ["object"] = "v_med_cor_tvstand", ["price"] = 750, ["label"] = "TV Stand" },
			[31] = { ["object"] = "v_med_cor_wallunita", ["price"] = 750, ["label"] = "Wall Unit" },
			[32] = { ["object"] = "v_med_examlight", ["price"] = 750, ["label"] = "Exam light" },
			[33] = { ["object"] = "v_med_gastank", ["price"] = 750, ["label"] = "Gas Tank" },
			[34] = { ["object"] = "v_med_hazmatscan", ["price"] = 750, ["label"] = "Hazmat Scan" },
			[35] = { ["object"] = "v_med_hospheadwall1", ["price"] = 750, ["label"] = "Head Wall" },
			[36] = { ["object"] = "v_med_hospseating1", ["price"] = 750, ["label"] = "Seating" },
			[37] = { ["object"] = "v_med_hosptable", ["price"] = 750, ["label"] = "Hosp Table" },
			[38] = { ["object"] = "v_med_latexgloveboxblue", ["price"] = 50, ["label"] = "Glove Box" },
			[39] = { ["object"] = "v_med_medwastebin", ["price"] = 750, ["label"] = "Wastebin" },
			[40] = { ["object"] = "v_med_oscillator3", ["price"] = 750, ["label"] = "Oscillator" },
			[41] = { ["object"] = "v_ret_hd_unit1_", ["price"] = 100, ["label"] = "HD Unit 1" },
			[42] = { ["object"] = "v_ret_hd_unit2_", ["price"] = 100, ["label"] = "HD Unit 2" },
			[43] = { ["object"] = "v_ret_ta_firstaid", ["price"] = 100, ["label"] = "First Aid" },
			[44] = { ["object"] = "prop_bonesaw", ["price"] = 100, ["label"] = "Bonesaw" },
			[45] = { ["object"] = "prop_ld_health_pack", ["price"] = 100, ["label"] = "Health Pack" }
		},
	},
	["walldecoration"] = {
		label = "Muur Deco",
		items = {
			[1] = { ["object"] = "apa_p_h_acc_artwalll_02", ["price"] = 1000, ["label"] = "schilderij met vlakken" },
			[2] = { ["object"] = "v_ind_cs_toolboard", ["price"] = 500, ["label"] = "gereedschap" },
			[3] = { ["object"] = "ex_office_swag_paintings03", ["price"] = 1000, ["label"] = "schilderijen grond" },
			[4] = { ["object"] = "ex_mp_h_acc_artwallm_03", ["price"] = 750, ["label"] = "abstract schilderij" },
			[5] = { ["object"] = "ex_p_h_acc_artwallm_04", ["price"] = 750, ["label"] = "abstract schilderij 2" },
			[6] = { ["object"] = "ex_p_h_acc_artwalll_01", ["price"] = 1250, ["label"] = "abstract schilderij groot" },
			[7] = { ["object"] = "apa_p_h_acc_artwalll_03", ["price"] = 750, ["label"] = "abstract schilderij 3" },
			[8] = { ["object"] = "ex_mp_h_acc_artwallm_02", ["price"] = 750, ["label"] = "abstract schilderij 4" },
			[9] = { ["object"] = "ex_p_h_acc_artwallm_03", ["price"] = 750, ["label"] = "abstract schilderij 5" },
			[10] = { ["object"] = "apa_mp_h_acc_artwallm_02", ["price"] = 750, ["label"] = "abstract schilderij 6" },
			[11] = { ["object"] = "apa_mp_h_acc_artwalll_02", ["price"] = 750, ["label"] = "abstract schilderij 7" },
			[12] = { ["object"] = "apa_mp_h_acc_artwallm_04", ["price"] = 750, ["label"] = "abstract schilderij 8" },
			[13] = { ["object"] = "prop_dart_bd_cab_01", ["price"] = 250, ["label"] = "dartbord" },
			[14] = { ["object"] = "prop_dart_bd_01", ["price"] = 250, ["label"] = "dartbord 2" },
			[15] = { ["object"] = "hei_heist_acc_artgolddisc_03", ["price"] = 250, ["label"] = "Goude plaat" },
			[16] = { ["object"] = "prop_target_comp_wood", ["price"] = 250, ["label"] = "Target aan muur" },
			[17] = { ["object"] = "apa_p_h_acc_artwallm_01", ["price"] = 250, ["label"] = "3d blokken art" },
			[18] = { ["object"] = "apa_p_h_acc_artwalls_03", ["price"] = 250, ["label"] = "American football" },
			[19] = { ["object"] = "hei_prop_heist_pic_01", ["price"] = 250, ["label"] = " Heist foto chauffeur" },
			[20] = { ["object"] = "hei_prop_heist_pic_02", ["price"] = 250, ["label"] = "Heist foto crimineel" },
			[21] = { ["object"] = "hei_prop_heist_pic_03", ["price"] = 250, ["label"] = "Heist foto man" },
			[22] = { ["object"] = "hei_prop_heist_pic_04", ["price"] = 250, ["label"] = "Heist foto postbus" },
			[23] = { ["object"] = "hei_prop_heist_pic_05", ["price"] = 250, ["label"] = "Heist foto helikopter" },
			[24] = { ["object"] = "hei_prop_heist_pic_06", ["price"] = 250, ["label"] = "Heist foto airplane" },
			[25] = { ["object"] = "hei_prop_heist_pic_07", ["price"] = 250, ["label"] = "Heist foto passaggiersbus" },
			[26] = { ["object"] = "hei_prop_heist_pic_08", ["price"] = 250, ["label"] = "Heist foto legerauto" },
			[27] = { ["object"] = "hei_prop_heist_pic_09", ["price"] = 250, ["label"] = "Heist foto Bank" },
			[28] = { ["object"] = "hei_prop_heist_pic_10", ["price"] = 250, ["label"] = "Heist foto Lab" },
			[29] = { ["object"] = "hei_prop_heist_pic_11", ["price"] = 250, ["label"] = "Heist foto vrouw" },
			[30] = { ["object"] = "hei_prop_heist_pic_12", ["price"] = 250, ["label"] = "Heist foto bati" },
			[31] = { ["object"] = "v_ilev_trev_pictureframe", ["price"] = 250, ["label"] = "Fotolijst vrouw" },
			[32] = { ["object"] = "v_ilev_trev_pictureframebroken", ["price"] = 250, ["label"] = "Fotolijst vrouw gebroken" },
			[33] = { ["object"] = "ex_office_swag_paintings01", ["price"] = 250, ["label"] = "Potretten muur decoratie" },
		},
	},
}