Config = Config or {}

Config.Products = {
    ['Shops'] = {
        [1] = {
          name = "water_bottle",
          price = 2,
          amount = 100,
          info = {},
          type = "item",
          slot = 1,
        },
        [2] = {
          name = "kurkakola",
          price = 3,
          amount = 100,
          info = {},
          type = "item",
          slot = 2,
        },
        [3] = {
          name = "sprunk",
          price = 3,
          amount = 100,
          info = {},
          type = "item",
          slot = 3,
        },
        [4] = {
          name = "sandwich",
          price = 3,
          amount = 100,
          info = {},
          type = "item",
          slot = 4,
        },
        [5] = {
          name = "chocolade",
          price = 5,
          amount = 100,
          info = {},
          type = "item",
          slot = 5,
        },
        [6] = {
          name = "donut",
          price = 4,
          amount = 100,
          info = {},
          type = "item",
          slot = 6,
        },
        [7] = {
          name = "chips",
          price = 5,
          amount = 100,
          info = {},
          type = "item",
          slot = 7,
        },
        [8] = {
          name = "macncheese",
          price = 7,
          amount = 100,
          info = {},
          type = "item",
          slot = 8,
        },
        [9] = {
          name = "bandage",
          price = 15,
          amount = 100,
          info = {},
          type = "item",
          slot = 9,
        },
        [10] = {
          name = "apple",
          price = 4,
          amount = 100,
          info = {},
          type = "item",
          slot = 10,
        },
        [11] = {
          name = "banana",
          price = 4,
          amount = 100,
          info = {},
          type = "item",
          slot = 11,
        },
        [12] = {
          name = "rose",
          price = 25,
          amount = 10,
          info = {},
          type = "item",
          slot = 12,
        },
        [13] = {
          name = "umbrella",
          price = 5,
          amount = 10,
          info = {},
          type = "item",
          slot = 13,
        },
        [14] = {
          name = "hairtie",
          price = 25,
          amount = 10,
          info = {},
          type = "item",
          slot = 14,
        },
        [15] = {
          name = "lotto-card",
          price = 500,
          amount = 10,
          info = {},
          type = "item",
          slot = 15,
        },
    },
    ['BShops'] = {
        [1] = {
          name = "water_bottle",
          price = 2,
          amount = 100,
          info = {},
          type = "item",
          slot = 1,
        },
        [2] = {
          name = "kurkakola",
          price = 3,
          amount = 100,
          info = {},
          type = "item",
          slot = 2,
        },
        [3] = {
          name = "sprunk",
          price = 3,
          amount = 100,
          info = {},
          type = "item",
          slot = 3,
        },
        [4] = {
          name = "sandwich",
          price = 3,
          amount = 100,
          info = {},
          type = "item",
          slot = 4,
        },
        [5] = {
          name = "chocolade",
          price = 5,
          amount = 100,
          info = {},
          type = "item",
          slot = 5,
        },
        [6] = {
          name = "donut",
          price = 4,
          amount = 100,
          info = {},
          type = "item",
          slot = 6,
        },
        [7] = {
          name = "bandage",
          price = 15,
          amount = 100,
          info = {},
          type = "item",
          slot = 7,
        },
        [8] = {
          name = "apple",
          price = 4,
          amount = 100,
          info = {},
          type = "item",
          slot = 8,
        },
        [9] = {
          name = "banana",
          price = 4,
          amount = 100,
          info = {},
          type = "item",
          slot = 9,
        },
        [10] = {
          name = "rose",
          price = 25,
          amount = 10,
          info = {},
          type = "item",
          slot = 10,
        },
        [11] = {
          name = "umbrella",
          price = 5,
          amount = 10,
          info = {},
          type = "item",
          slot = 11,
        },
        [12] = {
          name = "hairtie",
          price = 25,
          amount = 10,
          info = {},
          type = "item",
          slot = 12,
        },
        [13] = {
          name = "lotto-card",
          price = 500,
          amount = 10,
          info = {},
          type = "item",
          slot = 13,
        },
        [14] = {
          name = "burger-bun",
          price = 10,
          amount = 100,
          info = {},
          type = "item",
          slot = 14,
        },
        [15] = {
          name = "burger-raw",
          price = 10,
          amount = 100,
          info = {},
          type = "item",
          slot = 15,
        },
        [16] = {
          name = "burger-lettuce",
          price = 10,
          amount = 100,
          info = {},
          type = "item",
          slot = 16,
        },
        [17] = {
          name = "burger-potato",
          price = 10,
          amount = 100,
          info = {},
          type = "item",
          slot = 17,
        },
    },	
    ['SShops'] = {
        [1] = {
          name = "water_bottle",
          price = 2,
          amount = 100,
          info = {},
          type = "item",
          slot = 1,
        },
        [2] = {
          name = "kurkakola",
          price = 3,
          amount = 100,
          info = {},
          type = "item",
          slot = 2,
        },
        [3] = {
          name = "sprunk",
          price = 3,
          amount = 100,
          info = {},
          type = "item",
          slot = 3,
        },
        [4] = {
          name = "sandwich",
          price = 3,
          amount = 100,
          info = {},
          type = "item",
          slot = 4,
        },
        [5] = {
          name = "chocolade",
          price = 5,
          amount = 100,
          info = {},
          type = "item",
          slot = 5,
        },
        [6] = {
          name = "donut",
          price = 4,
          amount = 100,
          info = {},
          type = "item",
          slot = 6,
        },
        [7] = {
          name = "bandage",
          price = 15,
          amount = 100,
          info = {},
          type = "item",
          slot = 7,
        },
        [8] = {
          name = "apple",
          price = 4,
          amount = 100,
          info = {},
          type = "item",
          slot = 8,
        },
        [9] = {
          name = "banana",
          price = 4,
          amount = 100,
          info = {},
          type = "item",
          slot = 9,
        },
        [10] = {
          name = "rose",
          price = 25,
          amount = 10,
          info = {},
          type = "item",
          slot = 10,
        },
        [11] = {
          name = "umbrella",
          price = 5,
          amount = 10,
          info = {},
          type = "item",
          slot = 11,
        },
        [12] = {
          name = "hairtie",
          price = 25,
          amount = 10,
          info = {},
          type = "item",
          slot = 12,
        },
        [13] = {
          name = "lotto-card",
          price = 500,
          amount = 10,
          info = {},
          type = "item",
          slot = 13,
        },
        [14] = {
          name = "sushi-noodle",
          price = 10,
          amount = 100,
          info = {},
          type = "item",
          slot = 14,
        },
        [15] = {
          name = "sushi-rice",
          price = 10,
          amount = 100,
          info = {},
          type = "item",
          slot = 15,
        },
    },	
    ['Weed'] = {
        [1] = {
          name = "joint",
          price = 22,
          amount = 1000,
          info = {},
          type = "item",
          slot = 1,
        },
        [2] = {
          name = "empty_weed_bag",
          price = 30,
          amount = 1000,
          info = {},
          type = "item",
          slot = 2,
        },
        [3] = {
          name = "rolling-paper",
          price = 4,
          amount = 450,
          info = {},
          type = "item",
          slot = 3,
        },
        [4] = {
          name = "weed-nutrition",
          price = 18,
          amount = 1000,
          info = {},
          type = "item",
          slot = 4,
        },
        [5] = {
          name = "weed_white-widow_seed",
          price = 15,
          amount = 1000,
          info = {},
          type = "item",
          slot = 5,
        },
    },
    ['Sea'] = {
        [1] = {
          name = "fishingrod",
          price = 750,
          amount = 100,
          info = {},
          type = "item",
          slot = 1,
        },
        [2] = {
          name = "jerry_can",
          price = 1000,
          amount = 10,
          info = {},
          type = "item",
          slot = 2,
        },
    },
    ['Hardware'] = {
        [1] = {
          name = "lockpick",
          price = 115,
          amount = 100,
          info = {},
          type = "item",
          slot = 1,
        },
        [2] = {
          name = "screwdriverset",
          price = 250,
          amount = 100,
          info = {},
          type = "item",
          slot = 2,
        },
    },
    ['Hardware-2'] = {
        [1] = {
          name = "repairkit",
          price = 185,
          amount = 10,
          info = {},
          type = "item",
          slot = 1,
        },
        [2] = {
          name = "tirekit",
          price = 185,
          amount = 10,
          info = {},
          type = "item",
          slot = 2,
        },
        [3] = {
          name = "drill",
          price = 2500,
          amount = 10,
          info = {},
          type = "item",
          slot = 3,
        },
        [4] = {
          name = "drill-bit",
          price = 200,
          amount = 10,
          info = {},
          type = "item",
          slot = 4,
        },
        [5] = {
          name = "dice",
          price = 15,
          amount = 10,
          info = {},
          type = "item",
          slot = 5,
        },
        [6] = {
          name = "coin",
          price = 15,
          amount = 10,
          info = {},
          type = "item",
          slot = 6,
        },
        [7] = {
          name = "duffel-bag",
          price = 420,
          amount = 10,
          info = {},
          type = "item",
          slot = 7,
        },
        [8] = {
          name = "binoculars",
          price = 75,
          amount = 10,
          info = {},
          type = "item",
          slot = 8,
        },
        [9] = {
          name = "nitrous",
          price = 7500,
          amount = 5,
          info = {},
          type = "item",
          slot = 9,
        },
    },
    ['Vending'] = {
        [1] = {
          name = "donut",
          price = 6,
          amount = 100,
          info = {},
          type = "item",
          slot = 1,
        },
        [2] = {
          name = "420-choco",
          price = 14,
          amount = 100,
          info = {},
          type = "item",
          slot = 2,
        },
    },
    ['FVending'] = {
        [1] = {
          name = "kurkakola",
          price = 4,
          amount = 100,
          info = {},
          type = "item",
          slot = 1,
        },
        [2] = {
          name = "sprunk",
          price = 4,
          amount = 100,
          info = {},
          type = "item",
          slot = 2,
        },
    },
    ['Coffee'] = {
        [1] = {
          name = "coffee",
          price = 3,
          amount = 100,
          info = {},
          type = "item",
          slot = 1,
        },
    },
    ['Autocare'] = {
        [1] = {
          name = "repairkit",
          price = 150,
          amount = 100,
          info = {},
          type = "item",
          slot = 1,
        },
        [2] = {
          name = "screwdriverset",
          price = 200,
          amount = 100,
          info = {},
          type = "item",
          slot = 2,
        },
    },
    ['Digital'] = {
        [1] = {
          name = "phone",
          price = 500,
          amount = 10,
          info = {},
          type = "item",
          slot = 1,
        },
        [2] = {
          name = "radio",
          price = 150,
          amount = 10,
          info = {},
          type = "item",
          slot = 2,
        },
    },
    ['Mine'] = {
        [1] = {
          name = "pickaxe",
          price = 1000,
          amount = 1,
          info = {},
          type = "item",
          slot = 1,
        },
        [2] = {
          name = "mine-scanner",
          price = 1000,
          amount = 1,
          info = {},
          type = "item",
          slot = 2,
        },
    },
    ['Hunting'] = {
        [1] = {
          name = "weapon_sniperrifle2",
          price = 12500,
          amount = 1,
          info = {},
          type = "weapon",
          slot = 1,
        },
        [2] = {
          name = "rifle_ammo",
          price = 70,
          amount = 5,
          info = {},
          type = "item",
          slot = 2,
        },
        [3] = {
          name = "hunting-knife",
          price = 1250,
          amount = 1,
          info = {},
          type = "item",
          slot = 3,
        },
        [4] = {
          name = "hunting-bait",
          price = 5,
          amount = 100,
          info = {},
          type = "item",
          slot = 4,
        },
    }
}

Config.Shops = {
    [1] = {
      ['Name'] = '24/7 Avond Winkel',
      ['Type'] = 'Store',
      ['Coords'] = {
        ['X'] = 25.92,
        ['Y'] = -1346.68,
        ['Z'] = 29.49,
      },
      ['Product'] = Config.Products["Shops"]
    },
    [2] = {
      ['Name'] = 'LTD Gasoline',
      ['Type'] = 'Store',
      ['Coords'] = {
        ['X'] = -48.09,
        ['Y'] = -1757.16,
        ['Z'] = 29.42,
      },
      ['Product'] = Config.Products["Shops"]
    },
    [3] = {
      ['Name'] = 'LTD Gasoline',
      ['Type'] = 'Store',
      ['Coords'] = {
        ['X'] = -707.78,
        ['Y'] = -913.96,
        ['Z'] = 19.21,
      },
      ['Product'] = Config.Products["Shops"]
    },
    [4] = {
      ['Name'] = 'Rob\'s Liquor',
      ['Type'] = 'Store',
      ['Coords'] = {
        ['X'] = -1222.86,
        ['Y'] = -907.16,
        ['Z'] = 12.32,
      },
      ['Product'] = Config.Products["BShops"] -- Burgershot
    },
    [5] = {
      ['Name'] = 'Rob\'s Liquor',
      ['Type'] = 'Store',
      ['Coords'] = {
        ['X'] = 1135.79,
        ['Y'] = -981.91,
        ['Z'] = 46.41,
      },
      ['Product'] = Config.Products["Shops"]
    },
    [6] = {
      ['Name'] = 'Rob\'s Liquor',
      ['Type'] = 'Store',
      ['Coords'] = {
        ['X'] = -159.94,
        ['Y'] = 6322.61,
        ['Z'] = 31.58,
      },
      ['Product'] = Config.Products["Shops"]
    },
    [7] = {
      ['Name'] = '24/7 Avond Winkel',
      ['Type'] = 'Store',
      ['Coords'] = {
        ['X'] = 162.10,
        ['Y'] = 6641.16,
        ['Z'] = 31.69,
      },
      ['Product'] = Config.Products["Shops"]
    },
    [8] = {
      ['Name'] = '24/7 Avond Winkel',
      ['Type'] = 'Store',
      ['Coords'] = {
        ['X'] = 1729.43,
        ['Y'] = 6415.32,
        ['Z'] = 35.03,
      },
      ['Product'] = Config.Products["Shops"]
    },
    [9] = {
      ['Name'] = 'LTD Gasoline',
      ['Type'] = 'Store',
      ['Coords'] = {
        ['X'] = 1698.82,
        ['Y'] = 4924.58,
        ['Z'] = 42.06,
      },
      ['Product'] = Config.Products["Shops"]
    },
    [10] = {
      ['Name'] = '24/7 Avond Winkel',
      ['Type'] = 'Store',
      ['Coords'] = {
        ['X'] = 2678.00,
        ['Y'] = 3281.03,
        ['Z'] = 55.24,
      },
      ['Product'] = Config.Products["Shops"]
    },
    [11] = {
      ['Name'] = '24/7 Avond Winkel',
      ['Type'] = 'Store',
      ['Coords'] = {
        ['X'] = 1961.00,
        ['Y'] = 3741.30,
        ['Z'] = 32.34,
      },
      ['Product'] = Config.Products["Shops"]
    },
    [12] = {
      ['Name'] = 'Rob\'s Liquor',
      ['Type'] = 'Store',
      ['Coords'] = {
        ['X'] = 1166.12,
        ['Y'] = 2709.18,
        ['Z'] = 38.15,
      },
      ['Product'] = Config.Products["Shops"]
    },
    [13] = {
      ['Name'] = '24/7 Avond Winkel',
      ['Type'] = 'Store',
      ['Coords'] = {
        ['X'] = 547.99,
        ['Y'] = 2670.43,
        ['Z'] = 42.15,
      },
      ['Product'] = Config.Products["Shops"]
    },
    [14] = {
      ['Name'] = 'LTD Gasoline',
      ['Type'] = 'Store',
      ['Coords'] = {
        ['X'] = -1820.98,
        ['Y'] = 792.98,
        ['Z'] = 138.116,
      },
      ['Product'] = Config.Products["Shops"]
    },
    [15] = {
      ['Name'] = '24/7 Avond Winkel',
      ['Type'] = 'Store',
      ['Coords'] = {
        ['X'] = -3243.04,
        ['Y'] = 1001.49,
        ['Z'] = 12.83,
      },
      ['Product'] = Config.Products["Shops"]
    },
    [16] = {
      ['Name'] = '24/7 Avond Winkel',
      ['Type'] = 'Store',
      ['Coords'] = {
        ['X'] = -3040.01,
        ['Y'] = 585.66,
        ['Z'] = 7.9,
      },
      ['Product'] = Config.Products["Shops"]
    },
    [17] = {
      ['Name'] = 'Rob\'s Liquor',
      ['Type'] = 'Store',
      ['Coords'] = {
        ['X'] = -2967.93,
        ['Y'] = 391.03,
        ['Z'] = 15.04,
      },
      ['Product'] = Config.Products["Shops"]
    },
    [18] = {
      ['Name'] = 'Rob\'s Liquor',
      ['Type'] = 'Store',
      ['Coords'] = {
        ['X'] = -1487.37,
        ['Y'] = -379.13,
        ['Z'] = 40.16,
      },
      ['Product'] = Config.Products["Shops"]
    },
    [19] = {
      ['Name'] = '24/7 Avond Winkel',
      ['Type'] = 'Store',
      ['Coords'] = {
        ['X'] = 374.08,
        ['Y'] = 326.64,
        ['Z'] = 103.56,
      },
      ['Product'] = Config.Products["SShops"]
    },
    [20] = {
      ['Name'] = '24/7 Avond Winkel',
      ['Type'] = 'Store',
      ['Coords'] = {
        ['X'] = 2556.50,
        ['Y'] = 382.16,
        ['Z'] = 108.62,
      },
      ['Product'] = Config.Products["Shops"]
    },
    [21] = {
      ['Name'] = 'LTD Gasoline',
      ['Type'] = 'Store',
      ['Coords'] = {
        ['X'] = 1163.50,
        ['Y'] = -323.27,
        ['Z'] = 69.20,
      },
      ['Product'] = Config.Products["Shops"]
    },
    [22] = {
      ['Name'] = 'Slotenmaker',
      ['Type'] = 'Hardware',
      ['Coords'] = {
        ['X'] = 170.14,
        ['Y'] = -1799.22,
        ['Z'] = 29.31,
      },
      ['Product'] = Config.Products["Hardware"]
    },
    [23] = {
      ['Name'] = 'Hardware Store',
      ['Type'] = 'Hardware',
      ['Coords'] = {
        ['X'] = 44.74,
        ['Y'] = -1748.21,
        ['Z'] = 29.52,
      },
      ['Product'] = Config.Products["Hardware-2"]
    },
    [24] = {
      ['Name'] = 'Hardware Store',
      ['Type'] = 'Hardware',
      ['Coords'] = {
        ['X'] = 2748.84,
        ['Y'] = 3472.50,
        ['Z'] = 55.67,
      },
      ['Product'] = Config.Products["Hardware-2"]
    },
    [25] = {
      ['Name'] = 'Weed Store',
      ['Type'] = 'Store',
      ['Coords'] = {
        ['X'] = -1171.89,
        ['Y'] = -1572.03,
        ['Z'] = 4.66,
      },
      ['Product'] = Config.Products["Weed"]
    },
    [26] = {
      ['Name'] = 'Sea Store',
      ['Type'] = 'Store',
      ['Coords'] = {
        ['X'] = -1686.52,
        ['Y'] = -1072.51,
        ['Z'] = 13.15,
      },
      ['Product'] = Config.Products["Sea"]
    },
    [27] = {
      ['Name'] = 'Autocare Store',
      ['Type'] = 'Store',
      ['Coords'] = {
        ['X'] = -1429.93,
        ['Y'] = -453.46,
        ['Z'] = 35.90,
      },
      ['Product'] = Config.Products["Autocare"]
    },
    [28] = {
      ['Name'] = 'DigitalDen Store',
      ['Type'] = 'Store',
      ['Coords'] = {
        ['X'] = 1131.95,
        ['Y'] = -469.18,
        ['Z'] = 66.48,
      },
      ['Product'] = Config.Products["Digital"]
    },
    [29] = {
      ['Name'] = 'Hunting Store',
      ['Type'] = 'Store',
      ['Coords'] = {
        ['X'] = -677.31,
        ['Y'] = 5839.51,
        ['Z'] = 17.33,
      },
      ['Product'] = Config.Products["Hunting"]
    },
    [30] = {
      ['Name'] = 'Mijn Store',
      ['Type'] = 'Store',
      ['Coords'] = {
        ['X'] = -595.61,
        ['Y'] = 2091.70,
        ['Z'] = 131.46,
      },
      ['Product'] = Config.Products["Mine"]
    },
}