Config = Config or {}

Config.Locations = 'Ga maar zoeken..'

Config.CraftingItems = {
      [1] = {
          ['Label'] = 'Lockpick',
          ['ItemName'] = 'lockpick',
          ['Slot'] = 1,
          ['Amount'] = 10,
          ['Info'] = '',
          ['Weight'] = 1000,
          ['Image'] = 'lockpick.png',
          ['AddingPoints'] = 2,
          ['PointsNeeded'] = 0,
          ['Cost'] = {
              [1] = {
                  ['Label'] = 'Plastic',
                  ['ItemName'] = 'plastic',
                  ['Image'] = 'plastic.png',
                  ['Amount'] = 32,
              },
              [2] = {
                  ['Label'] = 'Metaal Schroot',
                  ['ItemName'] = 'metalscrap',
                  ['Image'] = 'metalscrap.png',
                  ['Amount'] = 22,
              },
          },
      },
      [2] = {
          ['Label'] = 'Toolkit',
          ['ItemName'] = 'screwdriverset',
          ['Slot'] = 2,
          ['Amount'] = 10,
          ['Info'] = '',
          ['Weight'] = 450,
          ['Image'] = 'toolkit.png',
          ['AddingPoints'] = 2,
          ['PointsNeeded'] = 0,
          ['Cost'] = {
              [1] = {
                  ['Label'] = 'Plastic',
                  ['ItemName'] = 'plastic',
                  ['Image'] = 'plastic.png',
                  ['Amount'] = 42,
              },
              [2] = {
                  ['Label'] = 'Metaal Schroot',
                  ['ItemName'] = 'metalscrap',
                  ['Image'] = 'metalscrap.png',
                  ['Amount'] = 30,
              },
          },
      },
      [3] = {
          ['Label'] = 'Electronic Kit',
          ['ItemName'] = 'electronickit',
          ['Slot'] = 3,
          ['Amount'] = 10,
          ['Info'] = '',
          ['Weight'] = 1000,
          ['Image'] = 'electronickit.png',
          ['AddingPoints'] = 3,
          ['PointsNeeded'] = 0,
          ['Cost'] = {
              [1] = {
                  ['Label'] = 'Plastic',
                  ['ItemName'] = 'plastic',
                  ['Image'] = 'plastic.png',
                  ['Amount'] = 45,
              },
              [2] = {
                  ['Label'] = 'Metaal Schroot',
                  ['ItemName'] = 'metalscrap',
                  ['Image'] = 'metalscrap.png',
                  ['Amount'] = 30,
              },
              [3] = {
                  ['Label'] = 'Aluminum',
                  ['ItemName'] = 'aluminum',
                  ['Image'] = 'aluminum.png',
                  ['Amount'] = 28,
              },
          },
      },
      [4] = {
          ['Label'] = 'Plastic Zakje',
          ['ItemName'] = 'empty_weed_bag',
          ['Slot'] = 4,
          ['Amount'] = 10,
          ['Info'] = '',
          ['Weight'] = 200,
          ['Image'] = 'plastic-bag.png',
          ['AddingPoints'] = 0,
          ['PointsNeeded'] = 0,
          ['Cost'] = {
              [1] = {
                  ['Label'] = 'Plastic',
                  ['ItemName'] = 'plastic',
                  ['Image'] = 'plastic.png',
                  ['Amount'] = 5,
              },
          },
      },
      [5] = {
          ['Label'] = 'Reparatie Set',
          ['ItemName'] = 'repairkit',
          ['Slot'] = 5,
          ['Amount'] = 10,
          ['Info'] = '',
          ['Weight'] = 2500,
          ['Image'] = 'repairkit.png',
          ['AddingPoints'] = 2,
          ['PointsNeeded'] = 100,
          ['Cost'] = {
              [1] = {
                  ['Label'] = 'Metaal Schroot',
                  ['ItemName'] = 'metalscrap',
                  ['Image'] = 'metalscrap.png',
                  ['Amount'] = 32,
              },
              [2] = {
                  ['Label'] = 'Staal',
                  ['ItemName'] = 'steel',
                  ['Image'] = 'steel.png',
                  ['Amount'] = 43,
              },
              [3] = {
                  ['Label'] = 'Plastic',
                  ['ItemName'] = 'plastic',
                  ['Image'] = 'plastic.png',
                  ['Amount'] = 61,
              },
          },
      },
      [6] = {
          ['Label'] = 'Handboeien',
          ['ItemName'] = 'handcuffs',
          ['Slot'] = 6,
          ['Amount'] = 10,
          ['Info'] = '',
          ['Weight'] = 1250,
          ['Image'] = 'cuffs.png',
          ['AddingPoints'] = 3,
          ['PointsNeeded'] = 250,
          ['Cost'] = {
              [1] = {
                  ['Label'] = 'Metaal Schroot',
                  ['ItemName'] = 'metalscrap',
                  ['Image'] = 'metalscrap.png',
                  ['Amount'] = 36,
              },
              [2] = {
                  ['Label'] = 'Staal',
                  ['ItemName'] = 'steel',
                  ['Image'] = 'steel.png',
                  ['Amount'] = 24,
              },
              [3] = {
                  ['Label'] = 'Aluminum',
                  ['ItemName'] = 'aluminum',
                  ['Image'] = 'aluminum.png',
                  ['Amount'] = 28,
              },
          },
      },
      [7] = {
          ['Label'] = 'Kogel Vest',
          ['ItemName'] = 'armor',
          ['Slot'] = 7,
          ['Amount'] = 10,
          ['Info'] = '',
          ['Weight'] = 13500,
          ['Image'] = 'vest.png',
          ['AddingPoints'] = 3,
          ['PointsNeeded'] = 300,
          ['Cost'] = {
              [1] = {
                  ['Label'] = 'Plastic',
                  ['ItemName'] = 'plastic',
                  ['Image'] = 'plastic.png',
                  ['Amount'] = 55,
              },
              [2] = {
                  ['Label'] = 'Staal',
                  ['ItemName'] = 'steel',
                  ['Image'] = 'steel.png',
                  ['Amount'] = 44,
              },
              [3] = {
                  ['Label'] = 'Ijzer',
                  ['ItemName'] = 'iron',
                  ['Image'] = 'ironplate.png',
                  ['Amount'] = 33,
              },
              [4] = {
                  ['Label'] = 'Aluminium',
                  ['ItemName'] = 'aluminum',
                  ['Image'] = 'aluminum.png',
                  ['Amount'] = 22,
              },
          },
      },
      [8] = {
          ['Label'] = 'Pistool Kogels',
          ['ItemName'] = 'pistol_ammo',
          ['Slot'] = 8,
          ['Amount'] = 10,
          ['Info'] = '',
          ['Weight'] = 500,
          ['Image'] = 'ammo-pistol.png',
          ['AddingPoints'] = 3,
          ['PointsNeeded'] = 350,
          ['Cost'] = {
              [1] = {
                  ['Label'] = 'Metaal Schroot',
                  ['ItemName'] = 'metalscrap',
                  ['Image'] = 'metalscrap.png',
                  ['Amount'] = 50,
              },
              [2] = {
                  ['Label'] = 'Staal',
                  ['ItemName'] = 'steel',
                  ['Image'] = 'steel.png',
                  ['Amount'] = 37,
              },
              [3] = {
                  ['Label'] = 'Koper',
                  ['ItemName'] = 'copper',
                  ['Image'] = 'copper.png',
                  ['Amount'] = 26,
              },
              [4] = {
                  ['Label'] = 'Aluminium Poeder',
                  ['ItemName'] = 'aluminumoxide',
                  ['Image'] = 'aluminumoxide.png',
                  ['Amount'] = 3,
              },
              [5] = {
                  ['Label'] = 'Ijzer Poeder',
                  ['ItemName'] = 'ironoxide',
                  ['Image'] = 'ironoxide.png',
                  ['Amount'] = 3,
              },
          },
      },
      [9] = {
          ['Label'] = 'SMG Kogels',
          ['ItemName'] = 'smg_ammo',
          ['Slot'] = 9,
          ['Amount'] = 10,
          ['Info'] = '',
          ['Weight'] = 650,
          ['Image'] = 'ammo-smg.png',
          ['AddingPoints'] = 3,
          ['PointsNeeded'] = 450,
          ['Cost'] = {
              [1] = {
                  ['Label'] = 'Metaal Schroot',
                  ['ItemName'] = 'metalscrap',
                  ['Image'] = 'metalscrap.png',
                  ['Amount'] = 65,
              },
              [2] = {
                  ['Label'] = 'Staal',
                  ['ItemName'] = 'steel',
                  ['Image'] = 'steel.png',
                  ['Amount'] = 41,
              },
              [3] = {
                  ['Label'] = 'Koper',
                  ['ItemName'] = 'copper',
                  ['Image'] = 'copper.png',
                  ['Amount'] = 26,
              },
              [4] = {
                  ['Label'] = 'Aluminium Poeder',
                  ['ItemName'] = 'aluminumoxide',
                  ['Image'] = 'aluminumoxide.png',
                  ['Amount'] = 4,
              },
              [5] = {
                  ['Label'] = 'Ijzer Poeder',
                  ['ItemName'] = 'ironoxide',
                  ['Image'] = 'ironoxide.png',
                  ['Amount'] = 4,
              },
          },
      },
      [10] = {
          ['Label'] = 'Shotgun Slugs',
          ['ItemName'] = 'shotgun_ammo',
          ['Slot'] = 10,
          ['Amount'] = 10,
          ['Info'] = '',
          ['Weight'] = 650,
          ['Image'] = 'ammo-shotgun.png',
          ['AddingPoints'] = 3,
          ['PointsNeeded'] = 500,
          ['Cost'] = {
              [1] = {
                  ['Label'] = 'Metaal Schroot',
                  ['ItemName'] = 'metalscrap',
                  ['Image'] = 'metalscrap.png',
                  ['Amount'] = 75,
              },
              [2] = {
                  ['Label'] = 'Staal',
                  ['ItemName'] = 'steel',
                  ['Image'] = 'steel.png',
                  ['Amount'] = 40,
              },
              [3] = {
                  ['Label'] = 'Koper',
                  ['ItemName'] = 'copper',
                  ['Image'] = 'copper.png',
                  ['Amount'] = 28,
              },
              [4] = {
                  ['Label'] = 'Aluminium Poeder',
                  ['ItemName'] = 'aluminumoxide',
                  ['Image'] = 'aluminumoxide.png',
                  ['Amount'] = 5,
              },
              [5] = {
                  ['Label'] = 'Ijzer Poeder',
                  ['ItemName'] = 'ironoxide',
                  ['Image'] = 'ironoxide.png',
                  ['Amount'] = 5,
              },
          },
      },
      [11] = {
          ['Label'] = 'Mes Onderdeel',
          ['ItemName'] = 'knife-part-2',
          ['Slot'] = 11,
          ['Amount'] = 10,
          ['Info'] = '',
          ['Weight'] = 450,
          ['Image'] = 'knife-part-2.png',
          ['AddingPoints'] = 3,
          ['PointsNeeded'] = 550,
          ['Cost'] = {
              [1] = {
                  ['Label'] = 'Metaal Schroot',
                  ['ItemName'] = 'metalscrap',
                  ['Image'] = 'metalscrap.png',
                  ['Amount'] = 72,
              },
              [2] = {
                  ['Label'] = 'Staal',
                  ['ItemName'] = 'steel',
                  ['Image'] = 'steel.png',
                  ['Amount'] = 33,
              },
              [3] = {
                  ['Label'] = 'Ijzer',
                  ['ItemName'] = 'iron',
                  ['Image'] = 'ironplate.png',
                  ['Amount'] = 51,
              },
          },
      },
      [12] = {
          ['Label'] = 'Klapmes Onderdeel',
          ['ItemName'] = 'switch-part-2',
          ['Slot'] = 12,
          ['Amount'] = 10,
          ['Info'] = '',
          ['Weight'] = 450,
          ['Image'] = 'switch-part-2.png',
          ['AddingPoints'] = 3,
          ['PointsNeeded'] = 550,
          ['Cost'] = {
              [1] = {
                  ['Label'] = 'Metaal Schroot',
                  ['ItemName'] = 'metalscrap',
                  ['Image'] = 'metalscrap.png',
                  ['Amount'] = 72,
              },
              [2] = {
                  ['Label'] = 'Staal',
                  ['ItemName'] = 'steel',
                  ['Image'] = 'steel.png',
                  ['Amount'] = 33,
              },
              [3] = {
                  ['Label'] = 'Ijzer',
                  ['ItemName'] = 'iron',
                  ['Image'] = 'ironplate.png',
                  ['Amount'] = 51,
              },
          },
      },
      [13] = {
          ['Label'] = 'Extended Clip',
          ['ItemName'] = 'pistol_extendedclip',
          ['Slot'] = 13,
          ['Amount'] = 10,
          ['Info'] = '',
          ['Weight'] = 1000,
          ['Image'] = 'pistol_extendedclip.png',
          ['AddingPoints'] = 3,
          ['PointsNeeded'] = 700,
          ['Cost'] = {
              [1] = {
                  ['Label'] = 'Metaal Schroot',
                  ['ItemName'] = 'metalscrap',
                  ['Image'] = 'metalscrap.png',
                  ['Amount'] = 105,
              },
              [2] = {
                  ['Label'] = 'Staal',
                  ['ItemName'] = 'steel',
                  ['Image'] = 'steel.png',
                  ['Amount'] = 48,
              },
              [3] = {
                  ['Label'] = 'Ijzer',
                  ['ItemName'] = 'iron',
                  ['Image'] = 'ironplate.png',
                  ['Amount'] = 36,
              },
              [4] = {
                  ['Label'] = 'Rubber',
                  ['ItemName'] = 'rubber',
                  ['Image'] = 'rubber.png',
                  ['Amount'] = 100,
              },
          },
      },
      [14] = {
          ['Label'] = 'SNS Loop',
          ['ItemName'] = 'snspistol_part_1',
          ['Slot'] = 14,
          ['Amount'] = 10,
          ['Info'] = '',
          ['Weight'] = 1500,
          ['Image'] = 'snspistol_part_1.png',
          ['AddingPoints'] = 5,
          ['PointsNeeded'] = 715,
          ['Cost'] = {
              [1] = {
                  ['Label'] = 'Metaal Schroot',
                  ['ItemName'] = 'metalscrap',
                  ['Image'] = 'metalscrap.png',
                  ['Amount'] = 225,
              },
              [2] = {
                  ['Label'] = 'Staal',
                  ['ItemName'] = 'steel',
                  ['Image'] = 'steel.png',
                  ['Amount'] = 51,
              },
              [3] = {
                  ['Label'] = 'Ijzer',
                  ['ItemName'] = 'iron',
                  ['Image'] = 'ironplate.png',
                  ['Amount'] = 61,
              },
              [4] = {
                  ['Label'] = 'Rubber',
                  ['ItemName'] = 'rubber',
                  ['Image'] = 'rubber.png',
                  ['Amount'] = 145,
              },
          },
      },
      [15] = {
          ['Label'] = 'Aluminium Poeder',
          ['ItemName'] = 'aluminumoxide',
          ['Slot'] = 15,
          ['Amount'] = 10,
          ['Info'] = '',
          ['Weight'] = 100,
          ['Image'] = 'aluminumoxide.png',
          ['AddingPoints'] = 2,
          ['PointsNeeded'] = 800,
          ['Cost'] = {
              [1] = {
                  ['Label'] = 'Aluminium',
                  ['ItemName'] = 'aluminum',
                  ['Image'] = 'aluminum.png',
                  ['Amount'] = 60,
              },
              [2] = {
                  ['Label'] = 'Glasplaat',
                  ['ItemName'] = 'glass',
                  ['Image'] = 'glassplate.png',
                  ['Amount'] = 30,
              },
          },
      },
      [16] = {
          ['Label'] = 'Ijzer Poeder',
          ['ItemName'] = 'ironoxide',
          ['Slot'] = 16,
          ['Amount'] = 10,
          ['Info'] = '',
          ['Weight'] = 100,
          ['Image'] = 'ironoxide.png',
          ['AddingPoints'] = 2,
          ['PointsNeeded'] = 800,
          ['Cost'] = {
              [1] = {
                  ['Label'] = 'Ijzer',
                  ['ItemName'] = 'iron',
                  ['Image'] = 'ironplate.png',
                  ['Amount'] = 60,
              },
              [2] = {
                  ['Label'] = 'Glasplaat',
                  ['ItemName'] = 'glass',
                  ['Image'] = 'glassplate.png',
                  ['Amount'] = 30,
              },
          },
      },
      [17] = {
          ['Label'] = 'Explosief',
          ['ItemName'] = 'explosive',
          ['Slot'] = 17,
          ['Amount'] = 10,
          ['Info'] = '',
          ['Weight'] = 4500,
          ['Image'] = 'explosive.png',
          ['AddingPoints'] = 2,
          ['PointsNeeded'] = 800,
          ['Cost'] = {
              [1] = {
                  ['Label'] = 'Metaal Schroot',
                  ['ItemName'] = 'metalscrap',
                  ['Image'] = 'metalscrap.png',
                  ['Amount'] = 110,
              },
              [2] = {
                  ['Label'] = 'Plastic',
                  ['ItemName'] = 'plastic',
                  ['Image'] = 'plastic.png',
                  ['Amount'] = 150,
              },
              [3] = {
                  ['Label'] = 'Thermiet',
                  ['ItemName'] = 'thermite',
                  ['Image'] = 'thermite.png',
                  ['Amount'] = 4,
              },
              [4] = {
                  ['Label'] = 'Rubber',
                  ['ItemName'] = 'rubber',
                  ['Image'] = 'rubber.png',
                  ['Amount'] = 20,
              },
              [5] = {
                  ['Label'] = 'Electronic Kit',
                  ['ItemName'] = 'electronickit',
                  ['Image'] = 'electronickit.png',
                  ['Amount'] = 2,
              },
          },
      },
      [18] = {
          ['Label'] = 'Zwaar Thermiet',
          ['ItemName'] = 'heavy-thermite',
          ['Slot'] = 18,
          ['Amount'] = 10,
          ['Info'] = '',
          ['Weight'] = 10000,
          ['Image'] = 'hthermite.png',
          ['AddingPoints'] = 2,
          ['PointsNeeded'] = 1000,
          ['Cost'] = {
              [1] = {
                  ['Label'] = 'Metaal Schroot',
                  ['ItemName'] = 'metalscrap',
                  ['Image'] = 'metalscrap.png',
                  ['Amount'] = 210,
              },
              [2] = {
                  ['Label'] = 'Staal',
                  ['ItemName'] = 'steel',
                  ['Image'] = 'steel.png',
                  ['Amount'] = 75,
              },
              [3] = {
                  ['Label'] = 'Koper',
                  ['ItemName'] = 'copper',
                  ['Image'] = 'copper.png',
                  ['Amount'] = 33,
              },
              [4] = {
                  ['Label'] = 'Thermiet',
                  ['ItemName'] = 'thermite',
                  ['Image'] = 'thermite.png',
                  ['Amount'] = 10,
              },
              [5] = {
                  ['Label'] = 'Rubber',
                  ['ItemName'] = 'rubber',
                  ['Image'] = 'rubber.png',
                  ['Amount'] = 10,
              },
          },
      },
}