Citizen.CreateThread(function()
    RequestIpl("gabz_mrpd_milo_")
    local interiorId = GetInteriorAtCoords(451.0129, -993.3741, 29.1718)
    if IsValidInterior(interiorId) then      
        EnableInteriorProp(interiorId, "v_gabz_mrpd_rm1")
        EnableInteriorProp(interiorId, "v_gabz_mrpd_rm2")
        EnableInteriorProp(interiorId, "v_gabz_mrpd_rm3")
        EnableInteriorProp(interiorId, "v_gabz_mrpd_rm4")
        EnableInteriorProp(interiorId, "v_gabz_mrpd_rm5")
        EnableInteriorProp(interiorId, "v_gabz_mrpd_rm6")
        EnableInteriorProp(interiorId, "v_gabz_mrpd_rm7")
        EnableInteriorProp(interiorId, "v_gabz_mrpd_rm8")
        EnableInteriorProp(interiorId, "v_gabz_mrpd_rm9")
        EnableInteriorProp(interiorId, "v_gabz_mrpd_rm10")
        EnableInteriorProp(interiorId, "v_gabz_mrpd_rm11")
        EnableInteriorProp(interiorId, "v_gabz_mrpd_rm12")
        EnableInteriorProp(interiorId, "v_gabz_mrpd_rm13")
        EnableInteriorProp(interiorId, "v_gabz_mrpd_rm14")
        EnableInteriorProp(interiorId, "v_gabz_mrpd_rm15")
        EnableInteriorProp(interiorId, "v_gabz_mrpd_rm16")
        EnableInteriorProp(interiorId, "v_gabz_mrpd_rm17")
        EnableInteriorProp(interiorId, "v_gabz_mrpd_rm18")
        EnableInteriorProp(interiorId, "v_gabz_mrpd_rm19")
        EnableInteriorProp(interiorId, "v_gabz_mrpd_rm20")
        EnableInteriorProp(interiorId, "v_gabz_mrpd_rm21")
        EnableInteriorProp(interiorId, "v_gabz_mrpd_rm22")
        EnableInteriorProp(interiorId, "v_gabz_mrpd_rm23")
        EnableInteriorProp(interiorId, "v_gabz_mrpd_rm24")
        EnableInteriorProp(interiorId, "v_gabz_mrpd_rm25")
        EnableInteriorProp(interiorId, "v_gabz_mrpd_rm26")
        EnableInteriorProp(interiorId, "v_gabz_mrpd_rm27")
        EnableInteriorProp(interiorId, "v_gabz_mrpd_rm28")
        EnableInteriorProp(interiorId, "v_gabz_mrpd_rm29")
        EnableInteriorProp(interiorId, "v_gabz_mrpd_rm30")
        EnableInteriorProp(interiorId, "v_gabz_mrpd_rm31")
        RefreshInterior(interiorId)
    end
end)