Config = Config or {}

Config.PedInteraction = {
    [1] = {
        ['Type'] = 'Toolshop',
        ['Model'] = 's_m_m_gardener_01',
        ['Animation'] = "WORLD_HUMAN_CLIPBOARD",
        ['InteractAnimation'] = nil,
        ['Coords'] = vector3(170.00, -1799.54, 29.31),
        ['Heading'] = 315.65,
    },
    [2] = {
        ['Type'] = 'Toolshop',
        ['Model'] = 's_m_m_gardener_01',
        ['Animation'] = "WORLD_HUMAN_CLIPBOARD",
        ['InteractAnimation'] = nil,
        ['Coords'] = vector3(46.45, -1749.53, 29.63),
        ['Heading'] = 43.75,
    },
    [3] = {
        ['Type'] = 'Toolshop',
        ['Model'] = 's_m_m_gardener_01',
        ['Animation'] = "WORLD_HUMAN_CLIPBOARD",
        ['InteractAnimation'] = nil,
        ['Coords'] = vector3(2748.08, 3472.64, 55.67),
        ['Heading'] = 245.64,
    },
    [4] = {
        ['Type'] = 'Main-Bank',
        ['Model'] = 's_m_m_highsec_02',
        ['Animation'] = "WORLD_HUMAN_CLIPBOARD",
        ['InteractAnimation'] = nil,
        ['Coords'] = vector3(241.35, 225.22, 106.28),
        ['Heading'] = 161.56,
    },
    [5] = {
        ['Type'] = 'Fisher',
        ['Model'] = 'a_f_m_prolhost_01',
        ['Animation'] = "",
        ['InteractAnimation'] = nil,
        ['Coords'] = vector3(-1686.35, -1072.63, 13.15),
        ['Heading'] = 52.82,
    },
    [6] = {
        ['Type'] = 'Electronics',
        ['Model'] = 'a_m_m_bevhills_02',
        ['Animation'] = "WORLD_HUMAN_CLIPBOARD",
        ['InteractAnimation'] = nil,
        ['Coords'] = vector3(1134.45, -468.13, 66.48),
        ['Heading'] = 166.48,
    },
    [7] = {
        ['Type'] = 'Oxy',
        ['Model'] = 'a_m_m_soucent_03',
        ['Animation'] = "",
        ['InteractAnimation'] = nil,
        ['Coords'] = vector3(745.35, -482.39, 26.29),
        ['Heading'] = 215.44,
    },
    [8] = {
        ['Type'] = 'Rental',
        ['Model'] = 'a_m_m_eastsa_02',
        ['Animation'] = "",
        ['InteractAnimation'] = nil,
        ['Coords'] = vector3(110.93, -1090.56, 29.30),
        ['Heading'] = 27.29,
    },
    [9] = {
        ['Type'] = 'Secret-Sell',
        ['Model'] = 'a_f_m_ktown_02',
        ['Animation'] = "",
        ['InteractAnimation'] = nil,
        ['Coords'] = vector3(-1846.87, -1190.70, 14.32),
        ['Heading'] = 149.82,
    },
    [10] = {
        ['Type'] = 'Casino-Shit',
        ['Model'] = 'u_f_m_casinocash_01',
        ['Animation'] = "",
        ['InteractAnimation'] = nil,
        ['Coords'] = vector3(1117.25, 220.03, -49.43),
        ['Heading'] = 88.73,
    },
    [11] = {
        ['Type'] = 'Casino-Shit',
        ['Model'] = 'u_f_m_casinocash_01',
        ['Animation'] = "",
        ['InteractAnimation'] = nil,
        ['Coords'] = vector3(1117.25, 220.03, -49.43),
        ['Heading'] = 88.73,
    },
    [12] = {
        ['Type'] = 'HouseRob',
        ['Model'] = 'a_f_y_vinewood_02',
        ['Animation'] = "",
        ['InteractAnimation'] = nil,
        ['Coords'] = vector3(-351.71, -108.10, 38.69),
        ['Heading'] = 161.47,
    },
    [13] = {
        ['Type'] = 'SellWeed',
        ['Model'] = 'a_m_m_farmer_01',
        ['Animation'] = "",
        ['InteractAnimation'] = nil,
        ['Coords'] = vector3(166.99, 2229.06, 90.78),
        ['Heading'] = 56.10,
    },
    [14] = {
        ['Type'] = 'PoliceGarage',
        ['Model'] = 'csb_trafficwarden',
        ['Animation'] = "",
        ['InteractAnimation'] = nil,
        ['Coords'] = vector3(441.40, -998.27, 25.69),
        ['Heading'] = 0.14,
    },
    [15] = {
        ['Type'] = 'PoliceGarage',
        ['Model'] = 'csb_trafficwarden',
        ['Animation'] = "",
        ['InteractAnimation'] = nil,
        ['Coords'] = vector3(-446.84, 6022.74, 31.55),
        ['Heading'] = 309.72,
    },
    [16] = {
        ['Type'] = 'Pilot',
        ['Model'] = 's_m_m_pilot_01',
        ['Animation'] = "",
        ['InteractAnimation'] = nil,
        ['Coords'] = vector3(-941.05, -2954.26, 13.94),
        ['Heading'] = 149.30,
    },
    [17] = {
        ['Type'] = 'BarsSell',
        ['Model'] = 'g_m_m_mexboss_01',
        ['Animation'] = "",
        ['InteractAnimation'] = nil,
        ['Coords'] = vector3(1082.51, -787.57, 58.32),
        ['Heading'] = 179.91,
    },
    [18] = {
        ['Type'] = 'HuntingSell',
        ['Model'] = 's_m_m_ammucountry',
        ['Animation'] = "",
        ['InteractAnimation'] = nil,
        ['Coords'] = vector3(569.13, 2796.66, 42.01),
        ['Heading'] = 275.00,
    },
    [19] = {
        ['Type'] = 'OtherSell',
        ['Model'] = 'mp_m_waremech_01',
        ['Animation'] = "",
        ['InteractAnimation'] = nil,
        ['Coords'] = vector3(-203.47, -1328.22, 34.89),
        ['Heading'] = 88.31,
    },
    [20] = {
        ['Type'] = 'Pickaxe',
        ['Model'] = 'ig_old_man2',
        ['Animation'] = "",
        ['InteractAnimation'] = nil,
        ['Coords'] = vector3(-595.12, 2091.35, 131.46),
        ['Heading'] = 57.67,
    },
}