Config = Config or {}

Config.BusyVehicles = {}

Config.VehiclePartData = {}

Config.VehicleBrakes = {}

Config.Locations = {
    ['TowVeh'] = {
        [1] = {['X'] = -1408.36, ['Y'] = -459.35, ['Z'] = 34.48, ['H'] = 122.17},
        [2] = {['X'] = 1120.83, ['Y'] = -778.74, ['Z'] = 57.77, ['H'] = 359.65},
    },
}

Config.RepairCosts = {
    ['Aandrijfas'] = {
        ['Label'] = 'Staal',
        ['Item'] = 'steel',
        ['S'] = {['Amount'] = math.random(75,95)},
        ['A'] = {['Amount'] = math.random(45,70)},
        ['B'] = {['Amount'] = math.random(15,20)},
    },       
    ['Brandstof Injectoren'] = {
        ['Label'] = 'Aluminium',
        ['Item'] = 'aluminum',
        ['S'] = {['Amount'] = math.random(75,95)},
        ['A'] = {['Amount'] = math.random(45,70)},
        ['B'] = {['Amount'] = math.random(15,20)},
    },       
    ['Transmissie'] = {
        ['Label'] = 'Metaal schroot',
        ['Item'] = 'metalscrap',
        ['S'] = {['Amount'] = math.random(75,95)},
        ['A'] = {['Amount'] = math.random(45,70)},
        ['B'] = {['Amount'] = math.random(15,20)},
    },       
    ['Motor'] = {
        ['Label'] = 'Ijzer',
        ['Item'] = 'iron',
        ['S'] = {['Amount'] = math.random(75,95)},
        ['A'] = {['Amount'] = math.random(45,70)},
        ['B'] = {['Amount'] = math.random(15,20)},
    },       
    ['Remmen'] = {
        ['Label'] = 'Koper',
        ['Item'] = 'copper',
        ['S'] = {['Amount'] = math.random(75,95)},
        ['A'] = {['Amount'] = math.random(45,70)},
        ['B'] = {['Amount'] = math.random(15,20)},
    },       
    ['Koppeling'] = {
        ['Label'] = 'Staal',
        ['Item'] = 'steel',
        ['S'] = {['Amount'] = math.random(75,95)},
        ['A'] = {['Amount'] = math.random(45,70)},
        ['B'] = {['Amount'] = math.random(15,20)},
    },       
}

Config.MechanicProps = {
    [1] = {
        ['Prop'] = 'v_ind_cf_flour',
        ['Coords'] = {
            ['X'] = -1415.23, 
            ['Y'] = -452.30, 
            ['Z'] = 35.90
        },
    },
    [2] = {
        ['Prop'] = 'v_ind_cf_flour',
        ['Coords'] = {
            ['X'] = -1421.86, 
            ['Y'] = -456.52, 
            ['Z'] = 35.90
        },
    },
    [3] = {
        ['Prop'] = 'v_ind_cf_flour',
        ['Coords'] = {
            ['X'] = -1407.10, 
            ['Y'] = -447.41, 
            ['Z'] = 35.90
        },
    },
    [4] = {
        ['Prop'] = 'v_ind_cf_flour',
        ['Coords'] = {
            ['X'] = 1155.26, 
            ['Y'] = -792.33, 
            ['Z'] = 57.40
        },
    },
}

Config.MechanicCrafting = {
    [1] = {
        ['Label'] = 'Koppeling (A)',
        ['ItemName'] = 'clutch-a',
        ['Slot'] = 1,
        ['Amount'] = 10,
        ['Info'] = '',
        ['Weight'] = 1000,
        ['Image'] = 'clutch-a.png',
        ['AddingPoints'] = 0,
        ['PointsNeeded'] = 0,
        ['Cost'] = {
            [1] = {
                ['Label'] = 'Staal',
                ['ItemName'] = 'steel',
                ['Image'] = 'steel.png',
                ['Amount'] = 31,
            },
            [2] = {
                ['Label'] = 'Metaal Schroot',
                ['ItemName'] = 'metalscrap',
                ['Image'] = 'metalscrap.png',
                ['Amount'] = 21,
            },
            [3] = {
                ['Label'] = 'Koper',
                ['ItemName'] = 'copper',
                ['Image'] = 'copper.png',
                ['Amount'] = 15,
            },
        },
    },
    [2] = {
        ['Label'] = 'Koppeling (B)',
        ['ItemName'] = 'clutch-b',
        ['Slot'] = 2,
        ['Amount'] = 10,
        ['Info'] = '',
        ['Weight'] = 450,
        ['Image'] = 'clutch-b.png',
        ['AddingPoints'] = 0,
        ['PointsNeeded'] = 0,
        ['Cost'] = {
            [1] = {
                ['Label'] = 'Staal',
                ['ItemName'] = 'steel',
                ['Image'] = 'steel.png',
                ['Amount'] = 33,
            },
            [2] = {
                ['Label'] = 'Metaal Schroot',
                ['ItemName'] = 'metalscrap',
                ['Image'] = 'metalscrap.png',
                ['Amount'] = 40,
            },
            [3] = {
                ['Label'] = 'Koper',
                ['ItemName'] = 'copper',
                ['Image'] = 'copper.png',
                ['Amount'] = 25,
            },
        },
    },
    [3] = {
        ['Label'] = 'Koppeling (S)',
        ['ItemName'] = 'clutch-s',
        ['Slot'] = 3,
        ['Amount'] = 10,
        ['Info'] = '',
        ['Weight'] = 1000,
        ['Image'] = 'clutch-s.png',
        ['AddingPoints'] = 0,
        ['PointsNeeded'] = 0,
        ['Cost'] = {
            [1] = {
                ['Label'] = 'Staal',
                ['ItemName'] = 'steel',
                ['Image'] = 'steel.png',
                ['Amount'] = 46,
            },
            [2] = {
                ['Label'] = 'Metaal Schroot',
                ['ItemName'] = 'metalscrap',
                ['Image'] = 'metalscrap.png',
                ['Amount'] = 64,
            },
            [3] = {
                ['Label'] = 'Koper',
                ['ItemName'] = 'copper',
                ['Image'] = 'copper.png',
                ['Amount'] = 35,
            },
        },
    },
    [4] = {
        ['Label'] = 'Aandrijfas (A)',
        ['ItemName'] = 'axle-a',
        ['Slot'] = 4,
        ['Amount'] = 10,
        ['Info'] = '',
        ['Weight'] = 1000,
        ['Image'] = 'axle-a.png',
        ['AddingPoints'] = 0,
        ['PointsNeeded'] = 0,
        ['Cost'] = {
            [1] = {
                ['Label'] = 'Staal',
                ['ItemName'] = 'steel',
                ['Image'] = 'steel.png',
                ['Amount'] = 31,
            },
            [2] = {
                ['Label'] = 'Metaal Schroot',
                ['ItemName'] = 'metalscrap',
                ['Image'] = 'metalscrap.png',
                ['Amount'] = 21,
            },
            [3] = {
                ['Label'] = 'Koper',
                ['ItemName'] = 'copper',
                ['Image'] = 'copper.png',
                ['Amount'] = 15,
            },
        },
    },
    [5] = {
        ['Label'] = 'Aandrijfas (B)',
        ['ItemName'] = 'axle-b',
        ['Slot'] = 5,
        ['Amount'] = 10,
        ['Info'] = '',
        ['Weight'] = 1000,
        ['Image'] = 'axle-b.png',
        ['AddingPoints'] = 0,
        ['PointsNeeded'] = 0,
        ['Cost'] = {
            [1] = {
                ['Label'] = 'Staal',
                ['ItemName'] = 'steel',
                ['Image'] = 'steel.png',
                ['Amount'] = 33,
            },
            [2] = {
                ['Label'] = 'Metaal Schroot',
                ['ItemName'] = 'metalscrap',
                ['Image'] = 'metalscrap.png',
                ['Amount'] = 40,
            },
            [3] = {
                ['Label'] = 'Koper',
                ['ItemName'] = 'copper',
                ['Image'] = 'copper.png',
                ['Amount'] = 25,
            },
        },
    },
    [6] = {
        ['Label'] = 'Aandrijfas (S)',
        ['ItemName'] = 'axle-s',
        ['Slot'] = 6,
        ['Amount'] = 10,
        ['Info'] = '',
        ['Weight'] = 1000,
        ['Image'] = 'axle-s.png',
        ['AddingPoints'] = 0,
        ['PointsNeeded'] = 0,
        ['Cost'] = {
            [1] = {
                ['Label'] = 'Staal',
                ['ItemName'] = 'steel',
                ['Image'] = 'steel.png',
                ['Amount'] = 46,
            },
            [2] = {
                ['Label'] = 'Metaal Schroot',
                ['ItemName'] = 'metalscrap',
                ['Image'] = 'metalscrap.png',
                ['Amount'] = 64,
            },
            [3] = {
                ['Label'] = 'Koper',
                ['ItemName'] = 'copper',
                ['Image'] = 'copper.png',
                ['Amount'] = 35,
            },
        },
    },
    [7] = {
        ['Label'] = 'Remmen (A)',
        ['ItemName'] = 'brakes-a',
        ['Slot'] = 7,
        ['Amount'] = 10,
        ['Info'] = '',
        ['Weight'] = 1000,
        ['Image'] = 'brakes-a.png',
        ['AddingPoints'] = 0,
        ['PointsNeeded'] = 0,
        ['Cost'] = {
            [1] = {
                ['Label'] = 'Staal',
                ['ItemName'] = 'steel',
                ['Image'] = 'steel.png',
                ['Amount'] = 31,
            },
            [2] = {
                ['Label'] = 'Metaal Schroot',
                ['ItemName'] = 'metalscrap',
                ['Image'] = 'metalscrap.png',
                ['Amount'] = 21,
            },
            [3] = {
                ['Label'] = 'Koper',
                ['ItemName'] = 'copper',
                ['Image'] = 'copper.png',
                ['Amount'] = 15,
            },
        },
    },
    [8] = {
        ['Label'] = 'Remmen (B)',
        ['ItemName'] = 'brakes-b',
        ['Slot'] = 8,
        ['Amount'] = 10,
        ['Info'] = '',
        ['Weight'] = 1000,
        ['Image'] = 'brakes-b.png',
        ['AddingPoints'] = 0,
        ['PointsNeeded'] = 0,
        ['Cost'] = {
            [1] = {
                ['Label'] = 'Staal',
                ['ItemName'] = 'steel',
                ['Image'] = 'steel.png',
                ['Amount'] = 33,
            },
            [2] = {
                ['Label'] = 'Metaal Schroot',
                ['ItemName'] = 'metalscrap',
                ['Image'] = 'metalscrap.png',
                ['Amount'] = 40,
            },
            [3] = {
                ['Label'] = 'Koper',
                ['ItemName'] = 'copper',
                ['Image'] = 'copper.png',
                ['Amount'] = 25,
            },
        },
    },
    [9] = {
        ['Label'] = 'Remmen (S)',
        ['ItemName'] = 'brakes-s',
        ['Slot'] = 9,
        ['Amount'] = 10,
        ['Info'] = '',
        ['Weight'] = 1000,
        ['Image'] = 'brakes-s.png',
        ['AddingPoints'] = 0,
        ['PointsNeeded'] = 0,
        ['Cost'] = {
            [1] = {
                ['Label'] = 'Staal',
                ['ItemName'] = 'steel',
                ['Image'] = 'steel.png',
                ['Amount'] = 46,
            },
            [2] = {
                ['Label'] = 'Metaal Schroot',
                ['ItemName'] = 'metalscrap',
                ['Image'] = 'metalscrap.png',
                ['Amount'] = 64,
            },
            [3] = {
                ['Label'] = 'Koper',
                ['ItemName'] = 'copper',
                ['Image'] = 'copper.png',
                ['Amount'] = 35,
            },
        },
    },
    [10] = {
        ['Label'] = 'Motor (A)',
        ['ItemName'] = 'engine-a',
        ['Slot'] = 10,
        ['Amount'] = 10,
        ['Info'] = '',
        ['Weight'] = 1000,
        ['Image'] = 'engine-a.png',
        ['AddingPoints'] = 0,
        ['PointsNeeded'] = 0,
        ['Cost'] = {
            [1] = {
                ['Label'] = 'Staal',
                ['ItemName'] = 'steel',
                ['Image'] = 'steel.png',
                ['Amount'] = 31,
            },
            [2] = {
                ['Label'] = 'Metaal Schroot',
                ['ItemName'] = 'metalscrap',
                ['Image'] = 'metalscrap.png',
                ['Amount'] = 21,
            },
            [3] = {
                ['Label'] = 'Koper',
                ['ItemName'] = 'copper',
                ['Image'] = 'copper.png',
                ['Amount'] = 15,
            },
        },
    },
    [11] = {
        ['Label'] = 'Motor (B)',
        ['ItemName'] = 'engine-b',
        ['Slot'] = 11,
        ['Amount'] = 10,
        ['Info'] = '',
        ['Weight'] = 1000,
        ['Image'] = 'engine-b.png',
        ['AddingPoints'] = 0,
        ['PointsNeeded'] = 0,
        ['Cost'] = {
            [1] = {
                ['Label'] = 'Staal',
                ['ItemName'] = 'steel',
                ['Image'] = 'steel.png',
                ['Amount'] = 33,
            },
            [2] = {
                ['Label'] = 'Metaal Schroot',
                ['ItemName'] = 'metalscrap',
                ['Image'] = 'metalscrap.png',
                ['Amount'] = 40,
            },
            [3] = {
                ['Label'] = 'Koper',
                ['ItemName'] = 'copper',
                ['Image'] = 'copper.png',
                ['Amount'] = 25,
            },
        },
    },
    [12] = {
        ['Label'] = 'Motor (S)',
        ['ItemName'] = 'engine-s',
        ['Slot'] = 12,
        ['Amount'] = 10,
        ['Info'] = '',
        ['Weight'] = 1000,
        ['Image'] = 'engine-s.png',
        ['AddingPoints'] = 0,
        ['PointsNeeded'] = 0,
        ['Cost'] = {
            [1] = {
                ['Label'] = 'Staal',
                ['ItemName'] = 'steel',
                ['Image'] = 'steel.png',
                ['Amount'] = 46,
            },
            [2] = {
                ['Label'] = 'Metaal Schroot',
                ['ItemName'] = 'metalscrap',
                ['Image'] = 'metalscrap.png',
                ['Amount'] = 64,
            },
            [3] = {
                ['Label'] = 'Koper',
                ['ItemName'] = 'copper',
                ['Image'] = 'copper.png',
                ['Amount'] = 35,
            },
        },
    },
    [13] = {
        ['Label'] = 'Injectoren (A)',
        ['ItemName'] = 'injectors-a',
        ['Slot'] = 13,
        ['Amount'] = 10,
        ['Info'] = '',
        ['Weight'] = 1000,
        ['Image'] = 'injectors-a.png',
        ['AddingPoints'] = 0,
        ['PointsNeeded'] = 0,
        ['Cost'] = {
            [1] = {
                ['Label'] = 'Staal',
                ['ItemName'] = 'steel',
                ['Image'] = 'steel.png',
                ['Amount'] = 31,
            },
            [2] = {
                ['Label'] = 'Metaal Schroot',
                ['ItemName'] = 'metalscrap',
                ['Image'] = 'metalscrap.png',
                ['Amount'] = 21,
            },
            [3] = {
                ['Label'] = 'Koper',
                ['ItemName'] = 'copper',
                ['Image'] = 'copper.png',
                ['Amount'] = 15,
            },
        },
    },
    [14] = {
        ['Label'] = 'Injectoren (B)',
        ['ItemName'] = 'injectors-b',
        ['Slot'] = 14,
        ['Amount'] = 10,
        ['Info'] = '',
        ['Weight'] = 1000,
        ['Image'] = 'injectors-b.png',
        ['AddingPoints'] = 0,
        ['PointsNeeded'] = 0,
        ['Cost'] = {
            [1] = {
                ['Label'] = 'Staal',
                ['ItemName'] = 'steel',
                ['Image'] = 'steel.png',
                ['Amount'] = 33,
            },
            [2] = {
                ['Label'] = 'Metaal Schroot',
                ['ItemName'] = 'metalscrap',
                ['Image'] = 'metalscrap.png',
                ['Amount'] = 40,
            },
            [3] = {
                ['Label'] = 'Koper',
                ['ItemName'] = 'copper',
                ['Image'] = 'copper.png',
                ['Amount'] = 25,
            },
        },
    },
    [15] = {
        ['Label'] = 'Injectoren (S)',
        ['ItemName'] = 'injectors-s',
        ['Slot'] = 15,
        ['Amount'] = 10,
        ['Info'] = '',
        ['Weight'] = 1000,
        ['Image'] = 'injectors-s.png',
        ['AddingPoints'] = 0,
        ['PointsNeeded'] = 0,
        ['Cost'] = {
            [1] = {
                ['Label'] = 'Staal',
                ['ItemName'] = 'steel',
                ['Image'] = 'steel.png',
                ['Amount'] = 46,
            },
            [2] = {
                ['Label'] = 'Metaal Schroot',
                ['ItemName'] = 'metalscrap',
                ['Image'] = 'metalscrap.png',
                ['Amount'] = 64,
            },
            [3] = {
                ['Label'] = 'Koper',
                ['ItemName'] = 'copper',
                ['Image'] = 'copper.png',
                ['Amount'] = 35,
            },
        },
    },
    [16] = {
        ['Label'] = 'Transmissie (A)',
        ['ItemName'] = 'transmission-a',
        ['Slot'] = 16,
        ['Amount'] = 10,
        ['Info'] = '',
        ['Weight'] = 1000,
        ['Image'] = 'transmission-a.png',
        ['AddingPoints'] = 0,
        ['PointsNeeded'] = 0,
        ['Cost'] = {
            [1] = {
                ['Label'] = 'Staal',
                ['ItemName'] = 'steel',
                ['Image'] = 'steel.png',
                ['Amount'] = 31,
            },
            [2] = {
                ['Label'] = 'Metaal Schroot',
                ['ItemName'] = 'metalscrap',
                ['Image'] = 'metalscrap.png',
                ['Amount'] = 21,
            },
            [3] = {
                ['Label'] = 'Koper',
                ['ItemName'] = 'copper',
                ['Image'] = 'copper.png',
                ['Amount'] = 15,
            },
        },
    },
    [17] = {
        ['Label'] = 'Transmissie (B)',
        ['ItemName'] = 'transmission-b',
        ['Slot'] = 17,
        ['Amount'] = 10,
        ['Info'] = '',
        ['Weight'] = 1000,
        ['Image'] = 'transmission-b.png',
        ['AddingPoints'] = 0,
        ['PointsNeeded'] = 0,
        ['Cost'] = {
            [1] = {
                ['Label'] = 'Staal',
                ['ItemName'] = 'steel',
                ['Image'] = 'steel.png',
                ['Amount'] = 33,
            },
            [2] = {
                ['Label'] = 'Metaal Schroot',
                ['ItemName'] = 'metalscrap',
                ['Image'] = 'metalscrap.png',
                ['Amount'] = 40,
            },
            [3] = {
                ['Label'] = 'Koper',
                ['ItemName'] = 'copper',
                ['Image'] = 'copper.png',
                ['Amount'] = 25,
            },
        },
    },
    [18] = {
        ['Label'] = 'Transmissie (S)',
        ['ItemName'] = 'transmission-s',
        ['Slot'] = 18,
        ['Amount'] = 10,
        ['Info'] = '',
        ['Weight'] = 1000,
        ['Image'] = 'transmission-s.png',
        ['AddingPoints'] = 0,
        ['PointsNeeded'] = 0,
        ['Cost'] = {
            [1] = {
                ['Label'] = 'Staal',
                ['ItemName'] = 'steel',
                ['Image'] = 'steel.png',
                ['Amount'] = 46,
            },
            [2] = {
                ['Label'] = 'Metaal Schroot',
                ['ItemName'] = 'metalscrap',
                ['Image'] = 'metalscrap.png',
                ['Amount'] = 64,
            },
            [3] = {
                ['Label'] = 'Koper',
                ['ItemName'] = 'copper',
                ['Image'] = 'copper.png',
                ['Amount'] = 35,
            },
        },
    },
    [19] = {
        ['Label'] = 'Repareer Kist',
        ['ItemName'] = 'big-repair',
        ['Slot'] = 19,
        ['Amount'] = 10,
        ['Info'] = '',
        ['Weight'] = 1000,
        ['Image'] = 'big-repair.png',
        ['AddingPoints'] = 0,
        ['PointsNeeded'] = 0,
        ['Cost'] = {
            [1] = {
                ['Label'] = 'Staal',
                ['ItemName'] = 'steel',
                ['Image'] = 'steel.png',
                ['Amount'] = 52,
            },
            [2] = {
                ['Label'] = 'Metaal Schroot',
                ['ItemName'] = 'metalscrap',
                ['Image'] = 'metalscrap.png',
                ['Amount'] = 50,
            },
            [3] = {
                ['Label'] = 'Koper',
                ['ItemName'] = 'copper',
                ['Image'] = 'copper.png',
                ['Amount'] = 41,
            },
            [4] = {
                ['Label'] = 'Rubber',
                ['ItemName'] = 'rubber',
                ['Image'] = 'rubber.png',
                ['Amount'] = 12,
            },
        },
    },
}