Config = Config or {}

Config.PedInteraction = {
    [1] = {
        ['Type'] = 'Toolshop',
        ['Model'] = 's_m_m_gardener_01',
        ['Animation'] = "WORLD_HUMAN_CLIPBOARD",
        ['InteractAnimation'] = nil,
        ['Coords'] = vector3(170.00, -1799.54, 29.31),
        ['Heading'] = 315.65,
        ['CurrentPedNumber'] = nil,
    },
    [2] = {
        ['Type'] = 'Toolshop',
        ['Model'] = 's_m_m_gardener_01',
        ['Animation'] = "WORLD_HUMAN_CLIPBOARD",
        ['InteractAnimation'] = nil,
        ['Coords'] = vector3(46.45, -1749.53, 29.63),
        ['Heading'] = 43.75,
        ['CurrentPedNumber'] = nil,
    },
    [3] = {
        ['Type'] = 'Toolshop',
        ['Model'] = 's_m_m_gardener_01',
        ['Animation'] = "WORLD_HUMAN_CLIPBOARD",
        ['InteractAnimation'] = nil,
        ['Coords'] = vector3(2748.08, 3472.64, 55.67),
        ['Heading'] = 245.64,
        ['CurrentPedNumber'] = nil,
    },
    [4] = {
        ['Type'] = 'Main-Bank',
        ['Model'] = 's_m_m_highsec_02',
        ['Animation'] = "WORLD_HUMAN_CLIPBOARD",
        ['InteractAnimation'] = nil,
        ['Coords'] = vector3(241.35, 225.22, 106.28),
        ['Heading'] = 161.56,
        ['CurrentPedNumber'] = nil,
    },
    [5] = {
        ['Type'] = 'Fisher',
        ['Model'] = 'a_f_m_prolhost_01',
        ['Animation'] = "",
        ['InteractAnimation'] = nil,
        ['Coords'] = vector3(-1686.35, -1072.63, 13.15),
        ['Heading'] = 52.82,
        ['CurrentPedNumber'] = nil,
    },
    [6] = {
        ['Type'] = 'Electronics', -- Nakijken
        ['Model'] = 'a_m_m_bevhills_02',
        ['Animation'] = "WORLD_HUMAN_CLIPBOARD",
        ['InteractAnimation'] = nil,
        ['Coords'] = vector3(1137.4436, -470.8099, 66.658241),
        ['Heading'] = 255.98715,
        ['CurrentPedNumber'] = nil,
    },
    [7] = {
        ['Type'] = 'Oxy',
        ['Model'] = 'a_m_m_soucent_03',
        ['Animation'] = "",
        ['InteractAnimation'] = nil,
        ['Coords'] = vector3(745.35, -482.39, 26.29),
        ['Heading'] = 215.44,
        ['CurrentPedNumber'] = nil,
    },
    -- [8] = {
    --     ['Type'] = 'Rental',
    --     ['Model'] = 'a_m_m_eastsa_02',
    --     ['Animation'] = "",
    --     ['InteractAnimation'] = nil,
    --     ['Coords'] = vector3(-516.89, -211.0, 38.17),
    --     ['Heading'] = 119.88,
    --     ['CurrentPedNumber'] = nil,
    -- },
    [8] = {
        ['Type'] = 'Secret-Sell',
        ['Model'] = 'a_f_m_ktown_02',
        ['Animation'] = "",
        ['InteractAnimation'] = nil,
        ['Coords'] = vector3(-1846.87, -1190.70, 14.32),
        ['Heading'] = 149.82,
        ['CurrentPedNumber'] = nil,
    },
    -- [10] = {
    --     ['Type'] = 'Casino-Shit',
    --     ['Model'] = 'u_f_m_casinocash_01',
    --     ['Animation'] = "",
    --     ['InteractAnimation'] = nil,
    --     ['Coords'] = vector3(1117.25, 220.03, -49.43),
    --     ['Heading'] = 88.73,
    --     ['CurrentPedNumber'] = nil,
    -- },
    -- [11] = {
    --     ['Type'] = 'Casino-Shit',
    --     ['Model'] = 'u_f_m_casinocash_01',
    --     ['Animation'] = "",
    --     ['InteractAnimation'] = nil,
    --     ['Coords'] = vector3(1117.25, 220.03, -49.43),
    --     ['Heading'] = 88.73,
    --     ['CurrentPedNumber'] = nil,
    -- },
    [9] = {
        ['Type'] = 'HouseRob',
        ['Model'] = 'a_f_y_vinewood_02',
        ['Animation'] = "",
        ['InteractAnimation'] = nil,
        ['Coords'] = vector3(230.46133, -1678.455, 29.692182),
        ['Heading'] = 60.417133,
        ['CurrentPedNumber'] = nil,
    },
    -- [13] = {
    --     ['Type'] = 'SellWeed',
    --     ['Model'] = 'a_m_m_farmer_01',
    --     ['Animation'] = "",
    --     ['InteractAnimation'] = nil,
    --     ['Coords'] = vector3(166.99, 2229.06, 90.78),
    --     ['Heading'] = 56.10,
    --     ['CurrentPedNumber'] = nil,
    -- },
    -- [10] = {
    --     ['Type'] = 'Pilot',
    --     ['Model'] = 's_m_m_pilot_01',
    --     ['Animation'] = "",
    --     ['InteractAnimation'] = nil,
    --     ['Coords'] = vector3(-941.05, -2954.26, 13.94),
    --     ['Heading'] = 149.30,
    --     ['CurrentPedNumber'] = nil,
    -- },
    [10] = {
        ['Type'] = 'BarsSell',
        ['Model'] = 'g_m_m_mexboss_01',
        ['Animation'] = "",
        ['InteractAnimation'] = nil,
        ['Coords'] = vector3(-108.5026, 6338.9946, 35.500743), -- vector3(173.93968, -1323.255, 29.363597) nieuwe
        ['Heading'] = 234.91,
        ['CurrentPedNumber'] = nil,
    },
    [11] = {
        ['Type'] = 'HuntingSell',
        ['Model'] = 's_m_m_ammucountry',
        ['Animation'] = "",
        ['InteractAnimation'] = nil,
        ['Coords'] = vector3(-62.01726, 6238.3906, 31.090066),
        ['Heading'] = 59.835063,
        ['CurrentPedNumber'] = nil,
    },
    [12] = {
        ['Type'] = 'OtherSell',
        ['Model'] = 'mp_m_waremech_01',
        ['Animation'] = "",
        ['InteractAnimation'] = nil,
        ['Coords'] = vector3(-1210.425, -1311.572, -27.64029),
        ['Heading'] = 336,
        ['CurrentPedNumber'] = nil,
    },
    [13] = {
        ['Type'] = 'Pickaxe',
        ['Model'] = 'ig_old_man2',
        ['Animation'] = "",
        ['InteractAnimation'] = nil,
        ['Coords'] = vector3(-595.12, 2091.35, 131.46),
        ['Heading'] = 57.67,
        ['CurrentPedNumber'] = nil,
    },
    [14] = {
        ['Type'] = 'WoodSell',
        ['Model'] = 'a_m_y_vinewood_03',
        ['Animation'] = "",
        ['InteractAnimation'] = nil,
        ['Coords'] = vector3(1901.72, 4924.6757, 48.849727),
        ['Heading'] = 160.0,
        ['CurrentPedNumber'] = nil,
    },
    [15] = {
        ['Type'] = 'VehicleSell',
        ['Model'] = 'a_m_y_vinewood_01',
        ['Animation'] = "",
        ['InteractAnimation'] = nil,
        ['Coords'] = vector3(-211.222, -1998.911, 27.755413),
        ['Heading'] = 268.40112,
        ['CurrentPedNumber'] = nil,
    },
    [16] = {
        ['Type'] = 'Weed',
        ['Model'] = 'a_m_m_farmer_01',
        ['Animation'] = "",
        ['InteractAnimation'] = nil,
        ['Coords'] = vector3(187.09062, -250.1156, 54.070537),
        ['Heading'] = 303.68185,
        ['CurrentPedNumber'] = nil,
    },
}