Shared = Shared or {}

Shared.ItemList = {
    ["weapon_fireextinguisher"] = {
		["name"] = "weapon_fireextinguisher", 		
		["label"] = "Brandblusser", 			
		["weight"] = 1000,
		["type"] = "weapon",	
		['ismetal'] = true,  
		['melee'] = false,
		["image"] = "fireext.png",   	
		["unique"] = true, 		
		["combinable"] = nil, 
		["description"] = "Een blusser voor brand?",
	},
	-- // Pistols \\ --
	["weapon_stungun"] = {
		["name"] = "weapon_stungun", 				
		["label"] = "Taser X4", 				
		["weight"] = 5000,       
		["type"] = "weapon", 	
		['ismetal'] = true, 
		['melee'] = false,
		["image"] = "stungun.png", 	      
		["unique"] = true, 		
		["combinable"] = nil, 
		["description"] = "Een politie taser.",
	},
	["weapon_combatpistol"] = {
		["name"] = "weapon_combatpistol", 			
		["label"] = "Beretta M9", 				
		["weight"] = 7000, 
		["type"] = "weapon", 	
		['ismetal'] = true, 
		['melee'] = false,
		["image"] = "beretta.png",   
		["unique"] = true, 		
		["combinable"] = nil,
		["description"] = "Een pittig pistooltje wel hoor."
	},
	["weapon_ceramicpistol"] = {
		["name"] = "weapon_ceramicpistol", 			
		["label"] = "Keramisch Pistool", 				
		["weight"] = 7000, 
		["type"] = "weapon", 	
		['ismetal'] = true, 
		['melee'] = false,
		["image"] = "ceramic.png",   
		["unique"] = true, 		
		["combinable"] = nil,
		["description"] = "Heerluk keramisch.."
	},
	["weapon_pistol"] = {
		["name"] = "weapon_pistol", 				
		["label"] = "Colt M1911", 				
		["weight"] = 7000, 		
		["type"] = "weapon", 	
		['ismetal'] = true, 
		['melee'] = false,
		["image"] = "colt.png", 	  	  
		["unique"] = true, 		
		["combinable"] = nil, 
		["description"] = "Volgensmij komt deze direct uit call of duty."
	},
	["weapon_pistol_mk2"] = {
		["name"] = "weapon_pistol_mk2", 			
		["label"] = "Walther P99Q", 			
		["weight"] = 7000,     
		["type"] = "weapon", 	
		['ismetal'] = true, 
		['melee'] = false,
		["image"] = "pistol.png", 	  	  
		["unique"] = true, 		
		["combinable"] = nil, 
		["description"] = "Een politie vuurwapen."
	},
	["weapon_snspistol_mk2"] = {
		["name"] = "weapon_snspistol_mk2", 			
		["label"] = "Sns Pistool", 				
		["weight"] = 5000, 
		["type"] = "weapon", 	
		['ismetal'] = true, 
		['melee'] = false,
		["image"] = "snspistol.png", 	  
		["unique"] = true, 		
		["combinable"] = nil, 
		["description"] = "De opvolger van de ewrten schieter alleen dan beter."
	},
	["weapon_heavypistol"] = {
		["name"] = "weapon_heavypistol", 			
		["label"] = "Zwaar Pistool", 			
		["weight"] = 12000, 	
		["type"] = "weapon", 	
		['ismetal'] = true, 
		['melee'] = false,
		["image"] = "heavypistol.png", 	  
		["unique"] = true, 		
		["combinable"] = nil, 
		["description"] = "Een tering zwaar pistool."
	},
	["weapon_vintagepistol"] = {
		["name"] = "weapon_vintagepistol", 		    
		["label"] = "Klassiek Pistool", 			
		["weight"] = 7500,    	
		["type"] = "weapon", 	
		['ismetal'] = true, 
		['melee'] = false,
		["image"] = "vintage.png", 	      
		["unique"] = true, 		
		["combinable"] = nil, 
		["description"] = "Een echt klassiek pistooltje."
	},
	["weapon_navyrevolver"] = {
		["name"] = "weapon_navyrevolver", 		    
		["label"] = "Navy Revolver", 			
		["weight"] = 7500,    	
		["type"] = "weapon", 	
		['ismetal'] = true, 
		['melee'] = false,
		["image"] = "navy.png", 	      
		["unique"] = true, 		
		["combinable"] = nil, 
		["description"] = "Een mooi ding."
	},
	-- // SMG Pistols \\ --
	["weapon_machinepistol"] = {
		["name"] = "weapon_machinepistol", 		    
		["label"] = "Machine Pistool", 			
		["weight"] = 12000, 	
		['melee'] = false,      
		["type"] = "weapon", 	
		['ismetal'] = true, 
		["image"] = "machine.png", 	      
		["unique"] = true, 
		["combinable"] = nil, 
		["description"] = "Rattatatatataaaaaa."
	},
	["weapon_microsmg"] = {
		["name"] = "weapon_microsmg", 			    
		["label"] = "Micro SMG", 			    
		["weight"] = 15500, 	
		['melee'] = false,      
		["type"] = "weapon", 	
		['ismetal'] = true, 
		["image"] = "micro.png", 	 	  
		["unique"] = true, 
		["combinable"] = nil,
		["description"] = "Ben ik in de bijlmer ofzo?"
	},
	["weapon_microsmg2"] = {
		["name"] = "weapon_microsmg2", 			    
		["label"] = "Uzi", 			    
		["weight"] = 13500, 	
		['melee'] = false,      
		["type"] = "weapon", 	
		['ismetal'] = true, 
		["image"] = "uzi.png", 	 	  
		["unique"] = true, 
		["combinable"] = nil,
		["description"] = "Wow kiek es aan!"
	},
	["weapon_microsmg3"] = {
		["name"] = "weapon_microsmg3", 			    
		["label"] = "Mac-10", 			    
		["weight"] = 13500, 	
		['melee'] = false,      
		["type"] = "weapon", 	
		['ismetal'] = true, 
		["image"] = "mac10.png", 	 	  
		["unique"] = true, 
		["combinable"] = nil,
		["description"] = "Praaapraaa pra pra pra.."
	},
	["weapon_appistol"] = {
		["name"] = "weapon_appistol", 			    
		["label"] = "AP Pistool", 			    
		["weight"] = 12000, 	
		['melee'] = false,      
		["type"] = "weapon", 	
		['ismetal'] = true, 
		["image"] = "appistol.png", 	  
		["unique"] = true, 
		["combinable"] = nil, 
		["description"] = "Poah wat een vuur kracht."
	},
	["weapon_browning"] = {
		["name"] = "weapon_browning", 			    
		["label"] = "Browning Pistool", 			    
		["weight"] = 11500, 	
		['melee'] = false,      
		["type"] = "weapon", 	
		['ismetal'] = true, 
		["image"] = "browning.png", 	  
		["unique"] = true, 
		["combinable"] = nil, 
		["description"] = "Dit is echt een geil wapen zeg."
	},
	["weapon_gusenberg"] = {
		["name"] = "weapon_gusenberg", 			    
		["label"] = "Tommy Gun", 			    
		["weight"] = 12000, 	
		['melee'] = false,      
		["type"] = "weapon", 	
		['ismetal'] = true, 
		["image"] = "tommy.png", 	  	  
		["unique"] = true, 
		["combinable"] = nil, 
		["description"] = "Das een groot ding."
	},
	-- // Shothguns \\ --[
	["weapon_sawnoffshotgun"] = {
		["name"] = "weapon_sawnoffshotgun", 		
		["label"] = "Korte Shotgun", 			
		["weight"] = 15500, 	
		['melee'] = false,      
		["type"] = "weapon", 	
		['ismetal'] = true, 
		["image"] = "sawnoff.png", 	      
		["unique"] = true, 
		["combinable"] = nil, 
		["description"] = "Dit is het echte werk."
	},
	-- // Rifles \\ --
	["weapon_m4"] = {
		["name"] = "weapon_m4", 		
		["label"] = "M4",	 		
		["weight"] = 17000, 	
		['melee'] = false,      
		["type"] = "weapon", 	
		['ismetal'] = true, 
		["image"] = "m4.png", 	  
		["unique"] = true, 
		["combinable"] = nil, 
		["description"] = "Zoutig politie wapen."
	},
	["weapon_assaultrifle"] = {
		["name"] = "weapon_assaultrifle", 			
		["label"] = "AK-47",	 				
		["weight"] = 17000, 	
		['melee'] = false,      
		["type"] = "weapon", 	
		['ismetal'] = true, 
		["image"] = "assaultrifle.png",   
		["unique"] = true, 
		["combinable"] = nil, 
		["description"] = "Ak's in the back."
	},
	["weapon_assaultrifle2"] = {
		["name"] = "weapon_assaultrifle2", 			
		["label"] = "M70",	 				
		["weight"] = 17000, 	
		['melee'] = false,      
		["type"] = "weapon", 	
		['ismetal'] = true, 
		["image"] = "m70.png",   
		["unique"] = true, 
		["combinable"] = nil, 
		["description"] = "Dit is volgensmij geen ak?"
	},
	["weapon_sniperrifle2"] = {
		["name"] = "weapon_sniperrifle2", 			
		["label"] = "Jacht Geweer",	 			
		["weight"] = 17000, 	
		['melee'] = false,      
		["type"] = "weapon", 	
		['ismetal'] = true, 
		["image"] = "huntingrifle.png",   
		["unique"] = true, 
		["combinable"] = nil, 
		["description"] = "Gaan we jagen?"
	},
	["weapon_snspistol"] = {
		["name"] = "weapon_snspistol", 		 		
		["label"] = "Paintball Gun", 					
		["weight"] = 4550, 		
		['melee'] = true,       
		["type"] = "weapon", 	
		['ismetal'] = true, 
		["image"] = "paintball.png",   	  
		["unique"] = true, 
		["combinable"] = nil, 
		["description"] = "Met verf schieten joh."
	},
	-- // Melee \\ --[
	["weapon_knuckle"] = {
		["name"] = "weapon_knuckle", 		 	  	
		["label"] = "Boksbeugel", 				
		["weight"] = 1000, 		
		['melee'] = true,       
		["type"] = "weapon", 	
		['ismetal'] = true,	
		["image"] = "knuckle.png", 		  
		["unique"] = true, 
		["combinable"] = nil, 
		["description"] = "Lekker beugeltje hoor!"
	},
	["weapon_nightstick"] = {
		["name"] = "weapon_nightstick", 			
		["label"] = "Politie Baton", 			
		["weight"] = 3000,	 	
		['melee'] = true,       
		["type"] = "weapon", 	
		['ismetal'] = true, 
		["image"] = "baton.png", 		  
		["unique"] = true, 
		["combinable"] = nil, 
		["description"] = "Een politie baton."
	},
	["weapon_flashlight"] = {
		["name"] = "weapon_flashlight", 			
		["label"] = "Zaklamp", 					
		["weight"] = 1350,	 	
		['melee'] = true,       
		["type"] = "weapon", 	
		['ismetal'] = true, 
		["image"] = "flashlight.png", 	  
		["unique"] = true, 
		["combinable"] = nil, 
		["description"] = "Schijn een lichtje op mij."
	},
	["weapon_hatchet"] = {
		["name"] = "weapon_hatchet", 		 	  	
		["label"] = "Hakbijl", 					
		["weight"] = 4750, 		
		['melee'] = true,       
		["type"] = "weapon", 	
		['ismetal'] = true, 
		["image"] = "hatchet.png", 		  
		["unique"] = true, 
		["combinable"] = nil, 
		["description"] = "Om hout mee te hakken of iets anders."
	},
	["weapon_switchblade"] = {
		["name"] = "weapon_switchblade", 	 	  	
		["label"] = "Klapmes", 				
		["weight"] = 4750, 		
		['melee'] = true,       
		["type"] = "weapon", 	
		['ismetal'] = true, 
		["image"] = "switchblade.png",	  
		["unique"] = true, 
		["combinable"] = nil, 
		["description"] = "Een KLAP mes."
	},
	["weapon_knife"] = {
		["name"] = "weapon_knife", 	 	  			
		["label"] = "Keuken Mes", 				
		["weight"] = 4750, 		
		['melee'] = true,       
		["type"] = "weapon", 	
		['ismetal'] = true, 
		["image"] = "wknife.png",	 	  
		["unique"] = true, 
		["combinable"] = nil, 
		["description"] = "Een mes."
	},
	["weapon_machete"] = {
		["name"] = "weapon_machete", 			 	
		["label"] = "Machete", 					
		["weight"] = 4750, 		
		['melee'] = true,       
		["type"] = "weapon", 	
		['ismetal'] = true, 
		["image"] = "machete.png",        
		["unique"] = true, 
		["combinable"] = nil, 
		["description"] = "Koppie eraf?"
	},
	["weapon_hammer"] = {
		["name"] = "weapon_hammer", 			 	
		["label"] = "Hamer", 					
		["weight"] = 4750, 		
		['melee'] = true,       
		["type"] = "weapon", 	
		['ismetal'] = true, 
		["image"] = "hammer.png",         
		["unique"] = true, 
		["combinable"] = nil, 
		["description"] = "Hamertje tik spelen?"
	},
	["weapon_wrench"] = {
		["name"] = "weapon_wrench", 			 	
		["label"] = "Moersleutel", 				
		["weight"] = 4750, 		
		['melee'] = true,       
		["type"] = "weapon", 	
		['ismetal'] = true, ["image"] = "wrench.png",         
		["unique"] = true, 
		["combinable"] = nil, 
		["description"] = "Deze sleutel past niet in je broek hoor."
	},
	["weapon_molotov"] = {
		["name"] = "weapon_molotov", 		 		
		["label"] = "Molotov", 					
		["weight"] = 4550, 		
		['melee'] = true,       
		["type"] = "weapon", 	
		['ismetal'] = true, 
		["image"] = "molotov.png", 	      
		["unique"] = true, 
		["combinable"] = nil, 
		["description"] = "Cocktailtje lekker hoor."
	},
	["weapon_flare"] = {
		["name"] = "weapon_flare", 		 		
		["label"] = "Flare", 					
		["weight"] = 4550, 		
		['melee'] = true,       
		["type"] = "weapon", 	
		['ismetal'] = true, 
		["image"] = "flare.png", 	      
		["unique"] = true, 
		["combinable"] = nil, 
		["description"] = "Mooi kleurtje wel."
	},
	["weapon_smokegrenade"] = {
		["name"] = "weapon_smokegrenade", 		 		
		["label"] = "Rook Bom", 					
		["weight"] = 4550, 		
		['melee'] = true,       
		["type"] = "weapon", 	
		['ismetal'] = true, 
		["image"] = "smokegrenade.png", 	      
		["unique"] = true, 
		["combinable"] = nil, 
		["description"] = "Niet inhaleren he."
	},
	["weapon_brick"] = {
		["name"] = "weapon_brick", 		 		
		["label"] = "Steen", 					
		["weight"] = 4550, 		
		['melee'] = true,       
		["type"] = "weapon", 	
		['ismetal'] = true, 
		["image"] = "brick.png",   	  
		["unique"] = true, 
		["combinable"] = nil, 
		["description"] = "Lekker gooien ermee!"
	},
	["weapon_shoe"] = {
		["name"] = "weapon_shoe", 		 		
		["label"] = "Schoenen", 					
		["weight"] = 4550, 		
		['melee'] = true,       
		["type"] = "weapon", 	
		['ismetal'] = true, 
		["image"] = "wshoe.png",   	  
		["unique"] = true, 
		["combinable"] = nil, 
		["description"] = "Poah deze stinken!"
	},
	["weapon_sledgeham"] = {
		["name"] = "weapon_sledgeham", 		 		
		["label"] = "Voorhamer", 				
		["weight"] = 4550, 		
		['melee'] = true,       
		["type"] = "weapon", 	
		['ismetal'] = true, 
		["image"] = "sledgehammer.png",   
		["unique"] = true, 
		["combinable"] = nil, 
		["description"] = "Moker.."
	},
	["weapon_katana"] = {
		["name"] = "weapon_katana", 		 		
		["label"] = "Katana", 					
		["weight"] = 4550, 		
		['melee'] = true,       
		["type"] = "weapon", 	
		['ismetal'] = true, 
		["image"] = "katana.png",   	  
		["unique"] = true, 
		["combinable"] = nil, 
		["description"] = "NAGASAKIIII.."
	},
	["weapon_unicorn"] = {
		["name"] = "weapon_unicorn", 		 		
		["label"] = "Eenhorn Stok", 			
		["weight"] = 4550, 		
		['melee'] = true,       
		["type"] = "weapon", 	
		['ismetal'] = true, 
		["image"] = "unicorn.png",   	  
		["unique"] = true, 
		["combinable"] = nil, 
		["description"] = "Wat is dit betoverend mooi!"
	},
	["weapon_crutch"] = {
		["name"] = "weapon_crutch", 		 		
		["label"] = "Kruk", 					
		["weight"] = 4550, 		
		['melee'] = true,       
		["type"] = "weapon", 	
		['ismetal'] = true, 
		["image"] = "crutch.png",   	  
		["unique"] = true, 
		["combinable"] = nil, 
		["description"] = "Om goed mee te lopen denk ik."
	},
	-- // Ammo \\ --
	["pistol_ammo"] = {
		["name"] = "pistol_ammo", 			 	  	
		["label"] = "Pistool Kogels", 			
		["weight"] = 500, 		
		["type"] = "item", 		
		['ismetal'] = true, 
		["image"] = "ammo-pistol.png", 							  
		["unique"] = false, 
		["combinable"] = nil, 
		["description"] = "Pistool munitie."
	},
	["rifle_ammo"] = {
		["name"] = "rifle_ammo", 			 	  	
		["label"] = "Geweer Kogels", 			
		["weight"] = 700, 		
		["type"] = "item", 		
		['ismetal'] = true, 
		["image"] = "ammo-rifle.png", 							  
		["unique"] = false, 
		["combinable"] = nil, 
		["description"] = "Ik denk dat dit automatische geweer kogels zijn, Weet het alleen niet zeker..."
	},
	["smg_ammo"] = {
		["name"] = "smg_ammo", 			 	  		
		["label"] = "Smg Kogels", 				
		["weight"] = 650, 		
		["type"] = "item", 		
		['ismetal'] = true, 
		["image"] = "ammo-smg.png", 							  
		["unique"] = false, 
		["combinable"] = nil, 
		["description"] = "Semi-Automatische geweer kogels."
	},
	["shotgun_ammo"] = {
		["name"] = "shotgun_ammo", 			 	  	
		["label"] = "Shotgun Shells", 			
		["weight"] = 650, 		
		["type"] = "item", 		
		['ismetal'] = true, 
		["image"] = "ammo-shotgun.png", 						  
		["unique"] = false, 
		["combinable"] = nil, 
		["description"] = "Shotguns Shells."
	},
	["taser_ammo"] = {
		["name"] = "taser_ammo", 			 	  	
		["label"] = "Taser Cartridge", 			
		["weight"] = 650, 		
		["type"] = "item", 		
		['ismetal'] = true, 
		["image"] = "taser-ammo.png", 		    				  
		["unique"] = false, 
		["combinable"] = nil, 
		["description"] = "Pasop dat je geen optater krijgt."
	},
	["paintball_ammo"] = {
		["name"] = "paintball_ammo", 			 	  	
		["label"] = "Paint Balls", 			
		["weight"] = 650, 		
		["type"] = "item", 		
		['ismetal'] = true, 
		["image"] = "paintball-ammo.png", 		    				  
		["unique"] = false, 
		["combinable"] = nil, 
		["description"] = "Balletjes met verf."
	},
	-- // Attatchments \\ --
	["pistol_extendedclip"] = {
		["name"] = "pistol_extendedclip", 			
		["label"] = "Pistool EXT Clip", 		
		["weight"] = 2500, 		
		["type"] = "item", 		
		['ismetal'] = true, 
		["image"] = "pistol_extendedclip.png", 	
		["unique"] = false, 
		["combinable"] = nil,   
		["description"] = "Voor meer kogels denk ik?"
	},
	["pistol_suppressor"] = {
		["name"] = "pistol_suppressor", 			
		["label"] = "Pistool Demper", 		
		["weight"] = 2500, 		
		["type"] = "item", 		
		['ismetal'] = true, 
		["image"] = "pistol_suppressor.png", 	
		["unique"] = false, 
		["combinable"] = nil,   
		["description"] = "Hier zou je niks meer door moeten horen neem ik aan.."
	},
	["smg_extendedclip"] = {
		["name"] = "smg_extendedclip", 				
		["label"] = "SMG EXT Clip", 			
		["weight"] = 3500, 		
		["type"] = "item", 		
		['ismetal'] = true, 
		["image"] = "smg_extendedclip.png", 	
		["unique"] = false, 
		["combinable"] = nil,   
		["description"] = "Voor meer kogels denk ik?"
	},
	-- // Miscs \\ --
	-- // Items \\ --
	["handcuffs"] = {
		["name"] = "handcuffs", 			 	  
		["label"] = "Handboeien", 				
		["weight"] = 1250, 		
		["type"] = "item", 		
		['ismetal'] = true,  
		["image"] = "cuffs.png", 				
		["unique"] = false,     
		["combinable"] = nil,   
		["description"] = "Om stoute stoute dingen mee te doen. (KEKW)"
	},
	["radio"] = {
		["name"] = "radio", 			 	 		
		["label"] = "Portofoon", 				
		["weight"] = 1000, 		
		["type"] = "item", 		
		['ismetal'] = true,  
		["image"] = "porto.png", 				
		["unique"] = false,     
		["combinable"] = nil,   
		["description"] = "Om mee over de ether te praten."
	},
	["camera"] = {
		["name"] = "camera", 			 			
		["label"] = "Foto Camera", 				
		["weight"] = 4500, 		
		["type"] = "item", 		
		['ismetal'] = true,  
		["image"] = "camera.png", 			    
		["unique"] = true,      
		["combinable"] = nil,   
		["description"] = "Oprotten met die camera."
	},
	["police_stormram"] = {
		["name"] = "police_stormram", 			 	
		["label"] = "Stormram", 				
		["weight"] = 7500, 		
		["type"] = "item", 		
		['ismetal'] = true,  
		["image"] = "stormram.png", 			
		["unique"] = false,     
		["combinable"] = nil,   
		["description"] = "Een storm ram om een huis mee in te rammen."
	},
	["keyfob"] = {
		["name"] = "keyfob", 			 			
		["label"] = "Garage Sleutel", 			
		["weight"] = 1250, 		
		["type"] = "item", 		
		['ismetal'] = true,  
		["image"] = "keyfob.png", 				
		["unique"] = true,      
		["combinable"] = nil,   
		["description"] = "Kan je leuk mee spelen."
	},
	["empty_evidence_bag"] = {
		["name"] = "empty_evidence_bag", 			
		["label"] = "Leeg bewijszakje", 		
		["weight"] = 0, 		
		["type"] = "item", 		
		['ismetal'] = false, 
		["image"] = "evidence.png", 			
		["unique"] = false,     
		["combinable"] = nil,   
		["description"] = "Wordt vaak gebruikt om bewijs materiaal in op te slaan. Denk aan DNA van bloed, kogelhulsen of haar etc."
	},
	["filled_evidence_bag"] = {
		["name"] = "filled_evidence_bag", 			
		["label"] = "Bewijszakje", 				
		["weight"] = 200, 		
		["type"] = "item", 		
		['ismetal'] = false, 
		["image"] = "evidence.png", 			
		["unique"] = true, 	    
		["combinable"] = nil,   
		["description"] = "Een gevuld bewijs zakje."
	},	
	["bloodvial"] = {
		["name"] = "bloodvial", 					
		["label"] = "Bloed Monster", 			
		["weight"] = 350, 		
		["type"] = "item", 		
		['ismetal'] = false, 
		["image"] = "bloodvial.png", 			
		["unique"] = true, 	    
		["combinable"] = nil,   
		["description"] = "Een medisch buisje met wat bloed druppels."
	},
	["armor"] = {
		["name"] = "armor", 			 	  		
		["label"] = "Kogel Vest", 				
		["weight"] = 15000, 	
		["type"] = "item", 		
		['ismetal'] = true,  
		["image"] = "vest.png", 				
		["unique"] = false,     
		["combinable"] = nil,   
		["description"] = "Een kogel afwerend vest."
	},
	["heavyarmor"] = {
		["name"] = "heavyarmor", 			 	  	
		["label"] = "Zwaar Vest", 				
		["weight"] = 20000, 	
		["type"] = "item", 		
		['ismetal'] = true,  
		["image"] = "zwaar-vest.png", 			
		["unique"] = false,     
		["combinable"] = nil,   
		["description"] = "Een zwaar kogel afwerend vest."
	},
	["lighter"] = {
		["name"] = "lighter", 			 	  		
		["label"] = "Aansteker", 				
		["weight"] = 1000, 		
		["type"] = "item", 		
		['ismetal'] = true,  
		["image"] = "lighter.png", 		    
		["unique"] = false,     
		["combinable"] = nil,   
		["description"] = "Pasop pieter."
	},
	["binoculars"] = {
		["name"] = "binoculars", 					
		["label"] = "Verrekijker", 				
		["weight"] = 600, 		
		["type"] = "item", 		
		['ismetal'] = true,  
		["image"] = "binoculars.png", 			
		["unique"] = false, 	
		["combinable"] = nil,   
		["description"] = "Gluren bij de buren.."
	},
	["nitrous"] = {
		["name"] = "nitrous", 						
		["label"] = "Nitro Fles", 				
		["weight"] = 2550, 		
		["type"] = "item", 		
		['ismetal'] = true,  
		["image"] = "nitrous.png", 			
		["unique"] = false, 	
		["combinable"] = nil,   
		["description"] = "Gassen met die lollie.."
	},
	-- // Lockpicks
	["lockpick"] = {
		["name"] = "lockpick", 			 	 	 	
		["label"] = "Lockpick", 				
		["weight"] = 1000,  	
		["type"] = "item", 		
		['ismetal'] = true, 
		["image"] = "lockpick.png", 			
		["unique"] = false,     
		["combinable"] = {['AcceptItems'] = {'screwdriverset'}, ['RewardItem'] = 'advancedlockpick'},   
		["description"] = "Een draadje ijzer verders niks speciaals"
	},
	["pickaxe"] = {
		["name"] = "pickaxe", 			 	 	 	
		["label"] = "Pikhouweel", 				
		["weight"] = 3500,  	
		["type"] = "item", 		
		['ismetal'] = true, 
		["image"] = "pickaxe.png", 			
		["unique"] = false,     
		["combinable"] = nil,   
		["description"] = "Lijkt wel op die van minecraft joh.."
	},
	["mine-scanner"] = {
		["name"] = "mine-scanner", 			 	 	 	
		["label"] = "Metaal Detector", 				
		["weight"] = 5500,  	
		["type"] = "item", 		
		['ismetal'] = true, 
		["image"] = "detector.png", 			
		["unique"] = false,     
		["combinable"] = nil,   
		["description"] = "Lekker stenen mee scannen.."
	},
	["screwdriverset"] = {
		["name"] = "screwdriverset", 			 	
		["label"] = "Toolkit", 					
		["weight"] = 450,  		
		["type"] = "item", 		
		['ismetal'] = true, 
		["image"] = "toolkit.png", 				
		["unique"] = false,     
		["combinable"] = {['AcceptItems'] = {'lockpick'}, ['RewardItem'] = 'advancedlockpick'},  
		["description"] = "Een handige schroevendraaier set."
	},
	["repairkit"] = {
		["name"] = "repairkit", 			 		
		["label"] = "Repareer Set", 			
		["weight"] = 2500,  	
		["type"] = "item", 		
		['ismetal'] = true, 
		["image"] = "repairkit.png", 			
		["unique"] = false,     
		["combinable"] = nil,   
		["description"] = "Een kistje vol met gereedschap."
	},
	["tirekit"] = {
		["name"] = "tirekit", 			 		
		["label"] = "Banden Set", 			
		["weight"] = 2500,  	
		["type"] = "item", 		
		['ismetal'] = true, 
		["image"] = "tirekit.png", 			
		["unique"] = false,     
		["combinable"] = nil,   
		["description"] = "Een extra band."
	},
	["harness"] = {
		["name"] = "harness", 			 		
		["label"] = "Race Harnas", 			
		["weight"] = 3000,  	
		["type"] = "item", 		
		['ismetal'] = true, 
		["image"] = "harness.png", 			
		["unique"] = false,     
		["combinable"] = nil,   
		["description"] = "Voor de bange poeperts."
	},
	["advancedlockpick"] = {
		["name"] = "advancedlockpick", 			 	
		["label"] = "Grote Lockpick", 			
		["weight"] = 1500,  	
		["type"] = "item", 		
		['ismetal'] = true, 
		["image"] = "advlockpick.png", 			
		["unique"] = false,     
		["combinable"] = nil,   
		["description"] = "Dit is geen draadje ijzer meer.."
	},
	["drill"] = {
		["name"] = "drill", 			    		
		["label"] = "Boor Machine", 			
		["weight"] = 15000, 	
		["type"] = "item", 		
		['ismetal'] = true, 
		["image"] = "drill.png", 				
		["unique"] = true, 		
		["combinable"] = nil,   
		["description"] = "Wat is dit voor een grote jonge."
	},
	["drill-bit"] = {
		["name"] = "drill-bit", 			    	
		["label"] = "Boor Bitje", 				
		["weight"] = 1500, 		
		["type"] = "item", 		
		['ismetal'] = true, 
		["image"] = "drill-bit.png", 			
		["unique"] = false, 	
		["combinable"] = nil,  
		["description"] = "Een bitje voor op een boor neem ik aan."
	},
	-- // Cards \\ --
	["blue-card"] = {
		["name"] = "blue-card", 			 		
		["label"] = "Blauwe Kaart", 			
		["weight"] = 1000,  	
		["type"] = "item", 		
		['ismetal'] = true,  
		["image"] = "bank-blue.png", 			
		["unique"] = false,     
		["combinable"] = nil,   
		["description"] = "Een blauw pasje.."
	},
	["purple-card"] = {
		["name"] = "purple-card", 			 		
		["label"] = "Paarse Kaart", 			
		["weight"] = 1000,  	
		["type"] = "item", 		
		['ismetal'] = true,  
		["image"] = "bank-purple.png", 		
		["unique"] = false,     
		["combinable"] = nil,   
		["description"] = "Een paars pasje.."
	},
	["red-card"] = {
		["name"] = "red-card", 					 	
		["label"] = "Rode Kaart", 				
		["weight"] = 1000,  	
		["type"] = "item", 		
		['ismetal'] = true,  
		["image"] = "bank-red.png", 			
		["unique"] = false,    
		["combinable"] = nil,   
		["description"] = "Een rood pasje.."
	},
	["green-card"] = {
		["name"] = "green-card", 					
		["label"] = "Groene Kaart", 			
		["weight"] = 1000,  	
		["type"] = "item", 		
		['ismetal'] = true, 
		["image"] = "bank-green.png", 			
		["unique"] = false,     
		["combinable"] = nil,   
		["description"] = "Een groen pasje.."
	},
	["yellow-card"] = {
		["name"] = "yellow-card", 					
		["label"] = "Gele Kaart", 				
		["weight"] = 1000,  	
		["type"] = "item", 		
		['ismetal'] = true,  
		["image"] = "jewerly-yellow.png", 		
		["unique"] = false,     
		["combinable"] = nil,   
		["description"] = "Een geel pasje.."
	},
	["black-card"] = {
		["name"] = "black-card", 					
		["label"] = "Zwarte Kaart", 			
		["weight"] = 1000,  	
		["type"] = "item", 		
		['ismetal'] = true,  
		["image"] = "card-black.png", 			
		["unique"] = false,     
		["combinable"] = nil,   
		["description"] = "Een zwart pasje.."
	},
	["electronickit"] = {
		["name"] = "electronickit", 				
		["label"] = "Electronic Kit", 			
		["weight"] = 1000,  	
		["type"] = "item", 		
		['ismetal'] = true,  
		["image"] = "electronickit.png", 		
		["unique"] = false,     
		["combinable"] = {['AcceptItems'] = {'rubber'}, ['RewardItem'] = 'usb-device'},   
		["description"] = "Een soort van moederbord?!?"
	},
	["usb-device"] = {
		["name"] = "usb-device", 					
		["label"] = "USB Apparaat", 			
		["weight"] = 1000,  	
		["type"] = "item", 		
		['ismetal'] = false, 
		["image"] = "usb-device.png", 			
		["unique"] = false,     
		["combinable"] = nil,   
		["description"] = "Staat hier een collectie op?"
	},
	["bank-box"] = {
		["name"] = "bank-box", 						
		["label"] = "Bank Doos", 				
		["weight"] = 15000,  	
		["type"] = "item", 		
		['ismetal'] = false, 
		["image"] = "bankbox.png", 			
		["unique"] = true,      
		["combinable"] = nil,   
		["description"] = "Wat zit er in?"
	},
	["bank-box-key"] = {
		["name"] = "bank-box-key", 					
		["label"] = "Bank Doos Sleutel", 		
		["weight"] = 1000,  	
		["type"] = "item", 		
		['ismetal'] = false, 
		["image"] = "bankbox-key.png", 		
		["unique"] = false,     
		["combinable"] = nil,   
		["description"] = "Wat een rare sleutel."
	},
	-- // Robbery Rewards \\ --
	["markedbills"] = {
		["name"] = "markedbills", 			  	  	
		["label"] = "Inked Geld", 				
		["weight"] = 1000, 		
		["type"] = "item", 		
		['ismetal'] = false,
		["image"] = "markedbills.png", 		
		["unique"] = true, 		
		["combinable"] = nil,   
		["description"] = "Een tasje met inkt?"
	},
	["rolex"] = {
		["name"] = "rolex", 			  	  		
		["label"] = "Gouden Horloge", 			
		["weight"] = 1500, 		
		["type"] = "item", 		
		['ismetal'] = true,  
		["image"] = "gold-rolex.png", 			
		["unique"] = false, 	
		["combinable"] = nil,   
		["description"] = "Is dit een echte rolex of niet?"
	},
	["goldchain"] = {
		["name"] = "goldchain", 			  		
		["label"] = "Gouden Ketting", 			
		["weight"] = 1500, 		
		["type"] = "item", 		
		['ismetal'] = true,  
		["image"] = "gold-necklace.png", 		
		["unique"] = false, 	
		["combinable"] = nil,   
		["description"] = "Wat een mooie gouden ketting is dit toch."
	},
	["goldbar"] = {
		["name"] = "goldbar", 			  			
		["label"] = "Goudstaaf", 				
		["weight"] = 7000, 	    
		["type"] = "item", 		
		['ismetal'] = true,  
		["image"] = "gold-bar.png", 			
		["unique"] = false, 	
		["combinable"] = nil,   
		["description"] = "Dikke grote zware staaf van goud."
	},
	["diamond_ring"] = {
		["name"] = "diamond_ring", 			  		
		["label"] = "Diamanten Ring", 			
		["weight"] = 1250, 	    
		["type"] = "item", 		
		['ismetal'] = true,  
		["image"] = "diamond-ring.png", 		
		["unique"] = false, 	
		["combinable"] = nil,   
		["description"] = "Lijkt wel op een trouw ring of iets."
	},
	["diamond-blue"] = {
		["name"] = "diamond-blue", 			  		
		["label"] = "Blauwe Diamant", 			
		["weight"] = 1500, 	    
		["type"] = "item", 		
		['ismetal'] = false, 
		["image"] = "diamond-blue.png", 		
		["unique"] = false, 	
		["combinable"] = nil,   
		["description"] = "Een blauwe diamant? Is die wel echt?"
	},
	["diamond-red"] = {
		["name"] = "diamond-red", 			  		
		["label"] = "Rode Diamant", 			
		["weight"] = 1500, 	   
		["type"] = "item", 		
		['ismetal'] = false, 
		["image"] = "diamond-red.png", 		
		["unique"] = false, 	
		["combinable"] = nil,   
		["description"] = "En dan is er ook nog een rode??"
	},
	["cult-necklace"] = {
		["name"] = "cult-necklace", 			  		
		["label"] = "Cult Ketting", 			
		["weight"] = 1000, 	   
		["type"] = "item", 		
		['ismetal'] = false, 
		["image"] = "cult-necklace.png", 		
		["unique"] = false, 	
		["combinable"] = nil,   
		["description"] = "A cult is a religion with no political power"
	},
	["white-pearl"] = {
		["name"] = "white-pearl", 			  		
		["label"] = "Witte Parel", 			
		["weight"] = 500, 	   
		["type"] = "item", 		
		['ismetal'] = false, 
		["image"] = "white-pearl.png", 		
		["unique"] = false, 	
		["combinable"] = nil,   
		["description"] = "Gevangen in een oester bevrijd voor verkoop"
	},
	["diamond-skull"] = {
		["name"] = "diamond-skull", 			  		
		["label"] = "Diamanten Schedel", 			
		["weight"] = 2000, 	   
		["type"] = "item", 		
		['ismetal'] = false, 
		["image"] = "diamond-skull.png", 		
		["unique"] = false, 	
		["combinable"] = nil,   
		["description"] = "Hoeveel diamanten zitten erop mijn hoofd?"
	},
	["diamond-chessboard"] = {
		["name"] = "diamond-chessboard", 			  		
		["label"] = "Schaakbord", 			
		["weight"] = 10000, 	   
		["type"] = "item", 		
		['ismetal'] = false, 
		["image"] = "diamond-chessboard.png", 		
		["unique"] = false, 	
		["combinable"] = nil,   
		["description"] = "Duur potje schaken.."
	},
	["heirloom"] = {
		["name"] = "heirloom", 			  		
		["label"] = "Zegelring", 			
		["weight"] = 1500, 	   
		["type"] = "item", 		
		['ismetal'] = false, 
		["image"] = "heirloom.png", 		
		["unique"] = false, 	
		["combinable"] = nil,   
		["description"] = "Kampioen!!!!"
	},
	["platinum-record"] = {
		["name"] = "platinum-record", 			  		
		["label"] = "Platina Plaat", 			
		["weight"] = 10000, 	   
		["type"] = "item", 		
		['ismetal'] = false, 
		["image"] = "platinum-record.png", 		
		["unique"] = false, 	
		["combinable"] = nil,   
		["description"] = "Klein hitje..."
	},
	["gold-record"] = {
		["name"] = "gold-record", 			  		
		["label"] = "Gouden Plaat", 			
		["weight"] = 10000, 	   
		["type"] = "item", 		
		['ismetal'] = false, 
		["image"] = "gold-record.png", 		
		["unique"] = false, 	
		["combinable"] = nil,   
		["description"] = "Hitje...."
	},
	["diamond-record"] = {
		["name"] = "diamond-record", 			  		
		["label"] = "Diamanten Plaat", 			
		["weight"] = 10000, 	   
		["type"] = "item", 		
		['ismetal'] = false, 
		["image"] = "diamond-record.png", 		
		["unique"] = false, 	
		["combinable"] = nil,   
		["description"] = "Groot hitje...."
	},
	["diamond"] = {
		["name"] = "diamond", 			  		
		["label"] = "Diamant", 			
		["weight"] = 2500, 	   
		["type"] = "item", 		
		['ismetal'] = false, 
		["image"] = "diamond.png", 		
		["unique"] = false, 	
		["combinable"] = nil,   
		["description"] = "Hij glinstert zo mooi!"
	},
	["stolen-tv"] = {
		["name"] = "stolen-tv", 			  		
		["label"] = "Gestolen TV", 			    
		["weight"] = 80000, 	
		["type"] = "item", 		
		['ismetal'] = true,  
		["image"] = "stolen-tv.png", 			
		["unique"] = true, 		
		["combinable"] = nil,   
		["description"] = "Hier krijg je toch een hernia van?"
	},
	["stolen-pc"] = {
		["name"] = "stolen-pc", 			  		
		["label"] = "Gestolen Computer", 	    
		["weight"] = 80000, 	
		["type"] = "item", 		
		['ismetal'] = true,  
		["image"] = "stolen-pc.png", 			
		["unique"] = true, 		
		["combinable"] = nil,   
		["description"] = "Kan ik hierop fivemmen?"
	},
	["stolen-micro"] = {
		["name"] = "stolen-micro", 			  		
		["label"] = "Gestolen Magnetron", 	   
		["weight"] = 80000, 	
		["type"] = "item", 		
		['ismetal'] = true,  
		["image"] = "stolen-micro.png", 		
		["unique"] = true, 		
		["combinable"] = nil,   
		["description"] = "Popcorn erbij heerluk."
	},
	["wheelchair"] = {
		["name"] = "wheelchair", 			  		
		["label"] = "Rolstoel", 	    		
		["weight"] = 30000, 	
		["type"] = "item", 		
		['ismetal'] = true,  
		["image"] = "wheelchair.png", 			
		["unique"] = true, 		
		["combinable"] = nil,   
		["description"] = "Ben je mank ofzo?"
	},
	["oxy-box"] = {
		["name"] = "oxy-box", 			 		 	
		["label"] = "Verdacht Pakket", 	    	
		["weight"] = 4000, 	    
		["type"] = "item", 		
		['ismetal'] = false, 
		["image"] = "oxy-box.png", 			
		["unique"] = true, 		
		["combinable"] = nil,   
		["description"] = "Wat zit erin?"
	},
	["stickynote"] = {
		["name"] = "stickynote", 			  		
		["label"] = "Plak Briefje", 			
		["weight"] = 500, 	    
		["type"] = "item", 		
		['ismetal'] = false, 
		["image"] = "note.png", 				
		["unique"] = true,   	
		["combinable"] = nil,   
		["description"] = "Een leeg papiertje?"
	},
	["money-roll"] = {
		["name"] = "money-roll", 			  		
		["label"] = "Geld Stack", 				
		["weight"] = 20, 	    
		["type"] = "item", 		
		['ismetal'] = false, 
		["image"] = "money-roll.png", 			
		["unique"] = false,   	
		["combinable"] = nil,   
		["description"] = "Hmm geld?"
	},
	["recycle-mats"] = {
		["name"] = "recycle-mats", 			  	  	
		["label"] = "Recycle Materiaal", 		
		["weight"] = 25, 		
		["type"] = "item", 		
		['ismetal'] = true,  
		["image"] = "recycle-mats.png", 		
		["unique"] = false, 	
		["combinable"] = nil,   
		["description"] = "Wat kan je hiermee joh?"
	},
	["plastic"] = {
		["name"] = "plastic", 			  	  	  	
		["label"] = "Plastic", 					
		["weight"] = 200, 		
		["type"] = "item", 		
		['ismetal'] = true,  
		["image"] = "plastic.png", 			
		["unique"] = false, 	
		["combinable"] = {['AcceptItems'] = {'rubber'}, ['RewardItem'] = 'weapon_brick'},   
		["description"] = "Niet op straat gooien he!"
	},
	["metalscrap"] = {
		["name"] = "metalscrap", 			  	  	
		["label"] = "Metaal schroot", 			
		["weight"] = 200, 		
		["type"] = "item", 		
		['ismetal'] = true,  
		["image"] = "metalscrap.png", 			
		["unique"] = false, 	
		["combinable"] = nil,   
		["description"] = "Hier kun je vast iets stevigs mee maken."
	},
	["copper"] = {
		["name"] = "copper", 			  	  		
		["label"] = "Koper", 					
		["weight"] = 200, 		
		["type"] = "item", 		
		['ismetal'] = true, 
		["image"] = "copper.png", 				
		["unique"] = false, 	
		["combinable"] = nil,  
		["description"] = "Handig stukje metaal wat je vast wel kunt gebruiken."
	},
	["aluminum"] = {
		["name"] = "aluminum", 			  	  		
		["label"] = "Aluminium", 				
		["weight"] = 200, 		
		["type"] = "item", 		
		['ismetal'] = true,  
		["image"] = "aluminum.png", 			
		["unique"] = false, 	
		["combinable"] = nil,   
		["description"] = "Handig stukje metaal wat je vast wel kunt gebruiken."
	},
	["iron"] = {
		["name"] = "iron", 			  				
		["label"] = "Ijzer", 					
		["weight"] = 200, 		
		["type"] = "item", 		
		['ismetal'] = true,  
		["image"] = "ironplate.png", 			
		["unique"] = false, 	
		["combinable"] = nil,   
		["description"] = "Handig stukje metaal wat je vast wel kunt gebruiken."
	},
	["steel"] = {
		["name"] = "steel", 			  			
		["label"] = "Staal", 					
		["weight"] = 200, 		
		["type"] = "item", 		
		['ismetal'] = true,  
		["image"] = "steel.png", 				
		["unique"] = false, 	
		["combinable"] = nil,   
		["description"] = "Handig stukje metaal wat je vast wel kunt gebruiken."
	},
	["rubber"] = {
		["name"] = "rubber", 			  			
		["label"] = "Rubber", 					
		["weight"] = 200, 		
		["type"] = "item", 		
		['ismetal'] = false, 
		["image"] = "rubber.png", 				
		["unique"] = false, 	
		["combinable"] = {['AcceptItems'] = {'electronickit'}, ['RewardItem'] = 'usb-device'},   
		["description"] = "Sappig stukje rubber.."
	},
	["glass"] = {
		["name"] = "glass", 			  			
		["label"] = "Glasplaat", 				
		["weight"] = 200, 		
		["type"] = "item", 		
		['ismetal'] = false, 
		["image"] = "glassplate.png", 			
		["unique"] = false, 	
		["combinable"] = nil,   
		["description"] = "Het is nogal breekbaar.. Kijk uit."
	},
	["electronics"] = {
		["name"] = "electronics", 			  			
		["label"] = "Electronica", 				
		["weight"] = 200, 		
		["type"] = "item", 		
		['ismetal'] = false, 
		["image"] = "electronics.png", 			
		["unique"] = false, 	
		["combinable"] = nil,   
		["description"] = "Kan ik hier een computer mee maken?"
	},
	["ironoxide"] = {
		["name"] = "ironoxide", 			  		
		["label"] = "Ijzer Poeder", 			
		["weight"] = 100, 		["type"] = "item", 		
		['ismetal'] = true, 
		["image"] = "ironoxide.png", 			
		["unique"] = false, 	
		["combinable"] = {['AcceptItems'] = {'aluminumoxide'}, ['RewardItem'] = 'thermite'},   
		["description"] = "Wat poeder om mee te mixen."
	},
	["aluminumoxide"] = {
		["name"] = "aluminumoxide", 			  	
		["label"] = "Aluminium Poeder", 		
		["weight"] = 100, 		
		["type"] = "item", 		
		['ismetal'] = true, 
		["image"] = "aluminumoxide.png", 		
		["unique"] = false, 	
		["combinable"] = {['AcceptItems'] = {'ironoxide'}, ['RewardItem'] = 'thermite'},       
		["description"] = "Wat poeder om mee te mixen."
	},
	["thermite"] = {
		["name"] = "thermite", 			  			
		["label"] = "Thermiet", 				
		["weight"] = 1000, 		
		["type"] = "item", 		
		['ismetal'] = true, 
		["image"] = "thermite.png", 			
		["unique"] = false, 	
		["combinable"] = nil,   
		["description"] = "Wow dit is erg vlambaar.."
	},
	["heavy-thermite"] = {
		["name"] = "heavy-thermite", 			  	
		["label"] = "Zwaar Thermiet", 			
		["weight"] = 10000, 	
		["type"] = "item", 		
		['ismetal'] = true, 
		["image"] = "hthermite.png", 			
		["unique"] = false, 	
		["combinable"] = nil,   
		["description"] = "Wow dit is erg vlambaar.."
	},
	["coin"] = {
		["name"] = "coin", 						  	
		["label"] = "Geluks Muntje", 	    	
		["weight"] = 100, 		
		["type"] = "item", 		
		['ismetal'] = true,  
		["image"] = "coin.png", 		        
		["unique"] = true, 		
		["combinable"] = nil,   
		["description"] = "Een geluks muntje zal het jouw geluk geven??"
	},
	["dice"] = {
		["name"] = "dice", 			  				
		["label"] = "Dobbel Stenen", 			
		["weight"] = 100, 		
		["type"] = "item", 		
		['ismetal'] = false, 
		["image"] = "dice.png", 				
		["unique"] = true, 		
		["combinable"] = nil,   
		["description"] = "Setje dobbel stenen lekker gokkuhh."
	},
	["jail-food"] = {
		["name"] = "jail-food", 			  		
		["label"] = "Dienblad Eten", 			
		["weight"] = 100, 		
		["type"] = "item", 		
		['ismetal'] = false, 
		["image"] = "jailfood.png", 			
		["unique"] = false, 	
		["combinable"] = nil,   
		["description"] = "Dit klinkt echt smerig."
	},
	["ass-phone"] = {
		["name"] = "ass-phone", 			  		
		["label"] = "Poep Telefoon", 			
		["weight"] = 100, 		
		["type"] = "item", 		
		['ismetal'] = false, 
		["image"] = "assphone.png", 			
		["unique"] = false, 	
		["combinable"] = nil,   
		["description"] = "Lekker poep aan je oor smeren joh."
	},
	["ass-lockpick"] = {
		["name"] = "ass-lockpick", 			  		
		["label"] = "Poep Lockpick", 			
		["weight"] = 100, 		
		["type"] = "item", 		
		['ismetal'] = false, 
		["image"] = "asslockpick.png", 		
		["unique"] = false, 	
		["combinable"] = nil,   
		["description"] = "Ik hoop niet dat ik uit een plek komt waar ik denk dat dit vandaan komt."
	},

	["bandage"] = {
		["name"] = "bandage", 			  			
		["label"] = "Verband", 					
		["weight"] = 100, 		
		["type"] = "item", 		
		['ismetal'] = false, 
		["image"] = "bandage.png", 		    
		["unique"] = false, 	
		["combinable"] = nil,   
		["description"] = "Verband voor je kleine wondjes."
	},
	["painkillers"] = {
		["name"] = "painkillers", 			  		
		["label"] = "Oxycodon", 				
		["weight"] = 100, 		
		["type"] = "item", 		
		['ismetal'] = false, 
		["image"] = "painkillers.png", 		
		["unique"] = false, 	
		["combinable"] = nil,   
		["description"] = "Dit is best zware medicatie."
	},
	["lsd-strip"] = {
		["name"] = "lsd-strip", 			  		
		["label"] = "Postzegel", 				
		["weight"] = 250, 		
		["type"] = "item", 		
		['ismetal'] = false, 
		["image"] = "postzegel.png", 		    
		["unique"] = false, 	
		["combinable"] = nil,   
		["description"] = "Lekker likken."
	},
	["joint"] = {
		["name"] = "joint", 			  	    	
		["label"] = "Joint", 					
		["weight"] = 200, 		
		["type"] = "item", 		
		['ismetal'] = false, 
		["image"] = "joint.png", 		       
		["unique"] = false, 	
		["combinable"] = nil,   
		["description"] = "Een jonko voor op de lip."
	},
	["health-pack"] = {
		["name"] = "health-pack", 			    	
		["label"] = "EHBO Koffer", 				
		["weight"] = 6000,   	
		["type"] = "item", 		
		['ismetal'] = false,
		["image"] = "health-pack.png", 		
		["unique"] = false, 	
		["combinable"] = nil,   
		["description"] = "Lijkt erop dat je iemand hiermee kan helpen.."
	},
	["wet-tak"] = {
		["name"] = "wet-tak", 			  	    	
		["label"] = "Wet Takje", 				
		["weight"] = 200, 		
		["type"] = "item", 		
		['ismetal'] = false, 
		["image"] = "wet-tak.png", 		    
		["unique"] = false, 	
		["combinable"] = nil,   
		["description"] = "Een wet tak?!?"
	},
	["wet-bud"] = {
		["name"] = "wet-bud", 			  	    	
		["label"] = "Gedroogd Wet", 			
		["weight"] = 200, 		
		["type"] = "item", 		
		['ismetal'] = false, 
		["image"] = "wet-bud.png", 		    
		["unique"] = false, 	
		["combinable"] = {['AcceptItems'] = {'rolling-paper'}, ['RewardItem'] = 'joint'},   
		["description"] = "Wat is al dit wet gedoe toch?"
	},
	["empty_weed_bag"] = {
		["name"] = "empty_weed_bag", 			  	
		["label"] = "Plastic Zakje", 			
		["weight"] = 200, 		
		["type"] = "item", 		
		['ismetal'] = false, 
		["image"] = "plastic-bag.png", 		
		["unique"] = false, 	["combinable"] = nil,   
		["description"] = "Een plastic zakje om iets in te doen ?"
	},
	["weed-nutrition"] = {
		["name"] = "weed-nutrition", 			  	
		["label"] = "Planten Voeding", 			
		["weight"] = 4000, 		
		["type"] = "item", 		
		['ismetal'] = false, 
		["image"] = "nutrition.png", 		    
		["unique"] = false, 	
		["combinable"] = nil,   
		["description"] = "Even lekker opdrinken of niet?"
	},
	["weed_white-widow"] = {
		["name"] = "weed_white-widow", 			 	
		["label"] = "White Widow 2g", 			
		["weight"] = 200, 		
		["type"] = "item", 		
		['ismetal'] = false, 
		["image"] = "weed-baggie.png", 		
		["unique"] = false, 	
		["combinable"] = nil,   
		["description"] = "Een zakje met een groene substantie."
	},
	["weed_skunk"]= {
		["name"] = "weed_skunk", 			 		
		["label"] = "Skunk 2g", 				
		["weight"] = 200, 		
		["type"] = "item", 		
		['ismetal'] = false, 
		["image"] = "weed-baggie.png", 		
		["unique"] = false, 	
		["combinable"] = nil,   
		["description"] = "Een zakje met een groene substantie."
	},
	["weed_purple-haze"] = {
		["name"] = "weed_purple-haze", 			 	
		["label"] = "Purple Haze 2g", 			
		["weight"] = 200, 		
		["type"] = "item", 		
		['ismetal'] = false, 
		["image"] = "weed-baggie.png", 		
		["unique"] = false, 	
		["combinable"] = nil,   
		["description"] = "Een zakje met een groene substantie."
	},
	["weed_og-kush"] = {
		["name"] = "weed_og-kush", 			 		
		["label"] = "OGKush 2g", 				
		["weight"] = 200, 		
		["type"] = "item", 		
		['ismetal'] = false, 
		["image"] = "weed-baggie.png", 		
		["unique"] = false, 	
		["combinable"] = nil,   
		["description"] = "Een zakje met een groene substantie."
	},
	["weed_amnesia"] = {
		["name"] = "weed_amnesia", 			 		
		["label"] = "Amnesia 2g", 				
		["weight"] = 200, 		
		["type"] = "item", 		
		['ismetal'] = false, 
		["image"] = "weed-baggie.png", 		
		["unique"] = false, 	
		["combinable"] = nil,   
		["description"] = "Een zakje met een groene substantie."
	},
	["weed_ak47"] = {
		["name"] = "weed_ak47", 			 		
		["label"] = "AK47 2g", 					
		["weight"] = 200, 		
		["type"] = "item", 		
		['ismetal'] = false, 
		["image"] = "weed-baggie.png", 		
		["unique"] = false, 	
		["combinable"] = nil,   
		["description"] = "Een zakje met een groene substantie."
	},
	["weed-brick"] = {
		["name"] = "weed-brick", 			 		
		["label"] = "Wiet Brick", 				
		["weight"] = 4000, 		
		["type"] = "item", 		
		['ismetal'] = false, 
		["image"] = "weed-brick.png", 			
		["unique"] = false, 	
		["combinable"] = nil,   
		["description"] = "Een puur natuurlijk brickie."
	},
	["rolling-paper"] = {
		["name"] = "rolling-paper", 			  	
		["label"] = "Vloei", 					
		["weight"] = 10, 		
		["type"] = "item", 		
		['ismetal'] = false, 
		["image"] = "rolling-paper.png", 		
		["unique"] = false, 	
		["combinable"] = {['AcceptItems'] = {'wet-bud'}, ['RewardItem'] = 'joint'},   
		["description"] = "Shaggies rollen tot de dood."
	},
	["weed_white-widow_seed"] = {
		["name"] = "weed_white-widow_seed", 			
		["label"] = "White Widow Zaad", 		
		["weight"] = 10, 		
		["type"] = "item", 		
		['ismetal'] = false, 
		["image"] = "plant-seed.png", 			
		["unique"] = false, 	
		["combinable"] = nil,   
		["description"] = "Een plantzaadje van White Widow"
	},
	["weed_skunk_seed"] = {
		["name"] = "weed_skunk_seed", 			    
		["label"] = "Skunk Zaad", 				
		["weight"] = 10, 		
		["type"] = "item", 		
		['ismetal'] = false, 
		["image"] = "plant-seed.png", 			
		["unique"] = false, 	
		["combinable"] = nil,   
		["description"] = "Een plantzaadje van Skunk"
	},
	["weed_purple-haze_seed"] = {
		["name"] = "weed_purple-haze_seed", 			
		["label"] = "Purple Haze Zaad", 		
		["weight"] = 10, 		
		["type"] = "item", 		
		['ismetal'] = false,
		["image"] = "plant-seed.png", 			
		["unique"] = false, 	
		["combinable"] = nil,   
		["description"] = "Een plantzaadje van Purple Haze"
	},
	["weed_og-kush_seed"] = 
	{["name"] = "weed_og-kush_seed", 				
	["label"] = "OGKush Zaad", 				
	["weight"] = 10, 		
	["type"] = "item", 		
	['ismetal'] = false, 
	["image"] = "plant-seed.png", 			
	["unique"] = false, 	
	["combinable"] = nil,   
	["description"] = "Een plantzaadje van OG Kush"
},
	["weed_amnesia_seed"] = 
	{["name"] = "weed_amnesia_seed", 				
	["label"] = "Amnesia Zaad", 			
	["weight"] = 10, 		
	["type"] = "item", 		
	['ismetal'] = false, 
	["image"] = "plant-seed.png", 			
	["unique"] = false, 	
	["combinable"] = nil,   
	["description"] = "Een plantzaadje van Amnesia"
},
	["weed_ak47_seed"] = {
		["name"] = "weed_ak47_seed", 			    
		["label"] = "AK47 Zaad", 				
		["weight"] = 10, 		
		["type"] = "item", 		
		['ismetal'] = false, 
		["image"] = "plant-seed.png", 			
		["unique"] = false, 	
		["combinable"] = nil,   
		["description"] = "Een plantzaadje van AK47"
	},
	["lotto-card"] = {
		["name"] = "lotto-card", 			 	  	
		["label"] = "Kraslot", 					
		["weight"] = 100,		
		["type"] = "item", 		
		['ismetal'] = false, 
		["image"] = "lotto-card.png", 			
		["unique"] = false, 	
		["combinable"] = nil,   
		["description"] = "Krassen tot de dood.."
	},
	["used-card"] = {
		["name"] = "used-card", 			 	  	
		["label"] = "Gekrast Kraslot", 		    
		["weight"] = 75,		
		["type"] = "item", 		
		['ismetal'] = false, 
		["image"] = "used-card.png", 			
		["unique"] = true, 		
		["combinable"] = nil,   
		["description"] = "Deze is al gekrast.."
	},
	-- // Food \\ --
	["phone"] = {
		["name"] = "phone", 			 	  	  
		["label"] = "Telefoon", 				
		["weight"] = 750, 		
		["type"] = "item", 		
		['ismetal'] = true,  
		["image"] = "phone.png", 				
		["unique"] = false, 	
		["combinable"] = nil,   
		["description"] = "Een stukje technologie"
	},
	["sandwich"] = {
		["name"] = "sandwich", 			 	  	  	
		["label"] = "Brood", 					
		["weight"] = 125, 		
		["type"] = "item", 		
		['ismetal'] = false, 
		["image"] = "bread.png", 				
		["unique"] = false, 	
		["combinable"] = nil,   
		["description"] = "Een broodje met beleg."
	},
	["water_bottle"] = {
		["name"] = "water_bottle", 					
		["label"] = "Water", 					
		["weight"] = 125, 		
		["type"] = "item", 		
		['ismetal'] = false, 
		["image"] = "water.png", 				
		["unique"] = false, 	
		["combinable"] = nil,   
		["description"] = "Eventjes lekker drinken."
	},
	["slushy"] = {
		["name"] = "slushy", 			 	  	  	
		["label"] = "Slushy", 					
		["weight"] = 10000, 	
		["type"] = "item", 		
		['ismetal'] = false, 
		["image"] = "slushy.png", 				
		["unique"] = false, 	
		["combinable"] = nil,   
		["description"] = "Pas op voor een brain freeze."
	},
	["kurkakola"] = {
		["name"] = "kurkakola", 			 	  
		["label"] = "E-Cola", 					
		["weight"] = 125, 		
		["type"] = "item", 		
		['ismetal'] = true,  
		["image"] = "ecola.png", 				
		["unique"] = false, 	
		["combinable"] = nil,   
		["description"] = "Blikie cola lekker hoor."
	},
	["sprunk"]= {
		["name"] = "sprunk", 			 	  	  	
		["label"] = "Sprunk", 					
		["weight"] = 125, 		
		["type"] = "item", 		
		['ismetal'] = true,  
		["image"] = "sprunk.png", 				
		["unique"] = false, 	
		["combinable"] = nil,   
		["description"] = "Sprunkie dr bij?"
	},
	["chocolade"] = {
		["name"] = "chocolade", 			 	  
		["label"] = "Chocolade", 				
		["weight"] = 125, 		
		["type"] = "item", 		
		['ismetal'] = false, 
		["image"] = "chocolade.png", 			
		["unique"] = false, 	
		["combinable"] = nil,   
		["description"] = "Een chocolade bar pasop straks word je nog dik."
	},
	["donut"] = {
		["name"] = "donut", 			 	  	  	
		["label"] = "Donut", 					
		["weight"] = 125, 		
		["type"] = "item", 		
		['ismetal'] = false, 
		["image"] = "donut.png", 				
		["unique"] = false, 	
		["combinable"] = nil,   
		["description"] = "Lekker donutje."
	},
	["coffee"] = {
		["name"] = "coffee", 			  	  		
		["label"] = "Koffie", 					
		["weight"] = 200, 		
		["type"] = "item", 		
		['ismetal'] = false, 
		["image"] = "coffee.png", 				
		["unique"] = false, 	
		["combinable"] = nil,   
		["description"] = "Lekker voor in de ochtend."
	},
	["420-choco"] = {
		["name"] = "420-choco", 			  	  
		["label"] = "420 Chocolade", 	
		["weight"] = 200, 		
		["type"] = "item", 		
		['ismetal'] = false, 
		["image"] = "420-choco.png", 			
		["unique"] = false, 	
		["combinable"] = nil,   
		["description"] = "420?"
	},
	["apple"] = {
		["name"] = "apple", 			  	  		
		["label"] = "Appel", 					
		["weight"] = 145, 		
		["type"] = "item", 		
		['ismetal'] = false, 
		["image"] = "apple.png", 				
		["unique"] = false, 	
		["combinable"] = nil,   
		["description"] = "An apple a day, keeps the doctor away."
	},
	["banana"] = {
		["name"] = "banana", 			  	  		
		["label"] = "Banaan", 					
		["weight"] = 145, 		
		["type"] = "item", 		
		['ismetal'] = false, 
		["image"] = "banana.png", 				
		["unique"] = false, 
		["combinable"] = nil,   
		["description"] = "Bananaaaa!!!!!!"
	},
	["chips"] = {
		["name"] = "chips", 			  	  		
		["label"] = "Chips", 					
		["weight"] = 125, 		
		["type"] = "item", 		
		['ismetal'] = false, 
		["image"] = "chips.png", 				
		["unique"] = false, 
		["combinable"] = nil,   
		["description"] = "Lekker chipie."
	},
	["macncheese"] = {
		["name"] = "macncheese", 			  	  	
		["label"] = "Mac en cheese", 			
		["weight"] = 125, 		
		["type"] = "item", 		
		['ismetal'] = false, 
		["image"] = "macncheese.png", 			
		["unique"] = false, 
		["combinable"] = nil,   
		["description"] = "Mc Donald's & Kaas?"
	},
	-- Burger Shot
	["burger-bleeder"] = {
		["name"] = "burger-bleeder", 			 	
		["label"] = "Bleeder", 					
		["weight"] = 250, 		
		["type"] = "item", 		
		['ismetal'] = false, 
		["image"] = "burger-bleeder.png", 		
		["unique"] = false, 	
		["combinable"] = nil,   
		["description"] = "Sow beetje bloederig broodje of niet?"
	},
	["burger-moneyshot"] = {
		["name"] = "burger-moneyshot", 			 	
		["label"] = "Moneyshot", 				
		["weight"] = 300, 		
		["type"] = "item", 		
		['ismetal'] = false, 
		["image"] = "burger-moneyshot.png", 	
		["unique"] = false, 	
		["combinable"] = nil,   
		["description"] = "Zit hier geld in ?"
	},
	["burger-torpedo"] = {
		["name"] = "burger-torpedo", 			 	
		["label"] = "Torpedo", 					
		["weight"] = 310, 		
		["type"] = "item", 		
		['ismetal'] = false, 
		["image"] = "burger-torpedo.png", 		
		["unique"] = false, 	
		["combinable"] = nil,   
		["description"] = "Hoort dit niet in een onderzeeboot."
	},
	["burger-heartstopper"] = {
		["name"] = "burger-heartstopper", 			
		["label"] = "Heartstopper", 			
		["weight"] = 2500, 		
		["type"] = "item", 		
		['ismetal'] = false, 
		["image"] = "burger-heartstopper.png", 
		["unique"] = false, 	
		["combinable"] = nil,  
		["description"] = "Dit kan mijn hart niet aan hoor."
	},
	["burger-softdrink"] = {
		["name"] = "burger-softdrink", 				
		["label"] = "Beker Fris", 				
		["weight"] = 125, 		
		["type"] = "item", 		
		['ismetal'] = false, 
		["image"] = "burger-softdrink.png", 	
		["unique"] = false, 	
		["combinable"] = nil,   
		["description"] = "Lekker slokkie nemen."
	},
	["burger-coffee"] = {
		["name"] = "burger-coffee", 				
		["label"] = "Beker Koffie", 			
		["weight"] = 125, 		
		["type"] = "item", 		
		['ismetal'] = false, 
		["image"] = "burger-coffee.png", 	    
		["unique"] = false, 	
		["combinable"] = nil,   
		["description"] = "Pasop is heet!"},
	["burger-fries"] = {
		["name"] = "burger-fries", 			 	  
		["label"] = "Frietjes", 			
		["weight"] = 125, 		
		["type"] = "item", 		
		['ismetal'] = false, 
		["image"] = "burger-fries.png", 		
		["unique"] = false, 	
		["combinable"] = nil,   
		["description"] = "Friet of patat? #ComeAtMe"
	},
	
	["burger-bun"] = {
		["name"] = "burger-bun", 			 	  	
		["label"] = "Burger Brood", 			
		["weight"] = 125, 		
		["type"] = "item", 		
		['ismetal'] = false, 
		["image"] = "burger-bun.png", 		    
		["unique"] = false, 	
		["combinable"] = nil,   
		["description"] = "Lekker warm en knapperig."
	},
	["burger-meat"] = {
		["name"] = "burger-meat", 			 	  	
		["label"] = "Burger Vlees", 			
		["weight"] = 125, 		
		["type"] = "item", 		
		['ismetal'] = false, 
		["image"] = "burger-meat.png", 		
		["unique"] = false, 	
		["combinable"] = nil,   
		["description"] = "Hmm lekker sappig stukkie vlees."
	},
	["burger-lettuce"] = {
		["name"] = "burger-lettuce", 			 	
		["label"] = "Burger Sla", 				
		["weight"] = 125, 		
		["type"] = "item", 		
		['ismetal'] = false, 
		["image"] = "burger-lettuce.png", 	    
		["unique"] = false, 	
		["combinable"] = nil,   
		["description"] = "Dit lijkt wel op vergif."
	},
	["burger-raw"] = {
		["name"] = "burger-raw", 			 		
		["label"] = "Rauw Vlees", 				
		["weight"] = 125, 		
		["type"] = "item", 		
		['ismetal'] = false,
		["image"] = "burger-raw.png", 	        
		["unique"] = false, 	
		["combinable"] = nil,   
		["description"] = "Dit kan je niet eten hoor."
	},
	["burger-potato"] = {
		["name"] = "burger-potato", 			 	
		["label"] = "Friet Aardappelen", 		
		["weight"] = 1500, 		
		["type"] = "item", 		
		['ismetal'] = false, 
		["image"] = "burger-potato.png", 	   
		["unique"] = false, 	
		["combinable"] = nil,  
		["description"] = "Lekker schillen."
	},
	["burger-ticket"] = {
		["name"] = "burger-ticket", 			 	
		["label"] = "Bestelling Bon", 	     	
		["weight"] = 150, 		
		["type"] = "item", 		
		['ismetal'] = false,
		["image"] = "burger-ticket.png", 	    
		["unique"] = false,   	
		["combinable"] = nil,   
		["description"] = "Hier staat een bestelling op die snel gemaakt moet worden!"
	},
	["burger-box"] = {
		["name"] = "burger-box", 			 	    
		["label"] = "Burger Zak", 	     	    
		["weight"] = 1000, 		
		["type"] = "item", 		
		['ismetal'] = false, 
		["image"] = "burger-box.png", 	        
		["unique"] = true,   	
		["combinable"] = nil,   
		["description"] = "Hier zitten lekkere spulletjes in."
	},
	-- Unicorn    
	["cocktail-1"] = {
		["name"] = "cocktail-1", 			 	  	
		["label"] = "Cocktail", 				
		["weight"] = 125, 		
		["type"] = "item", 		
		['ismetal'] = false, 
		["image"] = "cocktail-1.png", 		    
		["unique"] = false, 	
		["combinable"] = nil,   
		["description"] = "Oehhh een COCKtail."
	},
	["cocktail-2"] = {
		["name"] = "cocktail-2", 			 	  	
		["label"] = "Cocktail", 				
		["weight"] = 125, 		
		["type"] = "item", 		
		['ismetal'] = false, 
		["image"] = "cocktail-2.png", 		    
		["unique"] = false, 	
		["combinable"] = nil,   
		["description"] = "Dit is wel heel erg roze."
	},
	["cocktail-3"] = {
		["name"] = "cocktail-3", 			 	  
		["label"] = "Cocktail", 				
		["weight"] = 125, 		
		["type"] = "item", 		
		['ismetal'] = false, 
		["image"] = "cocktail-3.png", 		    
		["unique"] = false, 	
		["combinable"] = nil,   
		["description"] = "Ziet er wel lekker en tropisch uit."
	},
	["explosive"] = {
		["name"] = "explosive", 			 	  		
		["label"] = "Explosief", 				
		["weight"] = 4500, 		
		["type"] = "item", 		
		['ismetal'] = true, 
		["image"] = "explosive.png", 		    
		["unique"] = false, 	
		["combinable"] = nil,   
		["description"] = "Biem."
	},
	["scuba-gear"] = {
		["name"] = "scuba-gear", 					
		["label"] = "Duik Spullen", 			
		["weight"] = 30000, 	
		["type"] = "item", 		
		['ismetal'] = true, 
		["image"] = "scuba-gear.png", 			
		["unique"] = true, 	    
		["combinable"] = nil,   
		["description"] = "Hoop dat je niet stikt.."
	},
	-- Fishing
	["fishingrod"] = {
		["name"] = "fishingrod", 			 	  	
		["label"] = "Vis Hengel", 		    	
		["weight"] = 500, 		
		["type"] = "item", 		
		['ismetal'] = false, 
		["image"] = "vishengel.png", 			
		["unique"] = true, 	    
		["combinable"] = nil,   
		["description"] = "Even lekker hengelen.."
	},
	["fish-1"] = {
		["name"] = "fish-1", 			 	  	  
		["label"] = "Blauwe Vis", 				
		["weight"] = 750, 		
		["type"] = "item", 		
		['ismetal'] = false, 
		["image"] = "fish-1.png", 				
		["unique"] = false, 	
		["combinable"] = nil,   
		["description"] = "Dit is bijna een goudvis.."
	},
	["fish-2"] = {
		["name"] = "fish-2", 			 	  	  	
		["label"] = "Baars", 					
		["weight"] = 1500, 		
		["type"] = "item", 		
		['ismetal'] = false, 
		["image"] = "fish-2.png", 				
		["unique"] = false, 	
		["combinable"] = nil,   
		["description"] = "Pas op ik kan prikken.."
	},
	["fish-3"] = {
		["name"] = "fish-3", 			 	  	  	
		["label"] = "Makreel", 					
		["weight"] = 1700, 		
		["type"] = "item", 		
		['ismetal'] = false,
		["image"] = "fish-3.png", 				
		["unique"] = false, 	
		["combinable"] = nil,   
		["description"] = "Watn joekel van een vis zeg."
	},
	["special-fish"] = {
		["name"] = "special-fish", 			 	  	
		["label"] = "Gouden Vis", 				
		["weight"] = 2000, 		
		["type"] = "item", 		
		['ismetal'] = true,  
		["image"] = "special-fish.png", 		
		["unique"] = false, 	
		["combinable"] = nil,  
		["description"] = "DE GOUDEN VIS NEEJ JOH."
	},
	["fish-box"] = {
		["name"] = "fish-box", 			 	  		
		["label"] = "Verwaterde Doos", 			
		["weight"] = 2000, 		
		["type"] = "item", 		
		['ismetal'] = true,  
		["image"] = "fish-box.png", 			
		["unique"] = true, 		
		["combinable"] = nil,   
		["description"] = "Wat zit hier in dan?"
	},
	["fish-crate"] = {
		["name"] = "fish-crate", 			 	  
		["label"] = "Verwaterde Krat", 			
		["weight"] = 5000, 		
		["type"] = "item", 		
		['ismetal'] = true,  
		["image"] = "fish-crate.png", 			
		["unique"] = true, 		
		["combinable"] = nil,   
		["description"] = "Poah dit is oud nat en smerig bleh."
	},
	["fish-dolphine"] = {
		["name"] = "fish-dolphine", 			 	
		["label"] = "Dolfijn", 					
		["weight"] = 12000, 	
		["type"] = "item", 		
		['ismetal'] = false, 
		["image"] = "fish-dolphine.png", 		
		["unique"] = true, 		
		["combinable"] = nil,   
		["description"] = "Is dit niet illegaal om te hebben?"
	},
	["plasticbag"] = {
		["name"] = "plasticbag", 			 	 	
		["label"] = "Plastic zak", 				
		["weight"] = 125, 		
		["type"] = "item", 		
		['ismetal'] = false, 
		["image"] = "plasticbag.png", 			
		["unique"] = false, 	
		["combinable"] = nil,   
		["description"] = "Zak over de hoofd en gaan, toch??"
	},
	["shoe"] = {
		["name"] = "shoe", 			 	     	  	
		["label"] = "Oude Schoen", 				
		["weight"] = 1500, 		
		["type"] = "item", 		
		['ismetal'] = false, 
		["image"] = "shoe.png", 				
		["unique"] = false, 	
		["combinable"] = nil,   
		["description"] = "Sportief moddeletje wel hoor."
	},
	["hunting-knife"] = {
		["name"] = "hunting-knife", 			 	
		["label"] = "Jacht Mes", 				
		["weight"] = 1500, 		
		["type"] = "item", 		
		['ismetal'] = true,   
		["image"] = "hunting-knife.png", 		
		["unique"] = true, 		
		["combinable"] = nil,   
		["description"] = "Niet mee spelen he?"
	},
	["hunting-bait"] = {
		["name"] = "hunting-bait", 			 		
		["label"] = "Lok Voer", 				
		["weight"] = 1000, 		
		["type"] = "item", 		
		['ismetal'] = false,  
		["image"] = "hunting-bait.png", 		
		["unique"] = false, 	
		["combinable"] = nil,   
		["description"] = "Dit is niet voor menselijke consumptie denk ik."
	},
	["deer-antlers"] = {
		["name"] = "deer-antlers", 			 		
		["label"] = "Gewei", 					
		["weight"] = 3500, 		
		["type"] = "item", 		
		['ismetal'] = false,  
		["image"] = "deer-antler.png", 		
		["unique"] = false, 	
		["combinable"] = nil,   
		["description"] = "En gewei van een rendier?"
	},
	["hunting-pelt"] = {
		["name"] = "hunting-pelt", 			 		
		["label"] = "Vacht", 					
		["weight"] = 1250, 		
		["type"] = "item", 		
		['ismetal'] = false,  
		["image"] = "hunting-pelt.png", 		
		["unique"] = false, 	
		["combinable"] = nil,   
		["description"] = "Dieren vacht."
	},
	["hunting-meat"] = {
		["name"] = "hunting-meat", 			 		
		["label"] = "Rauw Vlees", 					
		["weight"] = 700, 		
		["type"] = "item", 		
		['ismetal'] = false,  
		["image"] = "hunting-meat.png", 		
		["unique"] = false, 	
		["combinable"] = nil,   
		["description"] = "Rauw dieren vlees"
	},
	["hunting-carcas-one"] = {
		["name"] = "hunting-carcas-one", 			
		["label"] = "Slecht Karkas", 			
		["weight"] = 15000, 		
		["type"] = "item", 		
		['ismetal'] = false,  
		["image"] = "hunting-carcas1.png", 	
		["unique"] = true, 		
		["combinable"] = nil,   
		["description"] = "Een karkas van een dier mag ik hopen."
	},
	["hunting-carcas-two"] = {
		["name"] = "hunting-carcas-two", 			
		["label"] = "Normaal Karkas", 			
		["weight"] = 15000, 		
		["type"] = "item", 		
		['ismetal'] = false,  
		["image"] = "hunting-carcas2.png", 	
		["unique"] = true, 		
		["combinable"] = nil,   
		["description"] = "Een karkas van een dier mag ik hopen."
	},
	["hunting-carcas-three"] = {
		["name"] = "hunting-carcas-three", 			
		["label"] = "Perfect Karkas", 			
		["weight"] = 15000, 		
		["type"] = "item", 		
		['ismetal'] = false,  
		["image"] = "hunting-carcas3.png", 	
		["unique"] = true, 		
		["combinable"] = nil,   
		["description"] = "Een karkas van een dier mag ik hopen."
	},
	["hunting-carcas-four"] = {
		["name"] = "hunting-carcas-four", 			
		["label"] = "Perfect Karkas", 			
		["weight"] = 15000, 		
		["type"] = "item", 		
		['ismetal'] = false,  
		["image"] = "hunting-carcas4.png", 	
		["unique"] = true, 		
		["combinable"] = nil,   
		["description"] = "Een karkas van een dier mag ik hopen."
	},
	["sushi"] = {
		["name"] = "sushi", 			 		
		["label"] = "Sushi", 					
		["weight"] = 250, 		
		["type"] = "item", 		
		['ismetal'] = false,  
		["image"] = "sushi.png", 		
		["unique"] = false, 	
		["combinable"] = nil,   
		["description"] = "Sambal bij?"
	},
	["sushi-ramen"] = {
		["name"] = "sushi-ramen", 			 		
		["label"] = "Ramen", 					
		["weight"] = 250, 		
		["type"] = "item", 		
		['ismetal'] = false,  
		["image"] = "sushi-ramen.png", 		
		["unique"] = false, 	
		["combinable"] = nil,   
		["description"] = "Goed blazen he!"
	},
	["sushi-beef"] = {
		["name"] = "sushi-beef", 			 		
		["label"] = "Rund Schotel", 					
		["weight"] = 250, 		
		["type"] = "item", 		
		['ismetal'] = false,  
		["image"] = "sushi-beef.png", 		
		["unique"] = false, 	
		["combinable"] = nil,   
		["description"] = "Voor onze vlees liefhebbers!"
	},
	["sushi-tea"] = {
		["name"] = "sushi-tea", 			 		
		["label"] = "Geluks Thee", 					
		["weight"] = 250, 		
		["type"] = "item", 		
		['ismetal'] = false,  
		["image"] = "sushi-tea.png", 		
		["unique"] = false, 	
		["combinable"] = nil,   
		["description"] = "Oeeh pasop is heet!"
	},
	["sushi-rice"] = {
		["name"] = "sushi-rice", 			 		
		["label"] = "Rijst", 					
		["weight"] = 250, 		
		["type"] = "item", 		
		['ismetal'] = false,  
		["image"] = "sushi-rice.png", 		
		["unique"] = false, 	
		["combinable"] = nil,   
		["description"] = "Hmm wel eerst koken he!"
	},
	["sushi-noodle"] = {
		["name"] = "sushi-noodle", 			 		
		["label"] = "Noodles", 					
		["weight"] = 250, 		
		["type"] = "item", 		
		['ismetal'] = false,  
		["image"] = "sushi-noodle.png", 		
		["unique"] = false, 	
		["combinable"] = nil,   
		["description"] = "Ook dit eerst koken he!"
	},
	["licence"] = {
		["name"] = "licence", 			 	  	  	
		["label"] = "Vergunning", 				
		["weight"] = 100, 		
		["type"] = "item", 		
		['ismetal'] = false, 
		["image"] = "licence.png", 			
		["unique"] = true, 		
		["combinable"] = nil,   
		["description"] = "Officiele documenten."
	},
	["id_card"] = {
		["name"] = "id_card", 			 	  	  	
		["label"] = "Identiteits Kaart", 		
		["weight"] = 100, 		
		["type"] = "item", 		
		['ismetal'] = false, 
		["image"] = "license-id.png", 			
		["unique"] = true, 		
		["combinable"] = nil,   
		["description"] = "Een kaart waar al je gegevens op staat."
	},
	["driver_license"] 			 	 = {
		["name"] = "driver_license", 		    	
		["label"] = "Rijbewijs", 				
		["weight"] = 100, 		
		["type"] = "item", 		
		['ismetal'] = false,
		["image"] = "license-drive.png", 		
		["unique"] = true, 		
		["combinable"] = nil,   
		["description"] = "Bewijs om aan te tonen dat je een voertuig kunt besturen."
	},
	["lawyerpass"] = {
		["name"] = "lawyerpass", 			 	  	
		["label"] = "Advocatenpas", 			
		["weight"] = 0, 		
		["type"] = "item", 		
		['ismetal'] = false, 
		["image"] = "lawyerpass.png", 			
		["unique"] = true, 		
		["combinable"] = nil,   
		["description"] = "Pas enkel voor advocaten als bewijs dat zij een verdachte mogen vertegenwoordigen."
	},
	["duffel-bag"] = {
		["name"] = "duffel-bag", 			 	  	
		["label"] = "Duffel Tas", 			    
		["weight"] = 19500, 	
		["type"] = "item", 		
		['ismetal'] = false, 
		["image"] = "duffel-bag.png", 			
		["unique"] = true, 		
		["combinable"] = nil,   
		["description"] = "Sow deze is tering zwaar."
	},
	-- Messen Onderdelen
	["knife-part-1"] = {
		["name"] = "knife-part-1", 			 	  
		["label"] = "Mes Onderdeel", 			
		["weight"] = 450, 		
		["type"] = "item", 		
		['ismetal'] = true, 
		["image"] = "knife-part-1.png", 		
		["unique"] = false, 	
		["combinable"] = {['AcceptItems'] = {'knife-part-2'}, ['RewardItem'] = 'weapon_knife'},         
		["description"] = "Lijkt wel op een onderdeel van een mes."
	},
	["knife-part-2"] = {
		["name"] = "knife-part-2", 			 	  	
		["label"] = "Mes Onderdeel", 			
		["weight"] = 450, 		
		["type"] = "item", 		
		['ismetal'] = true, 
		["image"] = "knife-part-2.png", 		
		["unique"] = false, 	
		["combinable"] = {['AcceptItems'] = {'knife-part-1'}, ['RewardItem'] = 'weapon_knife'},          
		["description"] = "Lijkt wel op een onderdeel van een mes."
	},
	["switch-part-1"] = {
		["name"] = "switch-part-1", 			 	
		["label"] = "Klapmes Onderdeel", 	
		["weight"] = 450, 		
		["type"] = "item", 		
		['ismetal'] = true, 
		["image"] = "switch-part-1.png", 		
		["unique"] = false, 	
		["combinable"] = {['AcceptItems'] = {'switch-part-2'}, ['RewardItem'] = 'weapon_switchblade'},   
		["description"] = "Lijkt wel op een onderdeel van een mes."
	},
	["switch-part-2"] = {
		["name"] = "switch-part-2", 			 	
		["label"] = "Klapmes Onderdeel", 	
		["weight"] = 450, 		
		["type"] = "item", 		
		['ismetal'] = true, 
		["image"] = "switch-part-2.png", 		
		["unique"] = false, 	
		["combinable"] = {['AcceptItems'] = {'switch-part-1'}, ['RewardItem'] = 'weapon_switchblade'},   
		["description"] = "Lijkt wel op een onderdeel van een mes."
	},
	["snspistol_part_1"] = {
		["name"] = "snspistol_part_1", 				
		["label"] = "SNS Loop", 				
		["weight"] = 1500, 		
		["type"] = "item", 		
		['ismetal'] = true, 
		["image"] = "snspistol_part_1.png", 	
		["unique"] = false, 	
		["combinable"] =  {['AcceptItems'] = {'snspistol_part_3'},  ['RewardItem'] = 'snspistol_stage_1'},    
		["description"] = "Loop van een SNS Pistol"
	},
	["snspistol_part_2"] = {
		["name"] = "snspistol_part_2", 				
		["label"] = "SNS Trigger", 				
		["weight"] = 1500, 		
		["type"] = "item", 		
		['ismetal'] = true, 
		["image"] = "snspistol_part_2.png", 	
		["unique"] = false, 	
		["combinable"] =  {['AcceptItems'] = {'snspistol_stage_1'}, ['RewardItem'] = 'weapon_snspistol_mk2'}, 
		["description"] = "Trigger van een SNS Pistol"
	},
	["snspistol_part_3"] = {
		["name"] = "snspistol_part_3", 				
		["label"] = "SNS Clip", 				
		["weight"] = 1500, 		
		["type"] = "item", 		
		['ismetal'] = true, 
		["image"] = "snspistol_part_3.png", 	
		["unique"] = false, 	
		["combinable"] =  {['AcceptItems'] = {'snspistol_part_1'}, ['RewardItem'] = 'snspistol_stage_1'},     
		["description"] = "Clip van een SNS Pistol"
	},
	["snspistol_stage_1"] = {
		["name"] = "snspistol_stage_1", 			
		["label"] = "SNS Body", 				
		["weight"] = 2500, 		
		["type"] = "item", 		
		['ismetal'] = true, 
		["image"] = "snspistol_stage_1.png", 	
		["unique"] = false, 	
		["combinable"] =  {['AcceptItems'] = {'snspistol_part_2'}, ['RewardItem'] = 'weapon_snspistol_mk2'},  
		["description"] = "SNS w/ Loop & Clip"
	},
	["big-repair"] = {
		["name"] = "big-repair", 					
		["label"] = "Repareer Kist", 			
		["weight"] = 2500, 		
		["type"] = "item", 		
		['ismetal'] = true, 
		["image"] = "big-repair.png", 		
		["unique"] = false, 	
		["combinable"] = nil, 
		["description"] = "Een grote reparatie set."
	},
	["clutch-a"] = {
		["name"] = "clutch-a", 						
		["label"] = "Koppeling (A)", 			
		["weight"] = 750, 		
		["type"] = "item", 		
		['ismetal'] = true, 
		["image"] = "clutch-a.png", 		
		["unique"] = false, 	
		["combinable"] = nil, 
		["description"] = "Koppeling Klasse A"
	},
	["clutch-b"] = {
		["name"] = "clutch-b", 						
		["label"] = "Koppeling (B)", 			
		["weight"] = 750, 		
		["type"] = "item", 		
		['ismetal'] = true, 
		["image"] = "clutch-b.png", 		
		["unique"] = false, 	
		["combinable"] = nil, 
		["description"] = "Koppeling Klasse B"
	},
	["clutch-s"] = {
		["name"] = "clutch-s", 						
		["label"] = "Koppeling (S)", 			
		["weight"] = 750, 		
		["type"] = "item", 		
		['ismetal'] = true, 
		["image"] = "clutch-s.png", 		
		["unique"] = false, 	
		["combinable"] = nil, 
		["description"] = "Koppeling Klasse S"
	},
	["axle-a"] = {
		["name"] = "axle-a", 						
		["label"] = "Aandrijfas (A)", 			
		["weight"] = 750, 		
		["type"] = "item", 		
		['ismetal'] = true, 
		["image"] = "axle-a.png", 			
		["unique"] = false, 	
		["combinable"] = nil, 
		["description"] = "Aandrijfas Klasse A"
	},
	["axle-b"] = {
		["name"] = "axle-b", 						
		["label"] = "Aandrijfas (B)", 			
		["weight"] = 750, 		
		["type"] = "item", 		
		['ismetal'] = true, 
		["image"] = "axle-b.png", 			
		["unique"] = false, 	
		["combinable"] = nil, 
		["description"] = "Aandrijfas Klasse B"
	},
	["axle-s"] = {
		["name"] = "axle-s", 						
		["label"] = "Aandrijfas (S)", 			
		["weight"] = 750, 		
		["type"] = "item", 		
		['ismetal'] = true, 
		["image"] = "axle-s.png", 			
		["unique"] = false, 	
		["combinable"] = nil, 
		["description"] = "Aandrijfas Klasse S"
	},
	["brakes-a"] = {
		["name"] = "brakes-a", 						
		["label"] = "Remmen (A)", 				
		["weight"] = 750, 		
		["type"] = "item", 		
		['ismetal'] = true, 
		["image"] = "brakes-a.png", 		
		["unique"] = false, 	
		["combinable"] = nil, 
		["description"] = "Remmen Klasse A"
	},
	["brakes-b"] = {
		["name"] = "brakes-b", 						
		["label"] = "Remmen (B)", 				
		["weight"] = 750, 		
		["type"] = "item", 		
		['ismetal'] = true, 
		["image"] = "brakes-b.png", 		
		["unique"] = false, 	
		["combinable"] = nil, 
		["description"] = "Remmen Klasse B"
	},
	["brakes-s"] = {
		["name"] = "brakes-s", 						
		["label"] = "Remmen (S)", 				
		["weight"] = 750, 		
		["type"] = "item", 		
		['ismetal'] = true, 
		["image"] = "brakes-s.png", 		
		["unique"] = false, 	
		["combinable"] = nil, 
		["description"] = "Remmen Klasse S"
	},
	["engine-a"] = {
		["name"] = "engine-a", 						
		["label"] = "Motor (A)", 				
		["weight"] = 750, 		
		["type"] = "item", 		
		['ismetal'] = true, 
		["image"] = "engine-a.png", 		
		["unique"] = false, 	
		["combinable"] = nil, 
		["description"] = "Motor Klasse A"
	},
	["engine-b"] = {
		["name"] = "engine-b", 						
		["label"] = "Motor (B)", 				
		["weight"] = 750, 		
		["type"] = "item", 		
		['ismetal'] = true, 
		["image"] = "engine-b.png", 		
		["unique"] = false, 	
		["combinable"] = nil, ["description"] = "Motor Klasse B"
	},
	["engine-s"] = {
		["name"] = "engine-s", 						
		["label"] = "Motor (S)", 				
		["weight"] = 750, 		
		["type"] = "item", 		
		['ismetal'] = true, 
		["image"] = "engine-s.png", 		
		["unique"] = false, 	
		["combinable"] = nil, 
		["description"] = "Motor Klasse S"
	},
	["injectors-a"] = {
		["name"] = "injectors-a", 					
		["label"] = "Injectoren (A)", 			
		["weight"] = 750, 		
		["type"] = "item", 		
		['ismetal'] = true, 
		["image"] = "injectors-a.png", 		
		["unique"] = false, 	
		["combinable"] = nil, 
		["description"] = "Brandstof Injectoren Klasse A"
	},
	["injectors-b"] = {
		["name"] = "injectors-b", 					
		["label"] = "Injectoren (B)", 			
		["weight"] = 750, 		
		["type"] = "item", 		
		['ismetal'] = true, 
		["image"] = "injectors-b.png", 		
		["unique"] = false, 	
		["combinable"] = nil, 
		["description"] = "Brandstof Injectoren Klasse B"
	},
	["injectors-s"] = {
		["name"] = "injectors-s", 					
		["label"] = "Injectoren (S)", 			
		["weight"] = 750, 		
		["type"] = "item", 		
		['ismetal'] = true, 
		["image"] = "injectors-s.png", 		
		["unique"] = false, 	
		["combinable"] = nil, 
		["description"] = "Brandstof Injectoren Klasse S"
	},
	["transmission-a"] = {
		["name"] = "transmission-a", 				
		["label"] = "Transmissie (A)", 			
		["weight"] = 750, 		
		["type"] = "item", 		
		['ismetal'] = true, 
		["image"] = "transmission-a.png", 	
		["unique"] = false, 	
		["combinable"] = nil, 
		["description"] = "Transmissie Klasse A"
	},
	["transmission-b"] = {
		["name"] = "transmission-b", 				
		["label"] = "Transmissie (B)", 			
		["weight"] = 750, 		
		["type"] = "item", 		
		['ismetal'] = true, 
		["image"] = "transmission-b.png", 	
		["unique"] = false, 	
		["combinable"] = nil, 
		["description"] = "Transmissie Klasse B"
	},
	["transmission-s"] = {
		["name"] = "transmission-s", 			
		["label"] = "Transmissie (S)", 			
		["weight"] = 750, 		
		["type"] = "item", 		
		['ismetal'] = true, 
		["image"] = "transmission-s.png", 
		["unique"] = false, 
		["combinable"] = nil, 
		["description"] = "Transmissie Klasse S"
	},
	["bible"] = {
		["name"] = "bible", 							
		["label"] = "Codex Gigas", 				
		["weight"] = 750, 		
		["type"] = "item", 		
		['ismetal'] = false, 
		["image"] = "bible.png", 			
		["unique"] = false, 	
		["combinable"] = nil, 
		["description"] = "Satan zal bij u zijn broeder."
	},
	["humanbone"] = {
		["name"] = "humanbone", 						
		["label"] = "Botten", 					
		["weight"] = 750, 		
		["type"] = "item", 		
		['ismetal'] = false, 
		["image"] = "humanbone.png", 		
		["unique"] = false, 	
		["combinable"] = nil, 
		["description"] = "Sow deze zijn lang."
	},
	["humanskull"] = {
		["name"] = "humanskull", 					
		["label"] = "Schedel", 					
		["weight"] = 750, 		
		["type"] = "item", 		
		['ismetal'] = false, 
		["image"] = "humanskull.png", 		
		["unique"] = false, 	
		["combinable"] = nil, 
		["description"] = "Poah wat een graf kop."
	},
	["humaneye"] = {
		["name"] = "humaneye", 						
		["label"] = "Mensen Oog", 				
		["weight"] = 750, 		
		["type"] = "item", 		
		['ismetal'] = false, 
		["image"] = "humaneye.png", 		
		["unique"] = false, 	
		["combinable"] = nil, 
		["description"] = "Kan jij kijken is mijn vraag?"
	},
	["humanfinger"] = {
		["name"] = "humanfinger", 					
		["label"] = "Mensen Vinger", 			
		["weight"] = 750, 		
		["type"] = "item", 		
		['ismetal'] = false, 
		["image"] = "humanfinger.png", 	
		["unique"] = false, 	
		["combinable"] = nil,
		["description"] = "Weer lopen stelen zeker he."
	},
	["humanheart"] = {
		["name"] = "humanheart", 					
		["label"] = "Mensen Hart", 				
		["weight"] = 750, 		
		["type"] = "item", 		
		['ismetal'] = false, 
		["image"] = "humanheart.png", 		
		["unique"] = false, 	
		["combinable"] = nil, 
		["description"] = "Hallo klopt daar iemand?"
	},
	["humankidney"] = {
		["name"] = "humankidney", 					
		["label"] = "Mensen Nier", 				
		["weight"] = 750, 		
		["type"] = "item", 		
		['ismetal'] = false, 
		["image"] = "humankidney.png", 
		["unique"] = false, 	
		["combinable"] = nil, 
		["description"] = "Kan toch nog wel door zuipen met 1 nier toch?"
	},
	["humanleg"] = {
		["name"] = "humanleg", 						
		["label"] = "Mensen Been", 				
		["weight"] = 750, 		
		["type"] = "item", 		
		['ismetal'] = false, 
		["image"] = "humanleg.png", 		
		["unique"] = false, 	
		["combinable"] = nil, 
		["description"] = "Lekker lopen he!"
	},
	["rose"] = {
		["name"] = "rose", 							
		["label"] = "Rode Roos", 				
		["weight"] = 750, 		
		["type"] = "item", 		
		['ismetal'] = false,
		["image"] = "rose.png", 			
		["unique"] = false, 	
		["combinable"] = nil, 
		["description"] = "Een rode roos!"
	},
	["antipatharia_coral"] 			= {
		["name"] = "antipatharia_coral", 			
		["label"] = "Antipatharia", 			
		["weight"] = 750, 		
		["type"] = "item", 		
		['ismetal'] = false, 
		["image"] = "antipatharia.png", 	
		["unique"] = false, 	
		["combinable"] = nil, 
		["description"] = "Wauw dit is echt gaaf!"
	},
	["dendrogyra_coral"] = {
		["name"] = "dendrogyra_coral", 				
		["label"] = "Dendrogyra", 				
		["weight"] = 750, 		
		["type"] = "item", 		
		['ismetal'] = false,  
		["image"] = "dendrogyra.png", 	
		["unique"] = false, 	
		["combinable"] = nil, 
		["description"] = "Mag je dit wel bij je hebben?!"
	},
	["policepass"] = {
		["name"] = "policepass", 					
		["label"] = "Politie Pas", 				
		["weight"] = 100, 		
		["type"] = "item", 		
		['ismetal'] = false,  
		["image"] = "police-pass.png", 	
		["unique"] = true, 	    
		["combinable"] = nil, 
		["description"] = "Identificatie van een politie medewerker."
	},
	["walkstick"] = {
		["name"] = "walkstick", 						
		["label"] = "Loopstok", 				
		["weight"] = 100, 		
		["type"] = "item", 		
		['ismetal'] = false, 
		 ["image"] = "walkstick.png", 		
		 ["unique"] = false, 	
		 ["combinable"] = nil, 
		 ["description"] = "Voor de oude mannen."
		},
	["jerry_can"] = {
		["name"] = "jerry_can", 						
		["label"] = "Jerrycan", 				
		["weight"] = 8000, 		
		["type"] = "item", 		
		['ismetal'] = false,  
		["image"] = "jerry_can.png", 		
		["unique"] = false, 	
		["combinable"] = nil,
		["description"] = "Ik ruik hier meestal aan vind ik heerluk."
	},
	["parachute"] = {
		["name"] = "parachute", 						
		["label"] = "Parachute", 				
		["weight"] = 10000, 	
		["type"] = "item", 		
		['ismetal'] = false,  
		["image"] = "parachute.png", 		
		["unique"] = false, 	
		["combinable"] = nil, 
		["description"] = "Voor de echte waaghalsen."
	},
	["moneybag"] = {
		["name"] = "moneybag", 						
		["label"] = "Tas met geld", 			
		["weight"] = 0, 		
		["type"] = "item", 		
		['ismetal'] = false,  
		["image"] = "moneybag.png", 		
		["unique"] = true, 		
		["combinable"] = nil, 
		["description"] = "Hier zit wat geld in denk ik."
	},
	["rentalpapers"] = {
		["name"] = "rentalpapers", 					
		["label"] = "Huur Papieren", 			
		["weight"] = 100, 		
		["type"] = "item", 		
		['ismetal'] = false, 
		["image"] = "rentalpapers.png", 	
		["unique"] = true, 		
		["combinable"] = nil, 
		["description"] = "Volgensmij zit hier een setje sleutels in van het huur voertuig."
	},
	["sheer"] = {
		["name"] = "sheer", 							
		["label"] = "Heggenschaar", 			
		["weight"] = 2000, 		
		["type"] = "item", 		
		['ismetal'] = true,   
		["image"] = "sheer.png", 			
		["unique"] = false, 	
		["combinable"] = nil, 
		["description"] = "Lekker knippen.."
	},
	["fishpass"] = {
		["name"] = "fishpass", 						
		["label"] = "Vis Pas", 					
		["weight"] = 100, 		
		["type"] = "item", 		
		['ismetal'] = false,  
		["image"] = "fishpass.png", 		
		["unique"] = true, 		
		["combinable"] = nil, 
		["description"] = "Er is één ding wat ik nooit zou willen missen en dat is ...."
	},
	["realestatepass"] = {
		["name"] = "realestatepass", 				
		["label"] = "Makelaars Pas", 			
		["weight"] = 100, 		
		["type"] = "item", 		
		['ismetal'] = false,  
		["image"] = "fishpass.png", 		
		["unique"] = true, 		
		["combinable"] = nil, 
		["description"] = "Mooi kaartje van de makelaar"
	},
	["xray-brain"] = {
		["name"] = "xray-brain", 					
		["label"] = "Hersen X-ray", 			
		["weight"] = 100, 		
		["type"] = "item", 		
		['ismetal'] = false, 
		["image"] = "xray-hersen.png", 	
		["unique"] = false,	 	
		["combinable"] = nil,   
		["description"] = "Een hersen x-ray van iemand."
	},
	["xray-arm"] = {
		["name"] = "xray-arm", 						
		["label"] = "Arm X-ray", 				
		["weight"] = 100, 		
		["type"] = "item", 		
		['ismetal'] = false, 
		["image"] = "xray-arm.png", 	   
		["unique"] = false,	 	
		["combinable"] = nil,   
		["description"] = "Een arm x-ray van iemand."
	},
	["teddy"] = {
		["name"] = "teddy", 						
		["label"] = "Teddy Beer", 				
		["weight"] = 500, 		
		["type"] = "item", 		
		['ismetal'] = false, 
		["image"] = "teddy.png", 	   		
		["unique"] = false,	 	
		["combinable"] = nil,  
		["description"] = "Een teddy beer om iemand mee te troosten."
	},
	["umbrella"] = {
		["name"] = "umbrella", 						
		["label"] = "Paraplu", 				
		["weight"] = 500, 		
		["type"] = "item", 		
		['ismetal'] = false, 
		["image"] = "umbrella.png", 	   		
		["unique"] = false,	 	
		["combinable"] = nil,  
		["description"] = "Lekker nat."
	},
	["petrock"] = {
		["name"] = "petrock", 						
		["label"] = "Stenen Vriend", 				
		["weight"] = 100, 		
		["type"] = "item", 		
		['ismetal'] = false, 
		["image"] = "pet-rock.png", 	   		
		["unique"] = false,	 	
		["combinable"] = nil,  
		["description"] = "Mister lonely."
	},
	["hat"] = {
		["name"] = "hat", 							
		["label"] = "Petje", 					
		["weight"] = 500, 		
		["type"] = "item", 		
		['ismetal'] = false, 
		["image"] = "hat.png", 	   		
		["unique"] = true,	 	
		["combinable"] = nil,   
		["description"] = "Een hoedje."
	},
	["mask"] = {
		["name"] = "mask", 							
		["label"] = "Masker", 					
		["weight"] = 500, 		
		["type"] = "item", 		
		['ismetal'] = false, 
		["image"] = "mask.png", 	   		
		["unique"] = true,	 	
		["combinable"] = nil,   
		["description"] = "Een maskertje"
	},
	["glasses"] = {
		["name"] = "glasses", 						
		["label"] = "Bril", 					
		["weight"] = 500, 		
		["type"] = "item", 		
		['ismetal'] = false, 
		["image"] = "glasses.png", 	   	
		["unique"] = true,	 	
		["combinable"] = nil,   
		["description"] = "Een brilletje"
	},
	["hairtie"] = {
		["name"] = "hairtie", 						
		["label"] = "Scunchie", 				
		["weight"] = 500, 		
		["type"] = "item", 		
		['ismetal'] = false, 
		["image"] = "scrunchie.png", 	   	
		["unique"] = false,	 	
		["combinable"] = nil,   
		["description"] = "Voor in je haren denk ik."
	},
	["race-dongle"] = {
		["name"] = "race-dongle", 						
		["label"] = "Race Dongel", 				
		["weight"] = 500, 		
		["type"] = "item", 		
		['ismetal'] = false, 
		["image"] = "race-dongle.png", 	   	
		["unique"] = false,	 	
		["combinable"] = nil,   
		["description"] = "Krijg toegang tot de race app."
	},
	["vpn"] = {
		["name"] = "vpn", 						
		["label"] = "VPN", 				
		["weight"] = 500, 		
		["type"] = "item", 		
		['ismetal'] = false, 
		["image"] = "vpn.png", 	   	
		["unique"] = true,	 	
		["combinable"] = nil,   
		["description"] = "Kan ik hiermee verbinden met andere landen?"
	},
	["red-usb"] = {
		["name"] = "red-usb", 						
		["label"] = "Rode USB", 				
		["weight"] = 500, 		
		["type"] = "item", 		
		['ismetal'] = false, 
		["image"] = "red-usb.png", 	   	
		["unique"] = false,	 	
		["combinable"] = nil,   
		["description"] = "???"
	},
	["blue-usb"] = {
		["name"] = "blue-usb", 						
		["label"] = "Blauwe USB", 				
		["weight"] = 500, 		
		["type"] = "item", 		
		['ismetal'] = false, 
		["image"] = "blue-usb.png", 	   	
		["unique"] = false,	 	
		["combinable"] = nil,   
		["description"] = "???"
	},
	["green-usb"] = {
		["name"] = "green-usb", 						
		["label"] = "Groene USB", 				
		["weight"] = 500, 		
		["type"] = "item", 		
		['ismetal'] = false, 
		["image"] = "green-usb.png", 	   	
		["unique"] = false,	 	
		["combinable"] = nil,   
		["description"] = "???"
	},
	["cracktable"] = {
		["name"] = "cracktable", 			 	
		["label"] = "Crack Tafel", 					
		["weight"] = 9000, 		
		["type"] = "item", 		
		['ismetal'] = false, 
		["image"] = "coketable.png", 		
		["unique"] = false, 	
		["combinable"] = nil,   
		["description"] = "Je zult hier wel iets cools mee kunnen doen..."
	},
	["weedtable"] = {
		["name"] = "weedtable", 			 	
		["label"] = "Wiet Tafel", 					
		["weight"] = 6000, 		
		["type"] = "item", 		
		['ismetal'] = false, 
		["image"] = "weedtable.png", 		
		["unique"] = false, 	
		["combinable"] = nil,   
		["description"] = "Je zult hier wel iets cools mee kunnen doen..."
	},
	["methtable"] = {
		["name"] = "methtable", 			 	
		["label"] = "Meth Tafel", 					
		["weight"] = 8000, 		
		["type"] = "item", 		
		['ismetal'] = false, 
		["image"] = "methtable.png", 		
		["unique"] = false, 	
		["combinable"] = nil,   
		["description"] = "Ik weet hier niks van maar het is methtastic..."
	},
}