Config = Config or {}

Config.Doors = {
    -- Politie --
    [1] = {
        ['Name'] = 'Politie Zij Deur Links',
        ['IsAGate'] = false,
        ['LockState'] = 1,
        ['Pickable'] = true,
        ['Authorized'] = {[1] = 'police', [2] = 'judge'},
        ['LockDistance'] = 0.7,
        ['DoorName'] = 'gabz_mrpd_reception_entrancedoor',
        ['DoorCoords'] = vector3(441.36, -998.76, 30.69),
    },
    [2] = {
        ['Name'] = 'Politie Zij Deur Links',
        ['IsAGate'] = false,
        ['LockState'] = 1,
        ['Pickable'] = true,
        ['Authorized'] = {[1] = 'police', [2] = 'judge'},
        ['LockDistance'] = 0.7,
        ['DoorName'] = 'gabz_mrpd_reception_entrancedoor',
        ['DoorCoords'] = vector3(442.47, -998.74, 30.69),
    },
    [3] = {
        ['Name'] = 'Politie Zij Deur Rechts',
        ['IsAGate'] = false,
        ['LockState'] = 1,
        ['Pickable'] = true,
        ['Authorized'] = {[1] = 'police', [2] = 'judge'},
        ['LockDistance'] = 0.7,
        ['DoorName'] = 'gabz_mrpd_reception_entrancedoor',
        ['DoorCoords'] = vector3(457.57, -972.21, 30.71),
    },
    [4] = {
        ['Name'] = 'Politie Zij Deur Rechts',
        ['IsAGate'] = false,
        ['LockState'] = 1,
        ['Pickable'] = true,
        ['Authorized'] = {[1] = 'police', [2] = 'judge'},
        ['LockDistance'] = 0.7,
        ['DoorName'] = 'gabz_mrpd_reception_entrancedoor',
        ['DoorCoords'] = vector3(456.45, -972.23, 30.70),
    },
    [5] = {
        ['Name'] = 'Politie Voordeur',
        ['IsAGate'] = false,
        ['LockState'] = 0,
        ['Pickable'] = true,
        ['Authorized'] = {[1] = 'police', [2] = 'judge'},
        ['LockDistance'] = 1.0,
        ['DoorName'] = 'gabz_mrpd_reception_entrancedoor',
        ['DoorCoords'] = vector3(435.26, -982.73, 30.68),
    },
    [6] = {
        ['Name'] = 'Politie Voordeur',
        ['IsAGate'] = false,
        ['LockState'] = 0,
        ['Pickable'] = true,
        ['Authorized'] = {[1] = 'police', [2] = 'judge'},
        ['LockDistance'] = 1.0,
        ['DoorName'] = 'gabz_mrpd_reception_entrancedoor',
        ['DoorCoords'] = vector3(435.26, -981.12, 30.68),
    },
    [7] = {
        ['Name'] = 'Politie Achterdeuren',
        ['IsAGate'] = false,
        ['LockState'] = 1,
        ['Pickable'] = true,
        ['Authorized'] = {[1] = 'police', [2] = 'judge'},
        ['LockDistance'] = 1.0,
        ['DoorName'] = 'gabz_mrpd_door_03',
        ['DoorCoords'] = vector3(467.71, -1014.87, 26.38),
    },
    [8] = {
        ['Name'] = 'Politie Achterdeuren',
        ['IsAGate'] = false,
        ['LockState'] = 1,
        ['Pickable'] = true,
        ['Authorized'] = {[1] = 'police', [2] = 'judge'},
        ['LockDistance'] = 1.0,
        ['DoorName'] = 'gabz_mrpd_door_03',
        ['DoorCoords'] = vector3(469.52, -1014.88, 26.38),
    },
    [9] = {
        ['Name'] = 'Politie Receptie Deur',
        ['IsAGate'] = false,
        ['LockState'] = 1,
        ['Pickable'] = true,
        ['Authorized'] = {[1] = 'police', [2] = 'judge'},
        ['LockDistance'] = 2.2,
        ['DoorName'] = 'gabz_mrpd_door_04',
        ['DoorCoords'] = vector3(441.16, -978.11, 30.68),
    },
    [10] = {
        ['Name'] = 'Politie Receptie Deur 2',
        ['IsAGate'] = false,
        ['LockState'] = 1,
        ['Pickable'] = true,
        ['Authorized'] = {[1] = 'police', [2] = 'judge'},
        ['LockDistance'] = 2.2,
        ['DoorName'] = 'gabz_mrpd_door_05',
        ['DoorCoords'] = vector3(441.30, -985.71, 30.68),
    },
    [11] = {
        ['Name'] = 'Politie Garage Deur',
        ['IsAGate'] = false,
        ['LockState'] = 1,
        ['Pickable'] = true,
        ['Authorized'] = {[1] = 'police', [2] = 'judge'},
        ['LockDistance'] = 2.2,
        ['DoorName'] = 'gabz_mrpd_room13_parkingdoor',
        ['DoorCoords'] = vector3(463.69, -996.76, 26.27),
    },
    [12] = {
        ['Name'] = 'Politie Garage Deur 2',
        ['IsAGate'] = false,
        ['LockState'] = 1,
        ['Pickable'] = true,
        ['Authorized'] = {[1] = 'police', [2] = 'judge'},
        ['LockDistance'] = 2.2,
        ['DoorName'] = 'gabz_mrpd_room13_parkingdoor',
        ['DoorCoords'] = vector3(463.68, -975.37, 26.27),
    },
    [13] = {
        ['Name'] = 'Politie Cell Buiten Deur',
        ['IsAGate'] = false,
        ['LockState'] = 1,
        ['Pickable'] = true,
        ['Authorized'] = {[1] = 'police', [2] = 'judge'},
        ['LockDistance'] = 1.2,
        ['DoorName'] = 'gabz_mrpd_cells_door',
        ['DoorCoords'] = vector3(477.05, -1008.22, 26.27),
    },
    [14] = {
        ['Name'] = 'Politie Cell Buiten Deur 2',
        ['IsAGate'] = false,
        ['LockState'] = 1,
        ['Pickable'] = true,
        ['Authorized'] = {[1] = 'police', [2] = 'judge'},
        ['LockDistance'] = 1.2,
        ['DoorName'] = 'gabz_mrpd_cells_door',
        ['DoorCoords'] = vector3(481.66, -1004.56, 26.27),
    },
    [15] = {
        ['Name'] = 'Politie Cell',
        ['IsAGate'] = false,
        ['LockState'] = 1,
        ['Pickable'] = true,
        ['Authorized'] = {[1] = 'police', [2] = 'judge'},
        ['LockDistance'] = 1.2,
        ['DoorName'] = 'gabz_mrpd_cells_door',
        ['DoorCoords'] = vector3(484.82, -1008.17, 26.27),
    },
    [16] = {
        ['Name'] = 'Politie Cell',
        ['IsAGate'] = false,
        ['LockState'] = 1,
        ['Pickable'] = true,
        ['Authorized'] = {[1] = 'police', [2] = 'judge'},
        ['LockDistance'] = 1.2,
        ['DoorName'] = 'gabz_mrpd_cells_door',
        ['DoorCoords'] = vector3(486.36, -1011.73, 26.27),
    },
    [17] = {
        ['Name'] = 'Politie Cell 3',
        ['IsAGate'] = false,
        ['LockState'] = 1,
        ['Pickable'] = true,
        ['Authorized'] = {[1] = 'police', [2] = 'judge'},
        ['LockDistance'] = 1.2,
        ['DoorName'] = 'gabz_mrpd_cells_door',
        ['DoorCoords'] = vector3(483.34, -1011.82, 26.27),
    },
    [18] = {
        ['Name'] = 'Politie Cell 4',
        ['IsAGate'] = false,
        ['LockState'] = 1,
        ['Pickable'] = true,
        ['Authorized'] = {[1] = 'police', [2] = 'judge'},
        ['LockDistance'] = 1.2,
        ['DoorName'] = 'gabz_mrpd_cells_door',
        ['DoorCoords'] = vector3(480.39, -1011.74, 26.27),
    },
    [19] = {
        ['Name'] = 'Politie Cell 5',
        ['IsAGate'] = false,
        ['LockState'] = 1,
        ['Pickable'] = true,
        ['Authorized'] = {[1] = 'police', [2] = 'judge'},
        ['LockDistance'] = 1.2,
        ['DoorName'] = 'gabz_mrpd_cells_door',
        ['DoorCoords'] = vector3(477.42, -1011.74, 26.27),
    },
    -- Ambulance --
    [20] = {
        ['Name'] = 'Ambulance OK Rechts',
        ['IsAGate'] = false,
        ['LockState'] = 1,
        ['Pickable'] = false,
        ['Authorized'] = {[1] = 'police', [2] = 'ambulance'},
        ['LockDistance'] = 1.0,
        ['DoorName'] = 'gabz_pillbox_doubledoor_r',
        ['DoorCoords'] = vector3(314.14, -572.61, 43.28),
    },
    [21] = {
        ['Name'] = 'Ambulance OK Links',
        ['IsAGate'] = false,
        ['LockState'] = 1,
        ['Pickable'] = false,
        ['Authorized'] = {[1] = 'police', [2] = 'ambulance'},
        ['LockDistance'] = 1.0,
        ['DoorName'] = 'gabz_pillbox_doubledoor_l',
        ['DoorCoords'] = vector3(311.91, -571.78, 43.28),
    },
    [22] = {
        ['Name'] = 'Ambulance OK 2 Rechts',
        ['IsAGate'] = false,
        ['LockState'] = 1,
        ['Pickable'] = false,
        ['Authorized'] = {[1] = 'police', [2] = 'ambulance'},
        ['LockDistance'] = 1.0,
        ['DoorName'] = 'gabz_pillbox_doubledoor_r',
        ['DoorCoords'] = vector3(319.89, -574.69, 43.28),
    },
    [23] = {
        ['Name'] = 'Ambulance OK 2 Links',
        ['IsAGate'] = false,
        ['LockState'] = 1,
        ['Pickable'] = false,
        ['Authorized'] = {[1] = 'police', [2] = 'ambulance'},
        ['LockDistance'] = 1.0,
        ['DoorName'] = 'gabz_pillbox_doubledoor_l',
        ['DoorCoords'] = vector3(317.66, -573.87, 43.28),
    },
    [24] = {
        ['Name'] = 'Ambulance OK 3 Rechts',
        ['IsAGate'] = false,
        ['LockState'] = 1,
        ['Pickable'] = false,
        ['Authorized'] = {[1] = 'police', [2] = 'ambulance'},
        ['LockDistance'] = 1.0,
        ['DoorName'] = 'gabz_pillbox_doubledoor_r',
        ['DoorCoords'] = vector3(325.36, -576.68, 43.28),
    },
    [25] = {
        ['Name'] = 'Ambulance OK 3 Links',
        ['IsAGate'] = false,
        ['LockState'] = 1,
        ['Pickable'] = false,
        ['Authorized'] = {[1] = 'police', [2] = 'ambulance'},
        ['LockDistance'] = 1.0,
        ['DoorName'] = 'gabz_pillbox_doubledoor_l',
        ['DoorCoords'] = vector3(323.32, -575.94, 43.28),
    },
    -- Prison --
    [26] = {
        ['Name'] = 'Gevangenis Gate',
        ['IsAGate'] = true,
        ['LockState'] = 1,
        ['Pickable'] = false,
        ['Authorized'] = {[1] = 'police', [2] = 'judge'},
        ['LockDistance'] = 10.0,
        ['DoorName'] = 'prop_gate_prison_01',
        ['DoorCoords'] = vector3(1844.9, 2604.8, 44.6),
    },
    [27] = {
        ['Name'] = 'Gevangenis Gate 2',
        ['IsAGate'] = true,
        ['LockState'] = 1,
        ['Pickable'] = false,
        ['Authorized'] = {[1] = 'police', [2] = 'judge'},
        ['LockDistance'] = 10.0,
        ['DoorName'] = 'prop_gate_prison_01',
        ['DoorCoords'] = vector3(1818.5, 2604.8, 44.6),
    },
    [28] = {
        ['Name'] = 'Gevangenis Gate Binnen',
        ['IsAGate'] = false,
        ['LockState'] = 1,
        ['Pickable'] = false,
        ['Authorized'] = {[1] = 'police', [2] = 'judge'},
        ['LockDistance'] = 1.3,
        ['DoorName'] = 'sanhje_Prison_recep_door02',
        ['DoorCoords'] = vector3(1831.771, 2594.194, 46.01),
    },
    [29] = {
        ['Name'] = 'Gevangenis Gate Binnen 2',
        ['IsAGate'] = false,
        ['LockState'] = 1,
        ['Pickable'] = false,
        ['Authorized'] = {[1] = 'police', [2] = 'judge'},
        ['LockDistance'] = 1.3,
        ['DoorName'] = 'prison_visit_gate',
        ['DoorCoords'] = vector3(1840.92, 2594.38, 46.01),
    },
    [30] = {
        ['Name'] = 'Gevangenis Buiten Toren',
        ['IsAGate'] = false,
        ['LockState'] = 1,
        ['Pickable'] = false,
        ['Authorized'] = {[1] = 'police', [2] = 'judge'},
        ['LockDistance'] = 1.3,
        ['DoorName'] = 'prop_gate_prison_01',
        ['DoorCoords'] = vector3(1798.2119, 2530.3781, 45.55278),
    },
    [31] = {
        ['Name'] = 'Gevangenis Tussen 2',
        ['IsAGate'] = false,
        ['LockState'] = 1,
        ['Pickable'] = false,
        ['Authorized'] = {[1] = 'police', [2] = 'judge'},
        ['LockDistance'] = 1.3,
        ['DoorName'] = 'prop_fnclink_03gate5',
        ['DoorCoords'] = vector3(1797.7, 2596.63, 45.66),
    },
    [32] = {
        ['Name'] = 'Gevang Toren Deur',
        ['IsAGate'] = false,
        ['LockState'] = 1,
        ['Pickable'] = false,
        ['Authorized'] = {[1] = 'police', [2] = 'judge'},
        ['LockDistance'] = 1.3,
        ['DoorName'] = 'v_ilev_gtdoor',
        ['DoorCoords'] = vector3(1820.89, 2477.05, 45.37),
    },
    [33] = {
        ['Name'] = 'Gevang Toren Deur 2',
        ['IsAGate'] = false,
        ['LockState'] = 1,
        ['Pickable'] = false,
        ['Authorized'] = {[1] = 'police', [2] = 'judge'},
        ['LockDistance'] = 1.3,
        ['DoorName'] = 'v_ilev_gtdoor',
        ['DoorCoords'] = vector3(1760.03, 2413.54, 45.36),
    },
    [34] = {
        ['Name'] = 'Gevang Toren Deur 3',
        ['IsAGate'] = false,
        ['LockState'] = 1,
        ['Pickable'] = false,
        ['Authorized'] = {[1] = 'police', [2] = 'judge'},
        ['LockDistance'] = 1.3,
        ['DoorName'] = 'v_ilev_gtdoor',
        ['DoorCoords'] = vector3(1659.27, 2398.14, 45.40),
    },
    [35] = {
        ['Name'] = 'Gevang Toren Deur 4',
        ['IsAGate'] = false,
        ['LockState'] = 1,
        ['Pickable'] = false,
        ['Authorized'] = {[1] = 'police', [2] = 'judge'},
        ['LockDistance'] = 1.3,
        ['DoorName'] = 'v_ilev_gtdoor',
        ['DoorCoords'] = vector3(1544.10, 2470.89, 45.40),
    },
    [36] = {
        ['Name'] = 'Gevang Toren Deur 5',
        ['IsAGate'] = false,
        ['LockState'] = 1,
        ['Pickable'] = false,
        ['Authorized'] = {[1] = 'police', [2] = 'judge'},
        ['LockDistance'] = 1.3,
        ['DoorName'] = 'v_ilev_gtdoor',
        ['DoorCoords'] = vector3(1538.32, 2585.37, 45.40),
    },
    [37] = {
        ['Name'] = 'Gevang Toren Deur 6',
        ['IsAGate'] = false,
        ['LockState'] = 1,
        ['Pickable'] = false,
        ['Authorized'] = {[1] = 'police', [2] = 'judge'},
        ['LockDistance'] = 1.3,
        ['DoorName'] = 'v_ilev_gtdoor',
        ['DoorCoords'] = vector3(1572.69, 2678.35, 45.40),
    },
    [38] = {
        ['Name'] = 'Gevang Toren Deur 7',
        ['IsAGate'] = false,
        ['LockState'] = 1,
        ['Pickable'] = false,
        ['Authorized'] = {[1] = 'police', [2] = 'judge'},
        ['LockDistance'] = 1.3,
        ['DoorName'] = 'v_ilev_gtdoor',
        ['DoorCoords'] = vector3(1650.71, 2754.75, 45.40),
    },
    [39] = {
        ['Name'] = 'Gevang Toren Deur 8',
        ['IsAGate'] = false,
        ['LockState'] = 1,
        ['Pickable'] = false,
        ['Authorized'] = {[1] = 'police', [2] = 'judge'},
        ['LockDistance'] = 1.3,
        ['DoorName'] = 'v_ilev_gtdoor',
        ['DoorCoords'] = vector3(1772.37, 2759.32, 45.40),
    },
    [40] = {
        ['Name'] = 'Gevang Toren Deur 9',
        ['IsAGate'] = false,
        ['LockState'] = 1,
        ['Pickable'] = false,
        ['Authorized'] = {[1] = 'police', [2] = 'judge'},
        ['LockDistance'] = 1.3,
        ['DoorName'] = 'v_ilev_gtdoor',
        ['DoorCoords'] = vector3(1845.23, 2699.18, 45.53),
    },
    [41] = {
        ['Name'] = 'Gevang Toren Deur 10',
        ['IsAGate'] = false,
        ['LockState'] = 1,
        ['Pickable'] = false,
        ['Authorized'] = {[1] = 'police', [2] = 'judge'},
        ['LockDistance'] = 1.3,
        ['DoorName'] = 'v_ilev_gtdoor',
        ['DoorCoords'] = vector3(1820.32, 2621.43, 45.40),
    },
    -- Juwelier --
    [42] = {
        ['Name'] = 'Juwelier Deuren Links',
        ['IsAGate'] = false,
        ['LockState'] = 4,
        ['Pickable'] = false,
        ['Authorized'] = {[1] = 'police', [2] = 'judge'},
        ['LockDistance'] = 1.3,
        ['DoorName'] = 'p_jewel_door_l',
        ['DoorCoords'] = vector3(-631.9554, -236.3333, 38.20653),
    },
    [43] = {
        ['Name'] = 'Juwelier Deuren Rechts',
        ['IsAGate'] = false,
        ['LockState'] = 4,
        ['Pickable'] = false,
        ['Authorized'] = {[1] = 'police', [2] = 'judge'},
        ['LockDistance'] = 1.3,
        ['DoorName'] = 'p_jewel_door_r1',
        ['DoorCoords'] = vector3(-630.4265, -238.4376, 38.20653),
    },
    -- Banks --
    [44] = {
        ['Name'] = 'Blokken Bank Gate',
        ['IsAGate'] = false,
        ['LockState'] = 4,
        ['Pickable'] = true,
        ['Authorized'] = {[1] = 'police', [2] = 'judge'},
        ['LockDistance'] = 1.3,
        ['DoorName'] = 'v_ilev_gb_vaubar',
        ['DoorCoords'] = vector3(149.89, -1047.29, 29.34),
    },
    [45] = {
        ['Name'] = 'Customs Bank Gate',
        ['IsAGate'] = false,
        ['LockState'] = 4,
        ['Pickable'] = true,
        ['Authorized'] = {[1] = 'police', [2] = 'judge'},
        ['LockDistance'] = 1.3,
        ['DoorName'] = 'v_ilev_gb_vaubar',
        ['DoorCoords'] = vector3(-351.19, -56.54, 49.01),
    },
    [46] = {
        ['Name'] = 'Pink Motel Bank Gate',
        ['IsAGate'] = false,
        ['LockState'] = 4,
        ['Pickable'] = true,
        ['Authorized'] = {[1] = 'police', [2] = 'judge'},
        ['LockDistance'] = 1.3,
        ['DoorName'] = 'v_ilev_gb_vaubar',
        ['DoorCoords'] = vector3(314.61, -285.82, 54.49),
    },
    [47] = {
        ['Name'] = 'Verloren Bank Gate',
        ['IsAGate'] = false,
        ['LockState'] = 4,
        ['Pickable'] = true,
        ['Authorized'] = {[1] = 'police', [2] = 'judge'},
        ['LockDistance'] = 1.3,
        ['DoorName'] = 'v_ilev_gb_vaubar',
        ['DoorCoords'] = vector3(-1207.37, -335.08, 37.75),
    },
    [48] = {
        ['Name'] = 'Snelweg Bank Gate',
        ['IsAGate'] = false,
        ['LockState'] = 4,
        ['Pickable'] = true,
        ['Authorized'] = {[1] = 'police', [2] = 'judge'},
        ['LockDistance'] = 1.3,
        ['DoorName'] = 'v_ilev_gb_vaubar',
        ['DoorCoords'] = vector3(-2956.04, 484.66, 15.67),
    },
    [49] = {
        ['Name'] = 'Sandy Bank Gate',
        ['IsAGate'] = false,
        ['LockState'] = 4,
        ['Pickable'] = true,
        ['Authorized'] = {[1] = 'police', [2] = 'judge'},
        ['LockDistance'] = 1.3,
        ['DoorName'] = 'v_ilev_gb_vaubar',
        ['DoorCoords'] = vector3(1173.07, 2712.74, 38.06),
    },
    [50] = {
        ['Name'] = 'Paleto Bank Gate',
        ['IsAGate'] = false,
        ['LockState'] = 4,
        ['Pickable'] = true,
        ['Authorized'] = {[1] = 'police', [2] = 'judge'},
        ['LockDistance'] = 1.0,
        ['DoorName'] = 'v_ilev_cbankvaulgate02',
        ['DoorCoords'] = vector3(-105.88, 6475.54, 31.62),
    },
    [51] = {
        ['Name'] = 'HumaneLabs Onderwater',
        ['IsAGate'] = false,
        ['LockState'] = 1,
        ['Pickable'] = false,
        ['Authorized'] = {[1] = 'yeetniks'},
        ['LockDistance'] = 1.3,
        ['DoorName'] = 'v_ilev_bl_doorpool',
        ['DoorCoords'] = vector3(3525.23, 3702.40, 20.99),
    },
    [52] = {
        ['Name'] = 'HumaneLabs Garage Deur',
        ['IsAGate'] = false,
        ['LockState'] = 1,
        ['Pickable'] = false,
        ['Authorized'] = {[1] = 'yeetniks'},
        ['LockDistance'] = 7.0,
        ['DoorName'] = 'v_ilev_bl_shutter2',
        ['DoorCoords'] = vector3(3620.97, 3751.71, 28.69),
    },
    [53] = {
        ['Name'] = 'HumaneLabs Garage Deur 2',
        ['IsAGate'] = false,
        ['LockState'] = 1,
        ['Pickable'] = false,
        ['Authorized'] = {[1] = 'yeetniks'},
        ['LockDistance'] = 7.0,
        ['DoorName'] = 'v_ilev_bl_shutter2',
        ['DoorCoords'] = vector3(3628.11, 3746.92, 28.69),
    },
    [54] = {
        ['Name'] = 'Smelterij Back Upper',
        ['IsAGate'] = false,
        ['LockState'] = 0,
        ['Pickable'] = false,
        ['Authorized'] = {[1] = 'yeetniks'},
        ['LockDistance'] = 1.3,
        ['DoorName'] = 'prop_ron_door_01',
        ['DoorCoords'] = vector3(1084.56, -2018.96, 41.48),
    },
    [55] = {
        ['Name'] = 'Smelterij Back',
        ['IsAGate'] = false,
        ['LockState'] = 0,
        ['Pickable'] = false,
        ['Authorized'] = {[1] = 'yeetniks'},
        ['LockDistance'] = 1.3,
        ['DoorName'] = 'prop_ron_door_01',
        ['DoorCoords'] = vector3(1065.59, -2005.57, 32.12),
    },
    [56] = {
        ['Name'] = 'Smelterij Back',
        ['IsAGate'] = false,
        ['LockState'] = 0,
        ['Pickable'] = false,
        ['Authorized'] = {[1] = 'yeetniks'},
        ['LockDistance'] = 1.3,
        ['DoorName'] = 'prop_ron_door_01',
        ['DoorCoords'] = vector3(1083.27, -1974.71, 31.27),
    },
    -- Politie Paleto --
    [57] = {
        ['Name'] = 'Politie Paleto',
        ['IsAGate'] = false,
        ['LockState'] = 1,
        ['Pickable'] = true,
        ['Authorized'] = {[1] = 'police', [2] = 'judge'},
        ['LockDistance'] = 1.3,
        ['DoorName'] = 'v_ilev_ph_gendoor002',
        ['DoorCoords'] = vector3(-444.38, 6009.50, 31.71),
    },
    [58] = {
        ['Name'] = 'Politie Paleto 2',
        ['IsAGate'] = false,
        ['LockState'] = 1,
        ['Pickable'] = true,
        ['Authorized'] = {[1] = 'police', [2] = 'judge'},
        ['LockDistance'] = 1.3,
        ['DoorName'] = 'v_ilev_ph_gendoor002',
        ['DoorCoords'] = vector3(-446.41, 6002.13, 31.71),
    },
    [59] = {
        ['Name'] = 'Politie Paleto 3',
        ['IsAGate'] = false,
        ['LockState'] = 1,
        ['Pickable'] = true,
        ['Authorized'] = {[1] = 'police', [2] = 'judge'},
        ['LockDistance'] = 1.3,
        ['DoorName'] = 'v_ilev_ph_gendoor002',
        ['DoorCoords'] = vector3(-451.17, 6006.86, 31.71),
    },
    [60] = {
        ['Name'] = 'Politie Paleto 4',
        ['IsAGate'] = false,
        ['LockState'] = 1,
        ['Pickable'] = true,
        ['Authorized'] = {[1] = 'police', [2] = 'judge'},
        ['LockDistance'] = 1.3,
        ['DoorName'] = 'v_ilev_ph_gendoor002',
        ['DoorCoords'] = vector3(-436.41, 5992.18, 31.71),
    },
    [61] = {
        ['Name'] = 'Politie Paleto Cell 1',
        ['IsAGate'] = false,
        ['LockState'] = 1,
        ['Pickable'] = true,
        ['Authorized'] = {[1] = 'police', [2] = 'judge'},
        ['LockDistance'] = 1.3,
        ['DoorName'] = 'v_ilev_ph_cellgate',
        ['DoorCoords'] = vector3(-439.36, 5988.97, 31.71),
    },
    [62] = {
        ['Name'] = 'Politie Paleto Cell 2',
        ['IsAGate'] = false,
        ['LockState'] = 1,
        ['Pickable'] = true,
        ['Authorized'] = {[1] = 'police', [2] = 'judge'},
        ['LockDistance'] = 1.3,
        ['DoorName'] = 'v_ilev_ph_cellgate',
        ['DoorCoords'] = vector3(-441.36, 5986.58, 31.71),
    },
    [63] = {
        ['Name'] = 'Politie Paleto Cell 3',
        ['IsAGate'] = false,
        ['LockState'] = 1,
        ['Pickable'] = true,
        ['Authorized'] = {[1] = 'police', [2] = 'judge'},
        ['LockDistance'] = 1.3,
        ['DoorName'] = 'v_ilev_ph_cellgate',
        ['DoorCoords'] = vector3(-441.55, 5988.82, 31.71),
    },
    [64] = {
        ['Name'] = 'Politie Paleto Cell 4',
        ['IsAGate'] = false,
        ['LockState'] = 1,
        ['Pickable'] = true,
        ['Authorized'] = {[1] = 'police', [2] = 'judge'},
        ['LockDistance'] = 1.3,
        ['DoorName'] = 'v_ilev_ph_cellgate',
        ['DoorCoords'] = vector3(-439.37, 5991.158, 31.71),
    },
    [65] = {
        ['Name'] = 'Politie Paleto Cell 4',
        ['IsAGate'] = false,
        ['LockState'] = 1,
        ['Pickable'] = true,
        ['Authorized'] = {[1] = 'police', [2] = 'judge'},
        ['LockDistance'] = 1.3,
        ['DoorName'] = 'v_ilev_ph_gendoor002',
        ['DoorCoords'] = vector3(-447.96, 6018.11, 31.71),
    },
    -- EXTRA MRPD
    [66] = {
        ['Name'] = 'Politie Bollars One',
        ['IsAGate'] = true,
        ['LockState'] = 1,
        ['Pickable'] = false,
        ['Authorized'] = {[1] = 'police', [2] = 'judge'},
        ['DoorRange'] = 4.5,
        ['LockDistance'] = 5.0,
        ['DoorName'] = 'gabz_mrpd_bollards1',
        ['DoorCoords'] = vector3(410.01, -1020.72, 29.41),
    },
    [67] = {
        ['Name'] = 'Politie Bollars Two',
        ['IsAGate'] = true,
        ['LockState'] = 1,
        ['Pickable'] = false,
        ['Authorized'] = {[1] = 'police', [2] = 'judge'},
        ['DoorRange'] = 4.5,
        ['LockDistance'] = 5.0,
        ['DoorName'] = 'gabz_mrpd_bollards2',
        ['DoorCoords'] = vector3(410.12, -1028.21, 29.39),
    },
    [68] = {
        ['Name'] = 'Politie Garage Deur One',
        ['IsAGate'] = true,
        ['LockState'] = 1,
        ['Pickable'] = false,
        ['Authorized'] = {[1] = 'police', [2] = 'judge'},
        ['DoorRange'] = 4.5,
        ['LockDistance'] = 6.5,
        ['DoorName'] = 'gabz_mrpd_garage_door',
        ['DoorCoords'] = vector3(452.31, -1000.84, 25.72),
    },
    [69] = {
        ['Name'] = 'Politie Garage Deur Two',
        ['IsAGate'] = true,
        ['LockState'] = 1,
        ['Pickable'] = false,
        ['Authorized'] = {[1] = 'police', [2] = 'judge'},
        ['DoorRange'] = 4.5,
        ['LockDistance'] = 6.5,
        ['DoorName'] = 'gabz_mrpd_garage_door',
        ['DoorCoords'] = vector3(431.35, -1000.73, 25.71),
    },
    [70] = {
        ['Name'] = 'Politie Garage Deur Three',
        ['IsAGate'] = true,
        ['LockState'] = 1,
        ['Pickable'] = false,
        ['Authorized'] = {[1] = 'police', [2] = 'judge'},
        ['DoorRange'] = 4.5,
        ['LockDistance'] = 6.5,
        ['DoorName'] = 'hei_prop_station_gate',
        ['DoorCoords'] = vector3(488.79, -1020.03, 28.21),
    },
    [71] = {
        ['Name'] = 'Politie Kantoor Leiding',
        ['IsAGate'] = false,
        ['LockState'] = 1,
        ['Pickable'] = false,
        ['Authorized'] = {[1] = 'police', [2] = 'judge'},
        ['LockDistance'] = 1.3,
        ['DoorName'] = 'gabz_mrpd_door_05',
        ['DoorCoords'] = vector3(458.66, -990.03, 30.68),
    },

    [72] = {
        ['Name'] = 'Tunershop Garage',
        ['IsAGate'] = false,
        ['LockState'] = 1,
        ['Pickable'] = false,
        ['Authorized'] = {[1] = 'mechanic'},
        ['DoorRange'] = 6.5,
        ['LockDistance'] = 6.5,
        ['DoorName'] = 'denis3d_hayes_auto_shuttergate',
        ['DoorCoords'] = vector3(-1414.74, -436.59, 35.93),
    },
    [73] = {
        ['Name'] = 'Tunershop Garage',
        ['IsAGate'] = false,
        ['LockState'] = 1,
        ['Pickable'] = false,
        ['Authorized'] = {[1] = 'mechanic'},
        ['DoorRange'] = 6.5,
        ['LockDistance'] = 6.5,
        ['DoorName'] = 'denis3d_hayes_auto_shuttergate',
        ['DoorCoords'] = vector3(-1421.15, -440.58, 35.93),
    },
    [74] = {
        ['Name'] = 'Tunershop Garage',
        ['IsAGate'] = false,
        ['LockState'] = 1,
        ['Pickable'] = false,
        ['Authorized'] = {[1] = 'mechanic'},
        ['DoorRange'] = 6.5,
        ['LockDistance'] = 6.5,
        ['DoorName'] = 'denis3d_hayes_auto_shuttergate',
        ['DoorCoords'] = vector3(-1427.21, -444.23, 35.93),
    },
    [75] = {
        ['Name'] = 'Tunershop Garage Deur',
        ['IsAGate'] = false,
        ['LockState'] = 1,
        ['Pickable'] = false,
        ['Authorized'] = {[1] = 'mechanic'},
        ['LockDistance'] = 1.3,
        ['DoorName'] = 'denis3d_hayes_auto_maindoors',
        ['DoorCoords'] = vector3(-1433.50, -448.21, 35.93),
    },
    [76] = {
        ['Name'] = 'Burgershot Drive Window',
        ['IsAGate'] = false,
        ['LockState'] = 1,
        ['Pickable'] = true,
        ['Authorized'] = {[1] = 'burger'},
        ['LockDistance'] = 1.3,
        ['DoorName'] = 'bs_dtwindow',
        ['DoorCoords'] = vector3(-1193.80, -906.94, 14.64),
    },
    [77] = {
        ['Name'] = 'Burgershot Drive Door',
        ['IsAGate'] = false,
        ['LockState'] = 1,
        ['Pickable'] = true,
        ['Authorized'] = {[1] = 'burger'},
        ['LockDistance'] = 1.3,
        ['DoorName'] = 'bs_prop_door_staff_01',
        ['DoorCoords'] = vector3(-1199.61, -903.34, 13.98),
    },
    [78] = {
        ['Name'] = 'Burgershot Employee Door',
        ['IsAGate'] = false,
        ['LockState'] = 1,
        ['Pickable'] = true,
        ['Authorized'] = {[1] = 'burger'},
        ['LockDistance'] = 1.3,
        ['DoorName'] = 'bs_prop_door_01',
        ['DoorCoords'] = vector3(-1200.63, -892.56, 13.92),
    },
    [79] = {
        ['Name'] = 'Casino Poortje Links',
        ['IsAGate'] = false,
        ['LockState'] = 1,
        ['Pickable'] = false,
        ['Authorized'] = {[1] = 'none'},
        ['LockDistance'] = 0.8,
        ['DoorName'] = 'vw_vwint_01_gate_slide',
        ['DoorCoords'] = vector3(1118.50, 237.29, -49.84),
    },
    [80] = {
        ['Name'] = 'Casino Poortje Links',
        ['IsAGate'] = false,
        ['LockState'] = 1,
        ['Pickable'] = false,
        ['Authorized'] = {[1] = 'none'},
        ['LockDistance'] = 0.8,
        ['DoorName'] = 'vw_vwint_01_gate_slide',
        ['DoorCoords'] = vector3(1119.20, 236.54, -49.84),
    },
    [81] = {
        ['Name'] = 'Vespucci HB Kleding',
        ['IsAGate'] = false,
        ['LockState'] = 1,
        ['Pickable'] = true,
        ['Authorized'] = {[1] = 'police'},
        ['LockDistance'] = 1.0,
        ['DoorName'] = 'v_ilev_gendoor01',
        ['DoorCoords'] = vector3(-1086.32, -825.25, 19.29),
    },
    [82] = {
        ['Name'] = 'Vespucci HB Dubbel',
        ['IsAGate'] = false,
        ['LockState'] = 1,
        ['Pickable'] = true,
        ['Authorized'] = {[1] = 'police'},
        ['LockDistance'] = 0.8,
        ['DoorName'] = 'v_ilev_gendoor01',
        ['DoorCoords'] = vector3(-1091.68, -823.38, 19.29),
    },
    [83] = {
        ['Name'] = 'Vespucci HB Dubbel',
        ['IsAGate'] = false,
        ['LockState'] = 1,
        ['Pickable'] = true,
        ['Authorized'] = {[1] = 'police'},
        ['LockDistance'] = 0.8,
        ['DoorName'] = 'v_ilev_gendoor01',
        ['DoorCoords'] = vector3(-1092.49, -822.36, 19.29),
    },
    [84] = {
        ['Name'] = 'Vespucci HB Main Cell',
        ['IsAGate'] = false,
        ['LockState'] = 1,
        ['Pickable'] = true,
        ['Authorized'] = {[1] = 'police'},
        ['LockDistance'] = 0.8,
        ['DoorName'] = 'v_ilev_ph_cellgate',
        ['DoorCoords'] = vector3(-1082.65, -839.86, 13.52),
    },
    [85] = {
        ['Name'] = 'Vespucci HB Cell 1',
        ['IsAGate'] = false,
        ['LockState'] = 1,
        ['Pickable'] = true,
        ['Authorized'] = {[1] = 'police'},
        ['LockDistance'] = 0.8,
        ['DoorName'] = 'v_ilev_ph_cellgate',
        ['DoorCoords'] = vector3(-1084.73, -838.92, 13.52),
    },
    [86] = {
        ['Name'] = 'Vespucci HB Cell 2',
        ['IsAGate'] = false,
        ['LockState'] = 1,
        ['Pickable'] = true,
        ['Authorized'] = {[1] = 'police'},
        ['LockDistance'] = 0.8,
        ['DoorName'] = 'v_ilev_ph_cellgate',
        ['DoorCoords'] = vector3(-1088.37, -841.85, 13.52),
    },
    [87] = {
        ['Name'] = 'Vespucci HB Cell 3',
        ['IsAGate'] = false,
        ['LockState'] = 1,
        ['Pickable'] = true,
        ['Authorized'] = {[1] = 'police'},
        ['LockDistance'] = 0.8,
        ['DoorName'] = 'v_ilev_ph_cellgate',
        ['DoorCoords'] = vector3(-1091.17, -844.03, 13.52),
    },
    [88] = {
        ['Name'] = 'Vespucci HB Wapen Kluis',
        ['IsAGate'] = false,
        ['LockState'] = 1,
        ['Pickable'] = true,
        ['Authorized'] = {[1] = 'police'},
        ['LockDistance'] = 0.8,
        ['DoorName'] = 'v_ilev_arm_secdoor',
        ['DoorCoords'] = vector3(-1081.51, -825.14, 19.32),
    },
    [89] = {
        ['Name'] = 'Vespucci HB Captain',
        ['IsAGate'] = false,
        ['LockState'] = 1,
        ['Pickable'] = true,
        ['Authorized'] = {[1] = 'police'},
        ['LockDistance'] = 0.8,
        ['DoorName'] = 'v_ilev_ph_gendoor002',
        ['DoorCoords'] = vector3(-1083.21, -819.03, 19.32),
    },
    [90] = {
        ['Name'] = 'Stipclub 1',
        ['IsAGate'] = false,
        ['LockState'] = 1,
        ['Pickable'] = true,
        ['Authorized'] = {[1] = 'vanilla'},
        ['LockDistance'] = 1.0,
        ['DoorName'] = 'ba_prop_door_club_edgy_generic',
        ['DoorCoords'] = vector3(116.65, -1295.21, 29.26),
    },
    [91] = {
        ['Name'] = 'Stipclub 1 buiten',
        ['IsAGate'] = false,
        ['LockState'] = 1,
        ['Pickable'] = true,
        ['Authorized'] = {[1] = 'vanilla'},
        ['LockDistance'] = 1.0,
        ['DoorName'] = 'ba_prop_door_club_glam_generic',
        ['DoorCoords'] = vector3(95.52, -1285.32, 29.28),
    },
    [92] = {
        ['Name'] = 'Stipclub 2 buiten',
        ['IsAGate'] = false,
        ['LockState'] = 1,
        ['Pickable'] = true,
        ['Authorized'] = {[1] = 'vanilla'},
        ['LockDistance'] = 1.0,
        ['DoorName'] = 'prop_strip_door_01',
        ['DoorCoords'] = vector3(128.59, -1298.12, 29.26),
    },
    [93] = {
        ['Name'] = 'Vliegschool Achter',
        ['IsAGate'] = false,
        ['LockState'] = 1,
        ['Pickable'] = true,
        ['Authorized'] = {[1] = 'flightschool'},
        ['LockDistance'] = 1.0,
        ['DoorName'] = 'v_ilev_ss_door04',
        ['DoorCoords'] = vector3(-935.11, -2927.66, 13.95),
    },
    [94] = {
        ['Name'] = 'Vliegschool Dubbel 1',
        ['IsAGate'] = false,
        ['LockState'] = 1,
        ['Pickable'] = true,
        ['Authorized'] = {[1] = 'flightschool'},
        ['LockDistance'] = 0.8,
        ['DoorName'] = 'v_ilev_staffdoor',
        ['DoorCoords'] = vector3(-922.28, -2941.01, 13.94),
    },
    [95] = {
        ['Name'] = 'Vliegschool Dubbel 2',
        ['IsAGate'] = false,
        ['LockState'] = 1,
        ['Pickable'] = true,
        ['Authorized'] = {[1] = 'flightschool'},
        ['LockDistance'] = 0.8,
        ['DoorName'] = 'v_ilev_staffdoor',
        ['DoorCoords'] = vector3(-921.62, -2939.87, 13.94),
    },
    [96] = {
        ['Name'] = 'Prison Extra',
        ['IsAGate'] = false,
        ['LockState'] = 1,
        ['Pickable'] = false,
        ['Authorized'] = {[1] = 'police'},
        ['LockDistance'] = 1.2,
        ['DoorName'] = 'prop_fnclink_03gate5',
        ['DoorCoords'] = vector3(1818.60, 2582.19, 46.59),
    },
    [97] = {
        ['Name'] = 'Cardealer Voordeur 1',
        ['IsAGate'] = false,
        ['LockState'] = 1,
        ['Pickable'] = false,
        ['Authorized'] = {[1] = 'cardealer'},
        ['LockDistance'] = 0.7,
        ['DoorName'] = 'door_1_r',
        ['DoorCoords'] = vector3(-802.10, -223.91, 37.21),
    },
    [98] = {
        ['Name'] = 'Cardealer Voordeur 2',
        ['IsAGate'] = false,
        ['LockState'] = 1,
        ['Pickable'] = false,
        ['Authorized'] = {[1] = 'cardealer'},
        ['LockDistance'] = 0.7,
        ['DoorName'] = 'door_1_l',
        ['DoorCoords'] = vector3(-802.62, -223.04, 37.23),
    },
    [99] = {
        ['Name'] = 'Cardealer Achterdeur 1',
        ['IsAGate'] = false,
        ['LockState'] = 1,
        ['Pickable'] = false,
        ['Authorized'] = {[1] = 'cardealer'},
        ['LockDistance'] = 0.7,
        ['DoorName'] = 'door_2_l',
        ['DoorCoords'] = vector3(-777.72, -244.05, 37.25),
    },
    [100] = {
        ['Name'] = 'Cardealer Achterdeur 2',
        ['IsAGate'] = false,
        ['LockState'] = 1,
        ['Pickable'] = false,
        ['Authorized'] = {[1] = 'cardealer'},
        ['LockDistance'] = 0.7,
        ['DoorName'] = 'door_2_r',
        ['DoorCoords'] = vector3(-776.50, -243.67, 37.17),
    },
    [101] = {
        ['Name'] = 'Rehab Center',
        ['IsAGate'] = false,
        ['LockState'] = 1,
        ['Pickable'] = false,
        ['Authorized'] = {[1] = 'ambulance'},
        ['LockDistance'] = 1.75,
        ['DoorName'] = 'prop_lrggate_01_l',
        ['DoorCoords'] = vector3(-1478.21, 882.42, 182.87),
    },
    [102] = {
        ['Name'] = 'Rehab Center',
        ['IsAGate'] = false,
        ['LockState'] = 1,
        ['Pickable'] = false,
        ['Authorized'] = {[1] = 'ambulance'},
        ['LockDistance'] = 1.75,
        ['DoorName'] = 'prop_lrggate_01_r',
        ['DoorCoords'] = vector3(-1477.28, 887.54, 182.82),
    },
    [103] = {
        ['Name'] = 'Burgershot Deuren 1',
        ['IsAGate'] = false,
        ['LockState'] = 1,
        ['Pickable'] = false,
        ['Authorized'] = {[1] = 'burger'},
        ['LockDistance'] = 0.7,
        ['DoorName'] = 'bs_prop_door_02_r',
        ['DoorCoords'] = vector3(-1198.41, -884.79, 14.01),
    },
    [104] = {
        ['Name'] = 'Burgershot Deuren 2',
        ['IsAGate'] = false,
        ['LockState'] = 1,
        ['Pickable'] = false,
        ['Authorized'] = {[1] = 'burger'},
        ['LockDistance'] = 0.7,
        ['DoorName'] = 'bs_prop_door_02_l',
        ['DoorCoords'] = vector3(-1197.18, -883.91, 14.01),
    },
    [105] = {
        ['Name'] = 'Burgershot Deuren 3',
        ['IsAGate'] = false,
        ['LockState'] = 1,
        ['Pickable'] = false,
        ['Authorized'] = {[1] = 'burger'},
        ['LockDistance'] = 0.7,
        ['DoorName'] = 'bs_prop_door_02_r',
        ['DoorCoords'] = vector3(-1184.44, -883.95, 14.01),
    },
    [106] = {
        ['Name'] = 'Burgershot Deuren 4',
        ['IsAGate'] = false,
        ['LockState'] = 1,
        ['Pickable'] = false,
        ['Authorized'] = {[1] = 'burger'},
        ['LockDistance'] = 0.7,
        ['DoorName'] = 'bs_prop_door_02_l',
        ['DoorCoords'] = vector3(-1183.61, -885.13, 14.01),
    },
    [107] = {
        ['Name'] = 'Bobcat Main 1',
        ['IsAGate'] = false,
        ['LockState'] = 1,
        ['Pickable'] = false,
        ['Authorized'] = {[1] = 'police'},
        ['LockDistance'] = 0.7,
        ['DoorName'] = 'apa_v_ilev_ss_door7',
        ['DoorCoords'] = vector3(881.49, -2258.38, 32.44),
    },
    [108] = {
        ['Name'] = 'Bobcat Main 2',
        ['IsAGate'] = false,
        ['LockState'] = 1,
        ['Pickable'] = false,
        ['Authorized'] = {[1] = 'police'},
        ['LockDistance'] = 0.7,
        ['DoorName'] = 'apa_v_ilev_ss_door8',
        ['DoorCoords'] = vector3(882.83, -2258.54, 32.44),
    },
    [109] = {
        ['Name'] = 'Bobcat Main 3',
        ['IsAGate'] = false,
        ['LockState'] = 1,
        ['Pickable'] = true,
        ['Authorized'] = {[1] = 'police'},
        ['LockDistance'] = 0.9,
        ['DoorName'] = 'v_ilev_cd_door2',
        ['DoorCoords'] = vector3(880.91, -2264.67, 32.44),
    },
    [110] = {
        ['Name'] = 'Bobcat Main 4',
        ['IsAGate'] = false,
        ['LockState'] = 1,
        ['Pickable'] = false,
        ['Authorized'] = {[1] = 'police'},
        ['LockDistance'] = 0.75,
        ['DoorName'] = 'v_ilev_ss_door03',
        ['DoorCoords'] = vector3(880.60, -2268.08, 32.44),
    },
    [111] = {
        ['Name'] = 'Bobcat Main 5',
        ['IsAGate'] = false,
        ['LockState'] = 1,
        ['Pickable'] = false,
        ['Authorized'] = {[1] = 'police'},
        ['LockDistance'] = 0.75,
        ['DoorName'] = 'v_ilev_ss_door03',
        ['DoorCoords'] = vector3(882.00, -2268.28, 32.44),
    },
    [112] = {
        ['Name'] = 'Sushi Main Door 1',
        ['IsAGate'] = false,
        ['LockState'] = 1,
        ['Pickable'] = true,
        ['Authorized'] = {[1] = 'sushi'},
        ['LockDistance'] = 0.7,
        ['DoorName'] = 'school_upper_door_r',
        ['DoorCoords'] = vector3(-151.06, 295.22, 98.87),
    },
    [113] = {
        ['Name'] = 'Sushi Main Door 2',
        ['IsAGate'] = false,
        ['LockState'] = 1,
        ['Pickable'] = true,
        ['Authorized'] = {[1] = 'sushi'},
        ['LockDistance'] = 0.7,
        ['DoorName'] = 'school_upper_door_l',
        ['DoorCoords'] = vector3(-152.13, 295.13, 98.87),
    },
    [114] = {
        ['Name'] = 'Sushi Back Door 1',
        ['IsAGate'] = false,
        ['LockState'] = 1,
        ['Pickable'] = true,
        ['Authorized'] = {[1] = 'sushi'},
        ['LockDistance'] = 0.7,
        ['DoorName'] = 'ss1_13_door_r_01',
        ['DoorCoords'] = vector3(-178.14, 313.89, 98.02),
    },
    [115] = {
        ['Name'] = 'Sushi Back Door 2',
        ['IsAGate'] = false,
        ['LockState'] = 1,
        ['Pickable'] = true,
        ['Authorized'] = {[1] = 'sushi'},
        ['LockDistance'] = 0.7,
        ['DoorName'] = 'ss1_13_door_l_01',
        ['DoorCoords'] = vector3(-178.25, 314.85, 98.02),
    },
    [116] = {
        ['Name'] = 'Sushi Downstairs',
        ['IsAGate'] = false,
        ['LockState'] = 1,
        ['Pickable'] = true,
        ['Authorized'] = {[1] = 'sushi'},
        ['LockDistance'] = 1.0,
        ['DoorName'] = 'school_door_interior_generic_01',
        ['DoorCoords'] = vector3(-171.77, 319.14, 93.75),
    },
    [117] = {
        ['Name'] = 'Outside Door Burgershot 2',
        ['IsAGate'] = false,
        ['LockState'] = 1,
        ['Pickable'] = true,
        ['Authorized'] = {[1] = 'burger'},
        ['LockDistance'] = 1.0,
        ['DoorName'] = 'bs_prop_door_staff_01',
        ['DoorCoords'] = vector3(-1178.92, -892.00, 13.98),
    },
    -- Pacific
    [118] = { 
        ['Name'] = 'Pacific Achter Kluis',
        ['IsAGate'] = false,
        ['LockState'] = 4,
        ['Pickable'] = true,
        ['Authorized'] = {[1] = 'police'},
        ['LockDistance'] = 1.0,
        ['DoorName'] = 'hei_v_ilev_bk_safegate_pris',
        ['DoorCoords'] = vector3(251.8576, 221.0655, 101.8324),
    },
    [119] = { 
        ['Name'] = 'Pacific Laatste Kluis',
        ['IsAGate'] = false,
        ['LockState'] = 4,
        ['Pickable'] = true,
        ['Authorized'] = {[1] = 'police'},
        ['LockDistance'] = 1.0,
        ['DoorName'] = 'hei_v_ilev_bk_safegate_pris',
        ['DoorCoords'] = vector3(261.3004, 214.5051, 101.8324),
    },
    [120] = { 
        ['Name'] = 'Applestore deur links',
        ['IsAGate'] = false,
        ['LockState'] = 4,
        ['Pickable'] = true,
        ['Authorized'] = {[1] = 'police'},
        ['LockDistance'] = 1.0,
        ['DoorName'] = 'xm_prop_facility_door_01',
        ['DoorCoords'] = vector3(155.6557, -218.4715, 54.33958),
    },
    [121] = { 
        ['Name'] = 'Applestore deur rechts',
        ['IsAGate'] = false,
        ['LockState'] = 4,
        ['Pickable'] = true,
        ['Authorized'] = {[1] = 'police'},
        ['LockDistance'] = 1.0,
        ['DoorName'] = 'xm_prop_facility_door_01',
        ['DoorCoords'] = vector3(154.2344, -217.9489, 54.35123),
    },
    [122] = { 
        ['Name'] = 'Mazebank staaldeur',
        ['IsAGate'] = false,
        ['LockState'] = 4,
        ['Pickable'] = true,
        ['Authorized'] = {[1] = 'police'},
        ['LockDistance'] = 1.3,
        ['DoorName'] = 'hei_v_ilev_bk_gate_pris',
        ['DoorCoords'] = vector3(-1306.2, -820.3, 17.14),
    },
    [123] = { 
        ['Name'] = 'Maze kluisdeur',
        ['IsAGate'] = false,
        ['LockState'] = 4,
        ['Pickable'] = true,
        ['Authorized'] = {[1] = 'police'},
        ['LockDistance'] = 1.1,
        ['DoorName'] = 'hei_v_ilev_bk_safegate_pris',
        ['DoorCoords'] = vector3(-1308.32, -813.96, 17.14),
    },
    -- Bajes
    [124] = { 
        ['Name'] = 'Celdeur Paleto',
        ['IsAGate'] = false,
        ['LockState'] = 4,
        ['Pickable'] = true,
        ['Authorized'] = {[1] = 'police'},
        ['LockDistance'] = 1.1,
        ['DoorName'] = 'v_ilev_ph_cellgate1',
        ['DoorCoords'] = vector3(-444.5569, 6011.352, 27.985609),
    },
    [125] = { 
        ['Name'] = 'Ingang Paleto',
        ['IsAGate'] = false,
        ['LockState'] = 4,
        ['Pickable'] = true,
        ['Authorized'] = {[1] = 'police'},
        ['LockDistance'] = 1.1,
        ['DoorName'] = 'v_ilev_ph_cellgate1',
        ['DoorCoords'] = vector3(-438.22, 6006.16, 28.13),
    },
    [126] = { 
        ['Name'] = 'Ingang Cellen Paleto',
        ['IsAGate'] = false,
        ['LockState'] = 4,
        ['Pickable'] = true,
        ['Authorized'] = {[1] = 'police'},
        ['LockDistance'] = 1.1,
        ['DoorName'] = 'v_ilev_ph_cellgate1',
        ['DoorCoords'] = vector3(-442.10, 6010.05, 28.13),
    },
    [127] = { 
        ['Name'] = 'Ingang Verhoor Paleto',
        ['IsAGate'] = false,
        ['LockState'] = 4,
        ['Pickable'] = true,
        ['Authorized'] = {[1] = 'police'},
        ['LockDistance'] = 1.1,
        ['DoorName'] = 'v_ilev_ph_cellgate1',
        ['DoorCoords'] = vector3(-436.62, 6002.54, 28.14),
    },
    [128] = { 
        ['Name'] = 'Ingang Wapenkamer Paleto',
        ['IsAGate'] = false,
        ['LockState'] = 4,
        ['Pickable'] = true,
        ['Authorized'] = {[1] = 'police'},
        ['LockDistance'] = 1.1,
        ['DoorName'] = 'v_ilev_arm_secdoor',
        ['DoorCoords'] = vector3(-439.1576, 5998.157, 31.86815),
    },
    [129] = { 
        ['Name'] = 'Achter Paleto',
        ['IsAGate'] = false,
        ['LockState'] = 4,
        ['Pickable'] = true,
        ['Authorized'] = {[1] = 'police'},
        ['LockDistance'] = 1.1,
        ['DoorName'] = 'v_ilev_arm_secdoor',
        ['DoorCoords'] = vector3(-447.2363, 6002.317, 31.84003),
    }, 
    [130] = { 
        ['Name'] = 'SatudarahMC Gate',
        ['IsAGate'] = false,
        ['LockState'] = 4,
        ['Pickable'] = true,
        ['Authorized'] = {[1] = 'satudarah'},
        ['LockDistance'] = 5.0,
        ['DoorName'] = 'prop_facgate_07b',
        ['DoorCoords'] = vector3(105.30281, 327.60949, 112.10275),
    },  
    -- // Low Santos \\ --
}